import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React,{act} from "react"; import {createRoot} from "react-dom/client"; import {ApiClientError} from "@teaching-research-alliance/client";
let Panel,temp; const flush=()=>act(async()=>{await new Promise(r=>setTimeout(r,0))}); const props=n=>n[Object.keys(n).find(k=>k.startsWith("__reactProps$"))]; const session={sessionId:"s",accountId:"a",personId:"admin",roleContexts:[],currentRoleContext:{subject:"SYSTEM_ADMIN",scope:"GLOBAL",personId:"admin"}};
const directory={planners:[{personId:"planner",nickname:"规划师甲",currentMentorPersonId:null,currentMentorNickname:null,currentRelationshipId:null},{personId:"planner2",nickname:"规划师乙",currentMentorPersonId:"old",currentMentorNickname:"原导师",currentRelationshipId:"rel"}],mentors:[{personId:"mentor",nickname:"新导师"},{personId:"old",nickname:"原导师"}],currentWeeks:[{id:"week",startsOn:"2026-09-21",endsOn:"2026-09-27",settlementMonth:"2026-09-01"},{id:"week2",startsOn:"2026-09-28",endsOn:"2026-10-04",settlementMonth:"2026-10-01"}]}; const preview={previewId:"preview",action:"ADD",plannerPersonId:"planner",plannerNickname:"规划师甲",sourceMentorPersonId:null,sourceMentorNickname:null,newMentorPersonId:"mentor",newMentorNickname:"新导师",effectiveTeachingWeekId:"week",effectiveThroughTeachingWeekId:null,effectiveAt:"2026-09-21T00:00:00.000Z",nextBoundaryAt:null,consideredFeeCount:2,changedFeeCount:1,zeroShareFeeCount:1,excludedRefundCount:0,plannerDeltaCents:"100",sourceMentorDeltaCents:"0",destinationMentorDeltaCents:"100"};
test.before(async()=>{temp=await mkdtemp(resolve(import.meta.dirname,".admin-planning-mini-"));const out=resolve(temp,"panel.mjs");await build({entryPoints:[resolve(import.meta.dirname,"../src/pages/index/admin-planning-mentor-relationship-panel.tsx")],bundle:true,platform:"node",format:"esm",outfile:out,external:["react","react-dom","@teaching-research-alliance/client"],plugins:[{name:"taro",setup(api){api.onResolve({filter:/^@tarojs\/components$/},()=>({path:"taro",namespace:"stub"}));api.onLoad({filter:/.*/,namespace:"stub"},()=>({loader:"js",contents:`import React from 'react';export const View=({children,...p})=>React.createElement('div',p,children);export const Text=({children,...p})=>React.createElement('span',p,children);export const Button=({children,...p})=>React.createElement('button',p,children);export const Textarea=({onInput,...p})=>React.createElement('textarea',{...p,onInput});export const Picker=({children,onChange,...p})=>React.createElement('div',{...p,onChange,'data-picker':'true'},children);`}))}}]});Panel=(await import(out)).AdminPlanningMentorRelationshipPanel});test.after(async()=>{await rm(temp,{recursive:true,force:true})});
async function mount(overrides={}){const dom=new JSDOM("<div id='host'></div>",{url:"http://localhost"});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const host=document.querySelector("#host"),root=createRoot(host),calls=[];const client={hasRoleContext:true,listAdminPlanningMentorRelationshipCandidates:async()=>directory,previewAdminPlanningMentorRelationshipChange:async d=>{calls.push(d);return {...preview,action:d.action}},createAdminPlanningMentorRelationshipChangeSubmission:id=>({draft:{previewId:id},idempotencyKey:"key"}),publishAdminPlanningMentorRelationshipChange:async()=>({replay:false}),...overrides};await act(async()=>root.render(React.createElement(Panel,{client,session,sessionKey:"one",onInvalidated:()=>calls.push("invalid")})));await flush();return{host,calls,close:async()=>{await act(async()=>root.unmount());dom.window.close()}}}
test("小程序三种动作至少可生成预览",async()=>{for(const [action,index] of [["ADD",0],["REPLACE",1],["REMOVE",1]]){const ui=await mount();try{assert.match(ui.host.textContent,/特殊期前结束/);let p=[...ui.host.querySelectorAll("[data-picker='true']")];await act(async()=>props(p[0]).onChange({detail:{value:["ADD","REPLACE","REMOVE"].indexOf(action)}}));p=[...ui.host.querySelectorAll("[data-picker='true']")];await act(async()=>props(p[1]).onChange({detail:{value:index+1}}));p=[...ui.host.querySelectorAll("[data-picker='true']")];if(action!=="REMOVE")await act(async()=>props(p[2]).onChange({detail:{value:1}}));p=[...ui.host.querySelectorAll("[data-picker='true']")];await act(async()=>props(p[3]).onChange({detail:{value:1}}));await act(async()=>props(ui.host.querySelector("textarea")).onInput({detail:{value:"关系纠正"}}));await act(async()=>ui.host.querySelectorAll("button")[0].click());await flush();assert.match(ui.host.textContent,/规划导师/);assert.equal(ui.calls[0].action,action)}finally{await ui.close()}}});
test("小程序结束周、未知发布和身份隔离",async()=>{const ui=await mount();try{let p=[...ui.host.querySelectorAll("[data-picker='true']")];await act(async()=>props(p[3]).onChange({detail:{value:1}}));p=[...ui.host.querySelectorAll("[data-picker='true']")];assert.match(props(p[4]).range.join("|"),/2026-09-21/)}finally{await ui.close()}const denied=await mount({listAdminPlanningMentorRelationshipCandidates:async()=>{throw new ApiClientError(401,"UNAUTHENTICATED")}});try{await flush();assert.match(denied.host.textContent,/身份已失效/)}finally{await denied.close()}});
