import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";

const here = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(here, "../..");
const taroPlugin = { name: "bonus-panel-taro", setup(buildApi) {
  buildApi.onResolve({ filter: /^@tarojs\/components$/ }, () => ({ path: "bonus-components", namespace: "bonus-test" }));
  buildApi.onLoad({ filter: /.*/, namespace: "bonus-test" }, () => ({ loader: "js", contents: `import React from "react";
    export const View=({children,...props})=>React.createElement("div",props,children);
    export const Text=({children,...props})=>React.createElement("span",props,children);
    export const Button=({children,onClick,...props})=>React.createElement("button",{...props,onClick},children);
    export const Input=({onInput,...props})=>React.createElement("input",{...props,onInput:(e)=>onInput?.({detail:{value:e.currentTarget.value}})});
    export const Textarea=({onInput,...props})=>React.createElement("textarea",{...props,onInput:(e)=>onInput?.({detail:{value:e.currentTarget.value}})});` }));
} };
let bundle;
const getPanel = async () => {
  if (bundle) return bundle.module;
  const dir = await mkdtemp(resolve(here, ".bonus-panel-test-"));
  const output = resolve(dir, "panel.mjs");
  await build({ entryPoints: [resolve(rootDir, "miniapp/src/pages/index/bonus-project-panel.tsx")], bundle: true, format: "esm", platform: "node", outfile: output, external: ["react", "@teaching-research-alliance/client"], plugins: [taroPlugin] });
  bundle = { dir, module: await import(`${pathToFileURL(output).href}?${Date.now()}`) };
  return bundle.module;
};
test.after(async () => { if (bundle) await rm(bundle.dir, { recursive: true, force: true }); });
const projects = Array.from({ length: 10 }, (_, index) => ({ projectNo: index + 1, nameVersionId: `id-${index + 1}`, nameVersion: 1, displayName: `项目${index + 1}`, changedByPersonId: null, changeSource: "MIGRATION_DEFAULT", changedAt: "2026-09-23T00:00:00.000Z" }));
const session = (subject, scope = "GLOBAL") => ({ sessionId: `${subject}-${scope}`, accountId: "account-1", personId: "person-1", roleContexts: [{ subject, personId: "person-1", scope }], currentRoleContext: { subject, personId: "person-1", scope } });
const flush = async () => { await act(async () => { await Promise.resolve(); await new Promise((done) => setTimeout(done, 0)); }); };
const withDom = async (work) => { const dom = new JSDOM("<!doctype html><html><body><div id=app></div></body></html>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, Event: dom.window.Event, IS_REACT_ACT_ENVIRONMENT: true }); try { await work(dom.window.document.querySelector("#app")); } finally { dom.window.close(); } };
const click = async (element) => { await act(async () => element.dispatchEvent(new window.MouseEvent("click", { bubbles: true }))); await flush(); };
const input = async (element, value) => { await act(async () => { element.value = value; element.dispatchEvent(new window.Event("input", { bubbles: true })); }); await flush(); };
const button = (container, text) => [...container.querySelectorAll("button")].find((item) => item.textContent === text);
const mount = async (container, client, currentSession, callbacks = {}) => { const { BonusProjectPanel } = await getPanel(); const root = createRoot(container); await act(async () => root.render(React.createElement(BonusProjectPanel, { client, session: currentSession, sessionKey: currentSession.sessionId, onInvalidated: callbacks.invalidated, onSaved: callbacks.saved, onUnconfirmedChange: callbacks.unconfirmed }))); await flush(); return root; };
const deferred = () => { let resolve; let reject; const promise = new Promise((ok, fail) => { resolve = ok; reject = fail; }); return { promise, resolve, reject }; };
const clientFor = (options = {}) => { const submissions = []; const renameCalls = []; let listCount = 0; return { submissions, renameCalls, get listCount() { return listCount; }, currentSession: options.session, listBonusProjects: async () => { const index = listCount++; const result = options.listResults?.[index] ?? options.projects ?? projects; if (result?.promise) return { projects: await result.promise }; if (options.listError) throw options.listError; return { projects: result }; }, createBonusProjectRenameSubmission: (draft) => { const submission = { draft, idempotencyKey: `key-${submissions.length + 1}` }; submissions.push(submission); return submission; }, renameBonusProject: async (submission) => { renameCalls.push(submission); if (options.rename) return options.rename(submission, renameCalls.length); return { ...projects[submission.draft.projectNo - 1], displayName: submission.draft.displayName, nameVersion: submission.draft.expectedVersion + 1, replay: false }; }, hasRoleContext: true }; };
const projectOne = (nameVersion, displayName) => projects.map((item) => item.projectNo === 1 ? { ...item, nameVersion, displayName } : item);

test("SYSTEM_ADMIN可改名、HQ只读，成功回调并清除in-flight", async () => {
  await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const events = []; const client = clientFor({ session: admin }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("input"), "新项目名"); await input(row.querySelector("textarea"), "业务调整"); await click(button(row, "保存项目名称")); assert.deepEqual(client.submissions[0].draft, { projectNo: 1, expectedVersion: 1, displayName: "新项目名", reason: "业务调整" }); assert.equal(client.submissions[0].idempotencyKey, "key-1"); assert.equal(events.includes(true), true); assert.equal(events.at(-1), false); assert.deepEqual(events.filter((value) => value === "saved"), ["saved"]); await act(async () => root.unmount()); });
  await withDom(async (container) => { const hq = session("HEADQUARTERS_FINANCE"); const root = await mount(container, clientFor({ session: hq }), hq); assert.equal(container.querySelectorAll("button").length, 0); assert.match(container.textContent, /项目10/); await act(async () => root.unmount()); });
});

test("409证明初始v1到冲突后读取v2，不自动重发，核对后新命令成功清除冲突", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const events = []; const refresh = deferred(); const client = clientFor({ session: admin, listResults: [projectOne(1, "初始名"), refresh], rename: async (_submission, count) => { if (count === 1) throw new ApiClientError(409, "BONUS_PROJECT_VERSION_CONFLICT"); return {}; } }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); assert.equal(client.listCount, 2); assert.equal(client.renameCalls.length, 1); assert.equal(row.querySelector("input").disabled, true); assert.equal(button(row, "核对后重新提交").disabled, true); assert.ok(button(row, "重试读取最新版本")); assert.equal(events.at(-1), false); refresh.resolve(projectOne(2, "并发新名")); await flush(); assert.match(row.textContent, /并发新名|版本 2/); assert.ok(button(row, "核对后重新提交")); await click(button(row, "核对后重新提交")); assert.equal(client.renameCalls.length, 2); assert.equal(client.renameCalls[0].draft.expectedVersion, 1); assert.equal(client.renameCalls[1].draft.expectedVersion, 2); assert.notEqual(client.renameCalls[0].idempotencyKey, client.renameCalls[1].idempotencyKey); assert.equal(events.at(-1), false); assert.deepEqual(events.filter((value) => value === "saved"), ["saved"]); assert.doesNotMatch(container.textContent, /版本冲突/); await act(async () => root.unmount()); }); });

test("unknown锁住草稿，显式原命令重试捕获同一submission/key", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const events = []; const client = clientFor({ session: admin, rename: async (_submission, count) => { if (count === 1) throw new Error("network uncertain"); return {}; } }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); assert.match(container.textContent, /结果未确认/); assert.equal(row.querySelector("input").disabled, true); assert.equal(events.includes(true), true); await click(button(row, "使用原提交重试")); assert.equal(client.renameCalls.length, 2); assert.strictEqual(client.renameCalls[0], client.renameCalls[1]); assert.equal(client.renameCalls[0].idempotencyKey, client.renameCalls[1].idempotencyKey); assert.equal(events.at(-1), false); assert.deepEqual(events.filter((value) => value === "saved"), ["saved"]); await act(async () => root.unmount()); }); });

test("同项目保存双击只有一次在途rename", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const request = deferred(); const client = clientFor({ session: admin, rename: () => request.promise }); const root = await mount(container, client, admin); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); const saveButton = button(row, "保存项目名称"); await click(saveButton); await click(saveButton); assert.equal(client.renameCalls.length, 1); request.resolve({}); await flush(); await act(async () => root.unmount()); }); });

test("unknown重试双击只有一次重试请求", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const request = deferred(); const client = clientFor({ session: admin, rename: (_submission, count) => { if (count === 1) return Promise.reject(new Error("network uncertain")); return request.promise; } }); const root = await mount(container, client, admin); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); const retryButton = button(row, "使用原提交重试"); await click(retryButton); await click(retryButton); assert.equal(client.renameCalls.length, 2); assert.strictEqual(client.renameCalls[0], client.renameCalls[1]); request.resolve({}); await flush(); await act(async () => root.unmount()); }); });

test("整面板单写锁阻止跨项目提交；项目1重试成功后项目2恢复", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const events = []; const client = clientFor({ session: admin, rename: async (_submission, count) => { if (count === 1) throw new Error("timeout"); return {}; } }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row1 = container.querySelector('[data-project-no="1"]'); const row2 = container.querySelector('[data-project-no="2"]'); await input(row1.querySelector("textarea"), "理由1"); await click(button(row1, "保存项目名称")); assert.equal(row2.querySelector("input").disabled, true); assert.equal(button(row2, "保存项目名称").disabled, true); await click(button(row1, "使用原提交重试")); assert.equal(client.renameCalls.length, 2); assert.strictEqual(client.renameCalls[0], client.renameCalls[1]); assert.equal(events.at(-1), false); const freshRow2 = container.querySelector('[data-project-no="2"]'); assert.equal(freshRow2.querySelector("input").disabled, false); await act(async () => root.unmount()); });
  await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const rename = deferred(); const client = clientFor({ session: admin, rename: () => rename.promise }); const root = await mount(container, client, admin); const row1 = container.querySelector('[data-project-no="1"]'); const row2 = container.querySelector('[data-project-no="2"]'); await input(row1.querySelector("textarea"), "理由1"); await click(button(row1, "保存项目名称")); await click(button(row2, "保存项目名称")); assert.equal(client.renameCalls.length, 1); rename.resolve({}); await flush(); await act(async () => root.unmount()); });
});

test("同sessionKey同角色的新session对象不会丢弃在途rename", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const replacement = { ...admin, roleContexts: [...admin.roleContexts], currentRoleContext: { ...admin.currentRoleContext } }; const rename = deferred(); const events = []; const client = clientFor({ session: admin, rename: () => rename.promise }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); const { BonusProjectPanel } = await getPanel(); await act(async () => root.render(React.createElement(BonusProjectPanel, { client, session: replacement, sessionKey: admin.sessionId, onSaved: () => events.push("saved"), onUnconfirmedChange: (value) => events.push(value) }))); rename.resolve({}); await flush(); assert.deepEqual(events.filter((value) => value === "saved"), ["saved"]); assert.equal(events.at(-1), false); await act(async () => root.unmount()); }); });

test("400确定拒绝释放submission锁，允许编辑并提交新命令", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const client = clientFor({ session: admin, rename: async (_submission, count) => { if (count === 1) throw new ApiClientError(400, "INVALID_INPUT"); return {}; } }); const root = await mount(container, client, admin); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); assert.equal(row.querySelector("input").disabled, false); assert.ok(button(row, "保存项目名称")); await input(row.querySelector("textarea"), "修正理由"); await click(button(row, "保存项目名称")); assert.equal(client.renameCalls.length, 2); assert.notEqual(client.renameCalls[0].idempotencyKey, client.renameCalls[1].idempotencyKey); await act(async () => root.unmount()); }); });

test("409刷新失败仍阻断旧版本，重试读取成功后才允许核对提交", async () => { await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const failedRefresh = deferred(); const client = clientFor({ session: admin, listResults: [projectOne(1, "初始名"), failedRefresh, projectOne(2, "最终新名")], rename: async () => { throw new ApiClientError(409, "BONUS_PROJECT_VERSION_CONFLICT"); } }); const root = await mount(container, client, admin); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); failedRefresh.reject(new Error("read unavailable")); await flush(); assert.equal(row.querySelector("input").disabled, true); assert.ok(button(row, "重试读取最新版本")); assert.equal(button(row, "核对后重新提交").disabled, true); await click(button(row, "重试读取最新版本")); assert.match(row.textContent, /最终新名|版本 2/); assert.equal(button(row, "核对后重新提交").disabled, false); await act(async () => root.unmount()); }); });

test("身份切换用独立旧/新deferred，旧响应不污染新身份；401和403均清空并通知", async () => { await withDom(async (container) => { const oldDeferred = deferred(); const newDeferred = deferred(); const old = projectOne(1, "旧身份名称"); const fresh = projectOne(1, "新身份名称"); const admin = session("SYSTEM_ADMIN"); const hq = session("HEADQUARTERS_FINANCE"); const client = clientFor({ listResults: [oldDeferred, newDeferred] }); const root = await mount(container, client, admin); const { BonusProjectPanel } = await getPanel(); await act(async () => root.render(React.createElement(BonusProjectPanel, { client, session: hq, sessionKey: hq.sessionId }))); oldDeferred.resolve(old); await flush(); assert.doesNotMatch(container.textContent, /旧身份名称/); newDeferred.resolve(fresh); await flush(); assert.match(container.textContent, /新身份名称/); assert.doesNotMatch(container.textContent, /旧身份名称/); await act(async () => root.unmount()); });
  for (const status of [401, 403]) await withDom(async (container) => { const admin = session("SYSTEM_ADMIN"); const invalidations = []; const client = clientFor({ session: admin, listError: new ApiClientError(status, status === 401 ? "UNAUTHORIZED" : "FORBIDDEN_SCOPE") }); const root = await mount(container, client, admin, { invalidated: () => invalidations.push(true), unconfirmed: (value) => invalidations.push(value) }); assert.equal(invalidations.filter((value) => value === true).length, 1); assert.match(container.textContent, /身份已失效/); await act(async () => root.unmount()); });
});

test("迟到rename在切换身份并卸载后不得保存、提示或触发新身份reload", async () => { await withDom(async (container) => { const renameDeferred = deferred(); const admin = session("SYSTEM_ADMIN"); const hq = session("HEADQUARTERS_FINANCE"); const events = []; const client = clientFor({ rename: () => renameDeferred.promise }); const root = await mount(container, client, admin, { saved: () => events.push("saved"), unconfirmed: (value) => events.push(value) }); const row = container.querySelector('[data-project-no="1"]'); await input(row.querySelector("textarea"), "理由"); await click(button(row, "保存项目名称")); assert.equal(events.includes(true), true); const { BonusProjectPanel } = await getPanel(); await act(async () => root.render(React.createElement(BonusProjectPanel, { client, session: hq, sessionKey: hq.sessionId }))); const listCountBefore = client.listCount; await act(async () => root.unmount()); renameDeferred.resolve({}); await flush(); assert.deepEqual(events.filter((value) => value === "saved"), []); assert.equal(client.listCount, listCountBefore); }); });
