import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";

const here = dirname(fileURLToPath(import.meta.url)); const appRoot = resolve(here, "../.."); let compiled;
const taro = { name: "people-taro", setup(api) { api.onResolve({ filter: /^@tarojs\/components$/ }, () => ({ path: "components", namespace: "people-test" })); api.onLoad({ filter: /.*/, namespace: "people-test" }, () => ({ loader: "js", contents: `import React from "react"; export const View=({children,...p})=>React.createElement("div",p,children); export const Text=({children,...p})=>React.createElement("span",p,children); export const Button=({children,onClick,...p})=>React.createElement("button",{...p,onClick},children); export const Input=({onInput,...p})=>React.createElement("input",{...p,onInput:e=>onInput?.({detail:{value:e.currentTarget.value}})}); export const Textarea=({onInput,maxlength,...p})=>React.createElement("textarea",{...p,maxLength:maxlength,onInput:e=>onInput?.({detail:{value:e.currentTarget.value}})}); export const Picker=({children,range,...p})=>React.createElement("div",{...p,"data-range":JSON.stringify(range)},children);` })); } };
const panel = async () => { if (compiled) return compiled.module; const dir = await mkdtemp(resolve(here, ".people-panel-")); const outfile = resolve(dir, "panel.mjs"); await build({ entryPoints: [resolve(appRoot, "miniapp/src/pages/index/person-responsibility-panel.tsx")], bundle: true, platform: "node", format: "esm", outfile, external: ["react", "@teaching-research-alliance/client"], plugins: [taro] }); compiled = { dir, module: await import(`${pathToFileURL(outfile).href}?${Date.now()}`) }; return compiled.module; };
test.after(async () => { if (compiled) await rm(compiled.dir, { recursive: true, force: true }); });
const flush = async () => { await act(async () => { await Promise.resolve(); await new Promise((done) => setTimeout(done, 0)); }); };
const deferred = () => { let resolve; const promise = new Promise((done) => { resolve = done; }); return { promise, resolve }; };
const roleSession = (subject = "SYSTEM_ADMIN", patch = {}) => ({ sessionId: "s", accountId: "a", personId: "actor", roleContexts: [], currentRoleContext: { subject, scope: "GLOBAL", personId: "actor", ...patch } });
const person = (nickname = "成员甲", responsibilities = []) => ({ accountId: "a2", personId: "p2", nickname, legalName: "真实姓名", profileVersion: "1", phoneNormalized: "13800000000", loginStatus: "ACTIVE", personStatus: "ACTIVE", responsibilities });
const base = (overrides = {}) => ({ hasRoleContext: true, listPeople: async () => [person()], createRoleAssignmentSubmission: (draft) => ({ draft, idempotencyKey: "assign" }), assignRole: async () => ({ replay: false }), createRoleRevocationSubmission: (draft) => ({ draft, idempotencyKey: "revoke" }), revokeRole: async () => ({ replay: false }), createPersonStatusSubmission: (draft) => ({ draft, idempotencyKey: "status" }), setPersonStatus: async () => ({ replay: false }), ...overrides });
const withDom = async (work) => { const dom = new JSDOM("<!doctype html><div id=app></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true }); try { await work(document.querySelector("#app")); } finally { dom.window.close(); } };
const clickText = async (container, text) => { const node = [...container.querySelectorAll("button")].find((item) => item.textContent === text); assert.ok(node, text); await act(async () => node.dispatchEvent(new window.MouseEvent("click", { bubbles: true }))); await flush(); };
const input = async (node, value) => { await act(async () => { node.value = value; node.dispatchEvent(new window.Event("input", { bubbles: true })); }); await flush(); };

test("严格 GLOBAL 守卫，ADMIN 不显示管理员候选，OWNER 显示", async () => {
  const { canManageMiniPersonnel, PersonResponsibilityPanel } = await panel();
  assert.equal(canManageMiniPersonnel(roleSession()), true); assert.equal(canManageMiniPersonnel(roleSession("SYSTEM_ADMIN", { scope: "REGION", regionId: "r" })), false);
  await withDom(async (container) => { const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client: base(), session: roleSession(), sessionKey: "admin", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); const adminChoices = container.querySelectorAll("[data-range]")[1].getAttribute("data-range"); for (const label of ["系统管理员", "普通老师", "授课老师", "学业规划师", "场地运营"]) assert.doesNotMatch(adminChoices, new RegExp(label)); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client: base(), session: roleSession("SYSTEM_OWNER"), sessionKey: "owner", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); const ownerChoices = container.querySelectorAll("[data-range]")[1].getAttribute("data-range"); assert.match(ownerChoices, /系统管理员/); for (const label of ["普通老师", "授课老师", "学业规划师", "场地运营"]) assert.doesNotMatch(ownerChoices, new RegExp(label)); await act(async () => root.unmount()); });
});

test("身份切换后迟到目录不会覆盖新页面", async () => { await withDom(async (container) => { const old = deferred(); let reads = 0; const client = base({ listPeople: () => ++reads === 1 ? old.promise : Promise.resolve([person("新身份成员")]) }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "old", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "new", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); old.resolve([person("旧身份成员")]); await flush(); assert.match(container.textContent, /新身份成员/); assert.doesNotMatch(container.textContent, /旧身份成员/); await act(async () => root.unmount()); }); });

test("5xx 后使用同一冻结任命提交重试", async () => { await withDom(async (container) => { const submissions = []; let attempts = 0; const frozen = { draft: { personId: "p2", subject: "HEADQUARTERS_FINANCE", scope: "GLOBAL", validFrom: "2026-09-23T00:00:00.000Z", reason: "排班" }, idempotencyKey: "same" }; const client = base({ createRoleAssignmentSubmission: (draft) => { submissions.push(draft); return frozen; }, assignRole: async (submission) => { assert.equal(submission, frozen); if (++attempts === 1) throw new ApiClientError(500, "INTERNAL_ERROR"); return { replay: true }; } }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession("SYSTEM_OWNER"), sessionKey: "owner", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); await input(container.querySelector("textarea"), "排班"); await clickText(container, "确认任命"); assert.match(container.textContent, /尚未确认/); await clickText(container, "安全重试原操作"); assert.equal(attempts, 2); assert.equal(submissions.length, 1); assert.deepEqual({ ...submissions[0], validFrom: undefined }, { ...frozen.draft, validFrom: undefined }); assert.match(submissions[0].validFrom, /^\d{4}-\d{2}-\d{2}T00:00:00\.000Z$/); assert.match(container.textContent, /未重复执行/); await act(async () => root.unmount()); }); });

test("未来职责显示取消任命，并只向撤销草稿传职责和理由", async () => { await withDom(async (container) => { const drafts = []; const future = new Date(Date.now() + 86400000).toISOString(); const client = base({ listPeople: async () => [person("成员甲", [{ assignmentId: "future-role", subject: "GROUP_LEADER", scope: "ASSOCIATED_TEACHERS", validFrom: future, reason: "预排", createdByPersonId: "actor" }])], createRoleRevocationSubmission: (draft) => { drafts.push(draft); return { draft, idempotencyKey: "future" }; } }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "future", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.match(container.textContent, /取消任命/); await input(container.querySelector("textarea"), "计划取消"); await clickText(container, "取消任命"); assert.deepEqual(drafts, [{ assignmentId: "future-role", reason: "计划取消" }]); await act(async () => root.unmount()); }); });

test("管理员可查看系统身份但没有任何编辑控件", async () => { await withDom(async (container) => { const role = (subject) => ({ assignmentId: subject, subject, scope: "GLOBAL", validFrom: "2000-01-01T00:00:00.000Z", reason: null, createdByPersonId: "owner" }); const client = base({ listPeople: async () => [person("系统成员", [role("SYSTEM_ADMIN"), role("TEACHER"), role("VENUE_OWNER")])] }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "protected", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.match(container.textContent, /仅开发者可管理系统身份/); for (const text of ["撤销职责", "停用人员并注销会话", "确认任命"]) assert.equal([...container.querySelectorAll("button")].some((node) => node.textContent === text), false); await act(async () => root.unmount()); }); });

test("未来系统任命仍只读，零长度取消记录不误判", async () => { await withDom(async (container) => { const future = new Date(Date.now() + 86400000).toISOString(); const later = new Date(Date.now() + 172800000).toISOString(); const assignment = (validTo) => ({ assignmentId: "future-admin", subject: "SYSTEM_ADMIN", scope: "GLOBAL", validFrom: future, ...(validTo === undefined ? {} : { validTo }), reason: null, createdByPersonId: "owner" }); const client = base({ listPeople: async () => [person("未来管理员", [assignment(later)])] }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "future-admin", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.match(container.textContent, /仅开发者可管理系统身份/); client.listPeople = async () => [person("取消记录", [assignment(future)])]; await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "cancelled-admin", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.equal([...container.querySelectorAll("button")].some((node) => node.textContent === "确认任命"), true); await act(async () => root.unmount()); }); });

for (const status of [401, 403]) test(`${status} 触发上层身份失效处理`, async () => { await withDom(async (container) => { const invalidated = []; const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client: base({ listPeople: async () => { throw new ApiClientError(status, status === 401 ? "UNAUTHENTICATED" : "FORBIDDEN_SCOPE"); } }), session: roleSession(), sessionKey: `lost-${status}`, onUnconfirmedChange() {}, onInvalidated: () => invalidated.push(status) }))); await flush(); assert.deepEqual(invalidated, [status]); await act(async () => root.unmount()); }); });

test("停用人员不渲染任命按钮，也不创建任命提交", async () => { await withDom(async (container) => { let submissions = 0; const client = base({ listPeople: async () => [{ ...person("已停用成员"), personStatus: "INACTIVE" }], createRoleAssignmentSubmission: () => { submissions += 1; throw new Error("must not run"); } }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession(), sessionKey: "inactive", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.match(container.textContent, /请先恢复后再任命职责/); assert.equal([...container.querySelectorAll("button")].some((node) => node.textContent === "确认任命"), false); assert.equal(submissions, 0); await act(async () => root.unmount()); }); });

test("资料更正入口不显示敏感字段，并在未知结果时重试同一 submission", async () => { await withDom(async (container) => { const frozen = { draft: { personId: "p2", nickname: "新昵称", legalName: "新姓名", expectedProfileVersion: "1", reason: "资料核对" }, idempotencyKey: "profile-key" }; const submissions = []; let attempts = 0; const client = base({ createPersonProfileSubmission: (draft) => { submissions.push(draft); return frozen; }, updatePersonProfile: async (submission) => { assert.equal(submission, frozen); if (++attempts === 1) throw new ApiClientError(500, "INTERNAL_ERROR"); return { replay: true }; } }); const { PersonResponsibilityPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(PersonResponsibilityPanel, { client, session: roleSession("SYSTEM_OWNER"), sessionKey: "profile", onUnconfirmedChange() {}, onInvalidated() {} }))); await flush(); assert.doesNotMatch(container.textContent, /13800000000/); await input(container.querySelector("[aria-label='展示昵称']"), "新昵称"); await input(container.querySelector("[aria-label='真实姓名']"), "新姓名"); await input(container.querySelector("textarea"), "资料核对"); await clickText(container, "保存人员资料"); assert.match(container.textContent, /尚未确认/); await clickText(container, "安全重试原操作"); assert.equal(attempts, 2); assert.equal(submissions.length, 1); assert.match(container.textContent, /人员编号、账户和职责未变化/); assert.equal(container.querySelector("[aria-label='展示昵称']").disabled, false); assert.equal([...container.querySelectorAll("button")].find((node) => node.textContent === "保存人员资料").disabled, false); await act(async () => root.unmount()); }); });
