import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";

let Panel;let temp;
const flush=()=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};const props=node=>node[Object.keys(node).find(key=>key.startsWith("__reactProps$"))];
const session={sessionId:"session",accountId:"account",personId:"mentor",roleContexts:[],currentRoleContext:{personId:"mentor",subject:"PLANNING_MENTOR",scope:"SELF"}};
const directory={mentorPersonId:"mentor",mentorNickname:"导师甲",managedPlanners:[],availablePlanners:[{personId:"planner-2",nickname:"规划师乙"}],currentWeeks:[{id:"week-1",startsOn:"2026-09-21",endsOn:"2026-09-27",settlementMonth:"2026-09-01"}]};
const preview={previewId:"preview-1",action:"ADD",mentorPersonId:"mentor",plannerPersonId:"planner-2",plannerNickname:"规划师乙",effectiveTeachingWeekId:"week-1",effectiveAt:"2026-09-20T16:00:00.000Z",nextBoundaryAt:null,consideredFeeCount:1,changedFeeCount:1,zeroShareFeeCount:0,excludedRefundCount:0,plannerDeltaCents:"-80",mentorDeltaCents:"80"};

test.before(async()=>{temp=await mkdtemp(resolve(import.meta.dirname,".planning-mentor-mini-"));const out=resolve(temp,"panel.mjs");await build({entryPoints:[resolve(import.meta.dirname,"../src/pages/index/planning-mentor-relationship-panel.tsx")],bundle:true,platform:"node",format:"esm",outfile:out,external:["react","react-dom","@teaching-research-alliance/client"],plugins:[{name:"taro",setup(api){api.onResolve({filter:/^@tarojs\/components$/},()=>({path:"taro",namespace:"stub"}));api.onLoad({filter:/.*/,namespace:"stub"},()=>({loader:"js",contents:`import React from 'react';export const View=({children,...p})=>React.createElement('div',p,children);export const Text=({children,...p})=>React.createElement('span',p,children);export const Button=({children,...p})=>React.createElement('button',p,children);export const Textarea=({onInput,...p})=>React.createElement('textarea',{...p,onInput});export const Picker=({children,onChange,...p})=>React.createElement('div',{...p,onChange,'data-picker':'true'},children);`}));}}]});Panel=(await import(out)).PlanningMentorRelationshipPanel;});
test.after(async()=>{await rm(temp,{recursive:true,force:true});});

async function mount(overrides={}){const dom=new JSDOM("<div id='host'></div>",{url:"http://localhost"});Object.assign(globalThis,{window:dom.window,document:dom.window.document,IS_REACT_ACT_ENVIRONMENT:true});const host=document.querySelector("#host"),root=createRoot(host),calls=[],locks=[];const client={hasRoleContext:true,listPlanningMentorRelationships:async()=>directory,previewPlanningMentorRelationshipChange:async()=>preview,createPlanningMentorRelationshipChangeSubmission:previewId=>({draft:{previewId},idempotencyKey:"mini-stable"}),publishPlanningMentorRelationshipChange:command=>{calls.push(command);return Promise.resolve({replay:false});},...overrides};await act(async()=>root.render(React.createElement(Panel,{client,session,sessionKey:"one",onUnconfirmedChange:value=>locks.push(value)})));await flush();const button=text=>[...host.querySelectorAll("button")].find(node=>node.textContent===text);const pick=async(index,value)=>{const node=host.querySelectorAll("[data-picker='true']")[index];assert.ok(node);await act(async()=>props(node).onChange({detail:{value:String(value)}}));};const fill=async()=>{await pick(1,1);await pick(2,1);const area=host.querySelector("textarea");await act(async()=>props(area).onInput({detail:{value:"本周纳入管理"}}));};return{host,root,dom,calls,locks,button,fill,close:async()=>{await act(async()=>root.unmount());dom.window.close();}};}

test("小程序规划导师预览和未知发布复用同一命令",async()=>{const wait=deferred(),commands=[];const v=await mount({publishPlanningMentorRelationshipChange:command=>{commands.push(command);return commands.length===1?wait.promise:Promise.resolve({replay:true});}});try{await v.fill();await act(async()=>v.button("生成关系影响预览").click());await flush();assert.match(v.host.textContent,/介绍池总额不增加/);await act(async()=>{const publish=v.button("确认发布关系变更");publish.click();publish.click();});assert.equal(commands.length,1);await act(async()=>wait.reject(new Error("offline")));await flush();assert.equal(v.locks.at(-1),true);await act(async()=>v.host.querySelector("[data-planning-mentor-action='retry-publish']").click());await flush();assert.equal(commands.length,2);assert.strictEqual(commands[0],commands[1]);}finally{await v.close();}});
