import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "../../../packages/client/dist/index.js";

let temp; let Managed; let Received;
const flush = () => act(async () => { await new Promise(done => setTimeout(done, 0)); });
const referral = (status = "ACCEPTED", id = "referral-a") => ({ referralId: id, studentDisplayName: "学生甲", courseContextId: "数学", receiverPersonId: "receiver", receiverNickname: "接收老师", referrerPersonId: "referrer", referrerNickname: "推荐老师", referralStatus: status, version: 3, submittedAt: "2026-09-24T00:00:00Z" });
const taro = { name: "taro", setup(api) { api.onResolve({ filter: /^@tarojs\/components$/ }, () => ({ path: "taro", namespace: "stub" })); api.onLoad({ filter: /.*/, namespace: "stub" }, () => ({ loader: "js", contents: "import React from 'react';export const View=({children,...p})=>React.createElement('div',p,children);export const Text=({children,...p})=>React.createElement('span',p,children);export const Button=({children,...p})=>React.createElement('button',p,children);" })); } };
test.before(async () => { temp = await mkdtemp(resolve(import.meta.dirname, ".referral-completion-")); const bundle = async (name, source) => { const output = resolve(temp, `${name}.mjs`); await build({ entryPoints: [resolve(import.meta.dirname, source)], bundle: true, platform: "node", format: "esm", outfile: output, external: ["react", "@teaching-research-alliance/client"], plugins: [taro] }); return import(output); }; ({ ManagedReferralCompletionPanel: Managed } = await bundle("managed", "../src/pages/index/managed-referral-completion-panel.tsx")); ({ ReceivedReferralCompletionPanel: Received } = await bundle("received", "../src/pages/index/received-referral-completion-panel.tsx")); });
test.after(async () => { await rm(temp, { recursive: true, force: true }); });
async function mount(Component, props) { const dom = new JSDOM("<div id='root'></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true }); const host = document.querySelector("#root"), root = createRoot(host), invalidated = [], locks = []; const render = async extra => { await act(async () => root.render(React.createElement(Component, { busy: false, sessionKey: "s", onInvalidated: () => invalidated.push(true), onUnconfirmedChange: value => locks.push(value), ...props, ...extra }))); await flush(); }; await render(); const click = async text => { const node = [...host.querySelectorAll("button")].find(x => x.textContent === text); assert.ok(node, text); await act(async () => node.click()); await flush(); }; return { host, render, click, locks, invalidated, close: async () => { await act(async () => root.unmount()); dom.window.close(); } }; }

test("小程序管理员成功完结并展示已完结", async () => { const commands = []; const client = { listManagedReferrals: async () => [referral(), referral("COMPLETED", "referral-b")], createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "stable" }), changeReferralLifecycle: async command => { commands.push(command); return {}; } }; const ui = await mount(Managed, { client }); try { await ui.click("完结课程"); assert.equal(commands.length, 1); assert.equal(commands[0].draft.command, "COMPLETE"); assert.match(ui.host.textContent, /学生课程已完结/); assert.match(ui.host.textContent, /完结撒花/); } finally { await ui.close(); } });
test("小程序管理员未知结果保留原命令，403清理身份", async () => { const commands = []; let first = true; const client = { listManagedReferrals: async () => [referral()], createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "stable" }), changeReferralLifecycle: async command => { commands.push(command); if (first) { first = false; throw new Error("network"); } throw new ApiClientError(403, "FORBIDDEN_SCOPE"); } }; const ui = await mount(Managed, { client }); try { await ui.click("完结课程"); assert.match(ui.host.textContent, /结果尚未确认/); await ui.click("安全重试原完结操作"); assert.equal(commands[0], commands[1]); assert.equal(ui.invalidated.length, 1); } finally { await ui.close(); } });
test("小程序接收老师完结成功，身份切换后的迟到结果不污染", async () => { let changed = 0; let resolve; const wait = new Promise(done => { resolve = done; }); const client = { createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "receiver-stable" }), changeReferralLifecycle: () => wait }; const ui = await mount(Received, { client, referrals: [referral()], onChanged: async () => { changed += 1; } }); try { await ui.click("完结课程"); await ui.render({ sessionKey: "other", referrals: [] }); await act(async () => resolve({})); await flush(); assert.equal(changed, 0); assert.doesNotMatch(ui.host.textContent, /学生课程已完结/); } finally { await ui.close(); } });
