import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";

const testDirectory = dirname(fileURLToPath(import.meta.url));
const miniappDirectory = resolve(testDirectory, "..");
const taroPlugin = { name: "refund-test-taro", setup(buildApi) {
  buildApi.onResolve({ filter: /^@tarojs\/taro$/ }, () => ({ path: "taro", namespace: "refund-test" }));
  buildApi.onResolve({ filter: /^@tarojs\/components$/ }, () => ({ path: "components", namespace: "refund-test" }));
  buildApi.onLoad({ filter: /.*/, namespace: "refund-test" }, (args) => ({ loader: "js", contents: args.path === "taro" ? "export default new Proxy({}, {get:()=>async()=>({})});" : `import React from 'react'; export const View=({children,...p})=>React.createElement('div',p,children); export const Text=({children,...p})=>React.createElement('span',p,children); export const Button=({children,...p})=>React.createElement('button',p,children); export const Input=({onInput,maxlength,...p})=>React.createElement('input',{...p,maxLength:maxlength,onInput:e=>onInput?.({detail:{value:e.currentTarget.value}})}); export const Textarea=({onInput,maxlength,...p})=>React.createElement('textarea',{...p,maxLength:maxlength,onInput:e=>onInput?.({detail:{value:e.currentTarget.value}})}); export const Picker=({children,range=[],value=0,onChange,...p})=>React.createElement('div',p,React.createElement('select',{value:String(value),onChange:e=>onChange?.({detail:{value:e.currentTarget.value}})},range.map((item,index)=>React.createElement('option',{key:index,value:String(index)},String(item)))),children);` }));
}};
let bundled;
const panel = async () => { if (bundled) return bundled.module; const directory = await mkdtemp(resolve(testDirectory, ".refund-panel-test-")); const output = resolve(directory, "panel.mjs"); await build({ entryPoints: [resolve(miniappDirectory, "src/pages/index/refund-panel.tsx")], bundle: true, format: "esm", platform: "node", outfile: output, define: { __API_BASE_URL__: JSON.stringify("http://127.0.0.1:3100") }, external: ["react", "@teaching-research-alliance/client"], plugins: [taroPlugin] }); bundled = { directory, module: await import(`${pathToFileURL(output).href}?${Date.now()}`) }; return bundled.module; };
test.after(async () => { if (bundled) await rm(bundled.directory, { recursive: true, force: true }); });
const draft = { id: "refund-draft", kind: "REFUND", status: "DRAFT", version: 1, createdAt: "2026-09-21T00:00:00Z", updatedAt: "2026-09-21T00:00:00Z" };
const summary = { id: "refund-1", status: "PENDING_APPROVAL", version: 2, reason: "合成退款", applicantPersonId: "p1", applicantDisplayName: "合成老师", referralCaseId: "r1", studentRecordId: "s1", studentDisplayName: "学生甲", submittedAt: "2026-09-21T00:00:00Z", submittedGrossAmountCents: "1000", selectedFeeCount: 1 };
const candidate = { weeklyFeeEntryId: "fee-1", referralCaseId: "r1", studentRecordId: "s1", studentDisplayName: "学生甲", courseContextId: "一对一", teachingWeekId: "week-1", settlementMonth: "2026-09", grossAmountCents: "1000", refundStatus: "ACTIVE" };
const sameCourseCandidate = { ...candidate, weeklyFeeEntryId: "fee-2", teachingWeekId: "week-2", grossAmountCents: "2000" };
const otherCourseCandidate = { ...candidate, weeklyFeeEntryId: "fee-3", referralCaseId: "r2", studentRecordId: "s2", studentDisplayName: "学生乙", courseContextId: "英语" };
const session = (subject, scope = "SELF") => ({ sessionId: `session-${subject}`, accountId: "a1", personId: "p1", currentRoleContext: { subject, personId: "p1", scope }, roleContexts: [{ subject, personId: "p1", scope }] });
const readyAttachments = { attachments: [{ attachmentId: "support", purpose: "SUPPORTING_DOCUMENT", createdAt: "2026-09-21T00:00:00Z", versions: [{ versionId: "support-v1", versionNo: 1, status: "READY", originalFilename: "support.png", declaredMediaType: "image/png", declaredSizeBytes: 8, createdAt: "2026-09-21T00:00:00Z" }] }, { attachmentId: "shot", purpose: "APPLICATION_SCREENSHOT", createdAt: "2026-09-21T00:00:00Z", versions: [{ versionId: "shot-v1", versionNo: 1, status: "READY", originalFilename: "shot.png", declaredMediaType: "image/png", declaredSizeBytes: 8, createdAt: "2026-09-21T00:00:00Z" }] }] };
const makeClient = (currentSession, options = {}) => { const calls = []; let submitCount = 0; return { calls, currentSession, hasRoleContext: true, listOwnRefunds: async () => ({ documents: [] }), listManagedRefunds: async () => ({ documents: options.managed ? [summary] : [] }), listOwnFinanceDrafts: async () => [draft], getOwnFinanceDraft: async () => draft, listFinanceDocumentAttachments: async () => readyAttachments, getRefundDetail: async () => ({ ...summary, attachments: [], selectedFees: [{ weeklyFeeEntryId: "fee-1", submittedFeeVersion: 1, submittedGrossAmountCents: "1000", teachingWeekId: "week-1", settlementMonth: "2026-09", refundStatus: "ACTIVE" }] }), createFinanceDraftSubmission: () => ({ idempotencyKey: "create-key" }), createFinanceDraft: async () => draft, createRefundSubmission: (value) => ({ draft: value, idempotencyKey: "refund-key" }), submitRefund: async (value) => { calls.push(value); submitCount += 1; if (options.unknownSubmit && submitCount === 1) throw new Error("network uncertain"); return { id: "refund-1", status: "PENDING_APPROVAL", version: 2, replay: submitCount > 1 }; }, createRefundReviewSubmission: (value) => ({ draft: value, idempotencyKey: "review-key" }), reviewRefund: async (value) => { calls.push(value); return { id: "refund-1", status: value.draft.decision === "APPROVE" ? "REFUNDED" : "REJECTED", version: 3, replay: false }; } }; };
const flush = async () => { await act(async () => { await Promise.resolve(); await new Promise((done) => setTimeout(done, 0)); }); };
const button = (root, text) => { const found = [...root.querySelectorAll("button")].find((item) => item.textContent === text); assert.ok(found, `button ${text}`); return found; };
const click = async (node) => { await act(async () => node.dispatchEvent(new window.MouseEvent("click", { bubbles: true }))); await flush(); };
const input = async (node, value) => { await act(async () => { node.value = value; node.dispatchEvent(new window.Event("input", { bubbles: true })); }); await flush(); };
const withDom = async (work) => { const dom = new JSDOM("<div id=app></div>"); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true }); try { await work(dom.window.document.querySelector("#app")); } finally { dom.window.close(); } };
const mount = async (container, client, currentSession, mode, feeCandidates = [candidate]) => { const { RefundPanel } = await panel(); const root = createRoot(container); await act(async () => root.render(React.createElement(RefundPanel, { client, session: currentSession, mode, feeCandidates, onInvalidated: () => {}, onBusyChange: () => {}, onUnconfirmedChange: () => {} }))); await flush(); return root; };

test("授课老师可冻结费用与原键安全重试；规划师不可提交", async () => { await withDom(async (container) => { const teacherSession = session("TEACHING_TEACHER"); const client = makeClient(teacherSession, { unknownSubmit: true }); const root = await mount(container, client, teacherSession, "personal"); await click(button(container, "继续填写退款")); await input(container.querySelector("input"), "学生退课"); await click(button(container, "选择")); await click(button(container, "确认提交退款申请")); assert.ok(container.querySelector('[data-refund-pending="submit"]')); await click(button(container, "安全重试原退款申请")); assert.equal(client.calls.length, 2); assert.equal(client.calls[0].idempotencyKey, client.calls[1].idempotencyKey); assert.deepEqual(client.calls[0].draft.weeklyFeeEntryIds, ["fee-1"]); await act(async () => root.unmount()); }); await withDom(async (container) => { const plannerSession = session("ACADEMIC_PLANNER"); const root = await mount(container, makeClient(plannerSession), plannerSession, "personal"); assert.equal(button(container, "新建退款申请").disabled, true); await act(async () => root.unmount()); }); });
test("仅 strict GLOBAL 总部财务可审核，管理员只读", async () => { await withDom(async (container) => { const hqSession = session("HEADQUARTERS_FINANCE", "GLOBAL"); const client = makeClient(hqSession, { managed: true }); const root = await mount(container, client, hqSession, "managed"); await click(button(container, "查看退款详情")); await input(container.querySelector("textarea"), "资料完整"); await click(button(container, "批准退款申请")); assert.equal(client.calls[0].draft.decision, "APPROVE"); await act(async () => root.unmount()); }); await withDom(async (container) => { const adminSession = session("SYSTEM_ADMIN", "GLOBAL"); const root = await mount(container, makeClient(adminSession, { managed: true }), adminSession, "managed"); await click(button(container, "查看退款详情")); assert.equal([...container.querySelectorAll("button")].some((item) => /批准退款申请|驳回退款申请/.test(item.textContent)), false); await act(async () => root.unmount()); }); });

test("退款先选学生课程，同课程可多选周费用，切换课程会清空旧选择", async () => { await withDom(async (container) => { const teacherSession = session("TEACHING_TEACHER"); const root = await mount(container, makeClient(teacherSession), teacherSession, "personal", [candidate, sameCourseCandidate, otherCourseCandidate]); await click(button(container, "继续填写退款")); const coursePicker = container.querySelector("select"); assert.ok(coursePicker); const feeButtons = () => [...container.querySelectorAll("button")].filter((item) => item.textContent === "选择" || item.textContent === "已选"); assert.equal(feeButtons().length, 2); await click(feeButtons()[0]); assert.equal(feeButtons()[0].textContent, "已选"); await act(async () => { coursePicker.value = "1"; coursePicker.dispatchEvent(new window.Event("change", { bubbles: true })); }); await flush(); assert.equal(feeButtons().every((item) => item.textContent === "选择"), true); await act(async () => root.unmount()); }); });
