import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React,{act} from "react"; import {createRoot} from "react-dom/client"; import {ApiClientError} from "@teaching-research-alliance/client";
let Panel,temp; const flush=()=>act(async()=>{await new Promise(r=>setTimeout(r,0))}); const props=n=>n[Object.keys(n).find(k=>k.startsWith("__reactProps$"))]; const session={sessionId:"s",accountId:"a",personId:"admin",roleContexts:[],currentRoleContext:{subject:"SYSTEM_ADMIN",scope:"GLOBAL",personId:"admin"}}; const directory={teachers:[{personId:"teacher",nickname:"老师甲",currentMentorPersonId:null,currentMentorNickname:null,currentRelationshipId:null},{personId:"teacher2",nickname:"老师乙",currentMentorPersonId:null,currentMentorNickname:null,currentRelationshipId:null}],mentors:[{personId:"mentor",nickname:"导师乙",eligibleTeacherPersonIds:null},{personId:"directed",nickname:"定向导师",eligibleTeacherPersonIds:["teacher"]}],currentWeeks:[{id:"week",startsOn:"2026-09-21",endsOn:"2026-09-27",settlementMonth:"2026-09-01"},{id:"week2",startsOn:"2026-09-28",endsOn:"2026-10-04",settlementMonth:"2026-10-01"}]}; const preview={previewId:"preview",action:"ADD",teacherPersonId:"teacher",sourceRelatedPersonId:null,sourceRelatedNickname:null,newRelatedPersonId:"mentor",newRelatedNickname:"导师乙",effectiveTeachingWeekId:"week",effectiveThroughTeachingWeekId:null,effectiveAt:"2026-09-21T00:00:00.000Z",nextBoundaryAt:null,consideredFeeCount:2,movedFeeCount:2,zeroShareFeeCount:0,excludedRefundCount:0,movedAmountCents:"1200"};
test.before(async()=>{temp=await mkdtemp(resolve(import.meta.dirname,".teaching-mentor-mini-"));const out=resolve(temp,"panel.mjs");await build({entryPoints:[resolve(import.meta.dirname,"../src/pages/index/teaching-mentor-change-panel.tsx")],bundle:true,platform:"node",format:"esm",outfile:out,external:["react","react-dom","@teaching-research-alliance/client"],plugins:[{name:"taro",setup(api){api.onResolve({filter:/^@tarojs\/components$/},()=>({path:"taro",namespace:"stub"}));api.onLoad({filter:/.*/,namespace:"stub"},()=>({loader:"js",contents:`import React from 'react';export const View=({children,...p})=>React.createElement('div',p,children);export const Text=({children,...p})=>React.createElement('span',p,children);export const Button=({children,...p})=>React.createElement('button',p,children);export const Textarea=({onInput,...p})=>React.createElement('textarea',{...p,onInput});export const Picker=({children,onChange,...p})=>React.createElement('div',{...p,onChange,'data-picker':'true'},children);`}))}}]});Panel=(await import(out)).TeachingMentorChangePanel});test.after(async()=>{await rm(temp,{recursive:true,force:true})});
async function mount(overrides={}){const dom=new JSDOM("<div id='host'></div>",{url:"http://localhost"});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const host=document.querySelector("#host"),root=createRoot(host),client={hasRoleContext:true,listTeachingMentorRelationshipCandidates:async()=>directory,previewTeachingMentorRelationshipChange:async()=>preview,createTeachingMentorRelationshipChangeSubmission:id=>({draft:{previewId:id},idempotencyKey:"key"}),publishTeachingMentorRelationshipChange:async()=>({replay:false}),...overrides};await act(async()=>root.render(React.createElement(Panel,{client,session,sessionKey:"one",onInvalidated:()=>{}})));await flush();return{host,close:async()=>{await act(async()=>root.unmount());dom.window.close()}}}
test("小程序预览与发布状态可观察",async()=>{const ui=await mount();try{const pickers=[...ui.host.querySelectorAll("[data-picker='true']")];await act(async()=>props(pickers[0]).onChange({detail:{value:"1"}}));assert.match(props(pickers[1]).range.join("|"),/定向导师/);await act(async()=>props(pickers[1]).onChange({detail:{value:"1"}}));await act(async()=>props(pickers[2]).onChange({detail:{value:"1"}}));await act(async()=>props(ui.host.querySelector("textarea")).onInput({detail:{value:"导师调整"}}));await act(async()=>ui.host.querySelectorAll("button")[0].click());await flush();assert.match(ui.host.textContent,/新增教学导师/);assert.match(ui.host.textContent,/迁移金额/)}finally{await ui.close()}});
test("小程序权限错误清理身份",async()=>{const ui=await mount({listTeachingMentorRelationshipCandidates:async()=>{throw new ApiClientError(401,"UNAUTHENTICATED")}});try{await flush();assert.match(ui.host.textContent,/身份已失效/)}finally{await ui.close()}});

test("小程序结束普通周包含开始周并清除过早结束周", async () => { const ui = await mount(); try { let pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[2]).onChange({ detail: { value: "1" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; assert.match(props(pickers[3]).range.join("|"), /2026-09-21/); await act(async () => props(pickers[3]).onChange({ detail: { value: "1" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[2]).onChange({ detail: { value: "2" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; assert.equal(props(pickers[3]).value, 0); } finally { await ui.close(); } });

test("小程序切换授课老师会清空旧定向导师且禁止提交", async () => { const calls = []; const ui = await mount({ previewTeachingMentorRelationshipChange: async (draft) => { calls.push(draft); return preview; } }); try { let pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[0]).onChange({ detail: { value: "1" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[1]).onChange({ detail: { value: "2" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[2]).onChange({ detail: { value: "1" } })); await act(async () => props(ui.host.querySelector("textarea")).onInput({ detail: { value: "导师调整" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; await act(async () => props(pickers[0]).onChange({ detail: { value: "2" } })); pickers = [...ui.host.querySelectorAll("[data-picker='true']")]; assert.equal(props(pickers[1]).value, 0); await act(async () => ui.host.querySelectorAll("button")[0].click()); await flush(); assert.equal(calls.length, 0); assert.match(ui.host.textContent, /请选择授课老师、教学导师和普通周/); } finally { await ui.close(); } });
