import { useEffect, useRef, useState, type ReactNode } from "react";
import { ApiClientError, RoleSelectionRequiredError, type SessionSnapshot, type TeacherApiClient, type CashWagePlanSubmission } from "@teaching-research-alliance/client";

type Props = { client: TeacherApiClient; session: SessionSnapshot; sessionKey: string; onInvalidated?: () => void; onSaved?: () => void; onUnconfirmedChange?: (pending: boolean) => void };
const yuanToCents = (value: string): string => { if (!/^\d+(?:\.\d{1,2})?$/.test(value.trim())) throw new Error("金额需为非负数字，最多两位小数"); const [whole = "0", fraction = ""] = value.trim().split("."); return `${BigInt(whole) * 100n + BigInt(fraction.padEnd(2, "0") || "0")}`; };
const monthNow = (): string => { const p = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit" }).formatToParts(new Date()); return `${p.find(x => x.type === "year")?.value}-${p.find(x => x.type === "month")?.value}-01`; };
const canWrite = (session: SessionSnapshot): boolean => { const c = session.currentRoleContext; return c?.scope === "GLOBAL" && c.regionId === undefined && c.campusId === undefined && c.venueId === undefined && ["HEADQUARTERS_FINANCE", "SYSTEM_ADMIN", "SYSTEM_OWNER"].includes(c.subject); };

export function CashWagePlanPanel({ client, session, sessionKey, onInvalidated, onSaved, onUnconfirmedChange }: Props): ReactNode {
  const [teachers, setTeachers] = useState<readonly { id: string; nickname: string }[] | null>(null); const [teacherId, setTeacherId] = useState(""); const [month, setMonth] = useState(monthNow); const [cash, setCash] = useState(""); const [deduction, setDeduction] = useState(""); const [active, setActive] = useState(true); const [future, setFuture] = useState(false); const [reason, setReason] = useState(""); const [message, setMessage] = useState(""); const [state, setState] = useState<"idle"|"pending"|"unknown">("idle"); const [submission, setSubmission] = useState<CashWagePlanSubmission | null>(null); const generation = useRef(0); const [directoryRevision, setDirectoryRevision] = useState(0);
  const authorized = canWrite(session);
  const fail = (error: unknown): void => { if (error instanceof RoleSelectionRequiredError || error instanceof ApiClientError && [401, 403].includes(error.status) || client.hasRoleContext === false) { setTeachers(null); onInvalidated?.(); setMessage("登录或身份已失效，请重新登录或选择身份。"); return; } setMessage(error instanceof Error ? error.message : "工资计划保存失败，请重试。"); };
  useEffect(() => { const token = ++generation.current; setTeachers(null); setTeacherId(""); setCash(""); setDeduction(""); setReason(""); setActive(true); setFuture(false); setSubmission(null); setState("idle"); setMessage(""); if (!authorized) return; let alive = true; void client.listManagedCashWageTeachers().then(result => { if (alive && generation.current === token) setTeachers(result.items); }).catch(error => { if (alive && generation.current === token) fail(error); }); return () => { alive = false; generation.current += 1; }; }, [client, sessionKey, authorized, directoryRevision]);
  useEffect(() => { onUnconfirmedChange?.(state !== "idle"); return () => onUnconfirmedChange?.(false); }, [state, onUnconfirmedChange]);
  if (!authorized) return <section className="panel" aria-label="工资计划维护"><h2>工资计划</h2><p>当前身份没有维护总部工资计划的权限。</p></section>;
  const save = async (): Promise<void> => { setMessage(""); const token = generation.current; let next = submission; if (!next) { try { const draft = { teacherPersonId: teacherId, salaryMonth: month, plannedCashCents: yuanToCents(cash), plannedDeductionCents: yuanToCents(deduction), active, applyToFutureMonths: future, reason: reason.trim() }; if (!teacherId || !draft.reason) throw new Error("请选择老师并填写理由"); if (draft.plannedCashCents !== draft.plannedDeductionCents) throw new Error("现金计划与扣豆计划必须一致"); next = client.createCashWagePlanSubmission(draft); } catch (error) { fail(error); return; } setSubmission(next); } setState("pending"); try { await client.setCashWagePlan(next); if (generation.current !== token) return; setMessage("工资计划已保存；本次仅保存计划，不产生已发或已扣豆记录。"); setSubmission(null); setState("idle"); onSaved?.(); } catch (error) { if (generation.current !== token) return; if (error instanceof RoleSelectionRequiredError || error instanceof ApiClientError && [401,403].includes(error.status)) { fail(error); return; } if (error instanceof ApiClientError && error.status === 400) { setSubmission(null); setState("idle"); setMessage(error.message || "输入不符合要求，请修改后重试。"); } else { setState("unknown"); setMessage("工资计划结果未确认，请使用原提交重试。"); } } };
  const locked = state !== "idle";
  return <section className="panel" aria-label="工资计划维护"><h2>工资计划</h2>{teachers === null ? <p role="status">{message || "正在读取可维护老师名单…"}</p> : teachers.length === 0 ? <p role="alert">当前身份下没有可维护的工资名单。</p> : <form onSubmit={e => { e.preventDefault(); if (!locked) void save(); }}><label>老师<select aria-label="老师" value={teacherId} disabled={locked} onChange={e => setTeacherId(e.target.value)}><option value="">请选择</option>{teachers.map(t => <option value={t.id} key={t.id}>{t.nickname}</option>)}</select></label><label>工资月<input type="month" value={month.slice(0, 7)} disabled={locked} onChange={e => setMonth(`${e.target.value}-01`)} /></label><label>现金计划（元）<input inputMode="decimal" value={cash} disabled={locked} onChange={e => setCash(e.target.value)} /></label><label>扣豆计划（欢乐豆）<input inputMode="decimal" value={deduction} disabled={locked} onChange={e => setDeduction(e.target.value)} /></label><label><input type="checkbox" checked={active} disabled={locked} onChange={e => setActive(e.target.checked)} />启用工资计划</label><fieldset><legend>适用范围</legend><label><input type="radio" checked={!future} disabled={locked} onChange={() => setFuture(false)} />仅选定月份</label><label><input type="radio" checked={future} disabled={locked} onChange={() => setFuture(true)} />从选定月份起</label></fieldset><label>理由<textarea aria-label="理由" required value={reason} disabled={locked} onChange={e => setReason(e.target.value)} /></label><button type="submit" disabled={locked}>{state === "pending" ? "保存中…" : state === "unknown" ? "结果未确认" : "保存工资计划"}</button>{state === "unknown" && <button type="button" onClick={() => void save()}>使用原提交重试</button>}</form>}{message && teachers !== null && <p role="status">{message}</p>}{teachers === null && message && <button type="button" onClick={() => setDirectoryRevision(value => value + 1)}>重试读取名单</button>}</section>;
}
