import { useEffect, useRef, useState, type ReactNode } from "react";
import { ApiClientError, StaleResponseError, type ManagedReferral, type ReferralLifecycleSubmission, type TeacherApiClient } from "@teaching-research-alliance/client";

type Props = Readonly<{ client: TeacherApiClient; sessionKey: string; busy: boolean; active: boolean; onUnconfirmedChange: (value: boolean) => void; onInvalidated: () => void }>;
const labels: Readonly<Record<ManagedReferral["referralStatus"], string>> = { ACCEPTED: "已接收", COMPLETED: "已完结" };
const isAuth = (error: unknown): boolean => error instanceof ApiClientError && (error.status === 401 || error.status === 403);
const uncertain = (error: unknown): boolean => !(error instanceof ApiClientError) || error.status >= 500;

/** A dedicated cross-person directory for strict GLOBAL system administrators and owners. */
export function ManagedReferralCompletionPanel({ client, sessionKey, busy, active, onUnconfirmedChange, onInvalidated }: Props): ReactNode {
  const [items, setItems] = useState<readonly ManagedReferral[]>([]); const [pending, setPending] = useState<ReferralLifecycleSubmission | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState("");
  const mounted = useRef(true); const generation = useRef(0);
  const load = async (expected = generation.current): Promise<void> => { try { const next = await client.listManagedReferrals(); if (mounted.current && expected === generation.current) setItems(next); } catch (error) { if (!mounted.current || expected !== generation.current || error instanceof StaleResponseError) return; if (isAuth(error)) { setItems([]); onInvalidated(); return; } setMessage("管理员推荐目录暂未加载，请刷新重试。"); } };
  useEffect(() => { mounted.current = true; generation.current += 1; const expected = generation.current; setItems([]); setMessage(""); if (active) void load(expected); return () => { mounted.current = false; generation.current += 1; }; }, [client, sessionKey, active]);
  useEffect(() => { onUnconfirmedChange(pending !== null); return () => onUnconfirmedChange(false); }, [pending, onUnconfirmedChange]);
  const execute = async (submission: ReferralLifecycleSubmission): Promise<void> => { const expected = generation.current; setLoading(true); setMessage(""); try { await client.changeReferralLifecycle(submission); if (!mounted.current || expected !== generation.current) return; setPending(null); setMessage("学生课程已完结，后续不能新增周费用。"); await load(expected); } catch (error) { if (!mounted.current || expected !== generation.current || error instanceof StaleResponseError) return; if (isAuth(error)) { setItems([]); setPending(null); onInvalidated(); return; } if (error instanceof ApiClientError && error.status === 409) { setPending(null); setMessage("该推荐已有新状态，旧命令已清空。请刷新后核对。"); await load(expected); return; } if (uncertain(error)) { setPending(submission); setMessage("完结结果尚未确认。请安全重试原操作。"); return; } setPending(null); setMessage("完结未完成，请刷新后核对。"); } finally { if (mounted.current && expected === generation.current) setLoading(false); } };
  const complete = (item: ManagedReferral): void => { if (loading || pending !== null) return; try { void execute(client.createReferralLifecycleSubmission({ referralId: item.referralId, expectedVersion: item.version, command: "COMPLETE" })); } catch { setMessage("当前管理员身份不能完结推荐，请重新选择身份。"); } };
  const locked = busy || loading || pending !== null;
  return <section className="panel" hidden={!active} aria-label="管理员推荐完结"><div className="section-title"><div><span className="fee-eyebrow">REFERRAL ADMINISTRATION</span><h2>管理员推荐完结</h2></div><button type="button" disabled={locked} onClick={() => void load()}>刷新</button></div><p>查看全局推荐，完结后停止新增周费用；已有费用仍可查看和更正。</p>{message && <p className="message" role={pending ? "alert" : "status"}>{message}</p>}{pending && <button type="button" disabled={busy || loading} onClick={() => void execute(pending)}>安全重试原完结操作</button>}{!items.length && !loading && <p>暂无推荐记录。</p>}{items.map((item) => <article key={item.referralId} data-managed-referral-id={item.referralId}><div><h3>{item.studentDisplayName}</h3><p>接收老师：{item.receiverNickname} · 推荐人：{item.referrerNickname}</p><p>{item.courseContextId} · {labels[item.referralStatus]}</p></div>{item.referralStatus === "ACCEPTED" ? <button type="button" disabled={locked} onClick={() => complete(item)}>完结课程</button> : item.referralStatus === "COMPLETED" ? <span>完结撒花</span> : null}</article>)}</section>;
}
