import { useEffect, useRef, useState, type ReactNode } from "react";
import { ApiClientError, formatCentsAsBeans, type FinanceDocumentAttachment, type FinanceDraftMetadata, type FinanceDraftSubmission, type RefundCommandResult, type RefundDetail, type RefundReviewSubmission, type RefundSubmission, type RefundSummary } from "@teaching-research-alliance/client";
import { Button } from "./components/ui/button.js";
import { Card } from "./components/ui/card.js";
import { AttachmentDownload, AttachmentPicker, financeError, isFinanceAuthError, type FinancePanelProps } from "./finance-shared.js";

export type RefundFeeCandidate = Readonly<{ weeklyFeeEntryId: string; referralCaseId: string; studentRecordId: string; studentDisplayName: string; courseContextId: string; teachingWeekId: string; settlementMonth: string; grossAmountCents: string; refundStatus: "ACTIVE" | "REFUNDED" }>;
type Props = Omit<FinancePanelProps, "onDataMayChange"> & { mode: "personal" | "managed"; feeCandidates: readonly RefundFeeCandidate[] };
type Command = Readonly<{ kind: "submit"; submission: RefundSubmission } | { kind: "review"; submission: RefundReviewSubmission }>;
const purposes = [{ purpose: "SUPPORTING_DOCUMENT", label: "退款业务单据" }, { purpose: "APPLICATION_SCREENSHOT", label: "退款申请截图" }] as const;
type Purpose = (typeof purposes)[number]["purpose"];
const uncertain = (error: unknown): boolean => !(error instanceof ApiClientError) || error.status >= 500;
const label = (status: RefundSummary["status"]): string => ({ PENDING_APPROVAL: "待审核", REFUNDED: "已退款", REJECTED: "已驳回" })[status];

/** Refund approval posts the system split reversal. Cash return remains an offline operation. */
export function RefundPanel({ client, busy, active, run, onUnconfirmedChange, mode, feeCandidates }: Props): ReactNode {
  const personal = mode === "personal"; const started = useRef(false); const pendingUploads = useRef(new Set<Purpose>());
  const [uploadCount, setUploadCount] = useState(0); const [drafts, setDrafts] = useState<readonly FinanceDraftMetadata[]>([]); const [records, setRecords] = useState<readonly RefundSummary[]>([]); const [loaded, setLoaded] = useState(false); const [fresh, setFresh] = useState(false);
  const [draft, setDraft] = useState<FinanceDraftMetadata | null>(null); const [attachments, setAttachments] = useState<readonly FinanceDocumentAttachment[]>([]); const [chosen, setChosen] = useState<Partial<Record<Purpose, string>>>({}); const [selectedFees, setSelectedFees] = useState<readonly string[]>([]); const [reason, setReason] = useState("");
  const [pendingCreate, setPendingCreate] = useState<FinanceDraftSubmission | null>(null); const [pendingCommand, setPendingCommand] = useState<Command | null>(null); const [detail, setDetail] = useState<RefundDetail | null>(null); const [reviewReason, setReviewReason] = useState(""); const [notice, setNotice] = useState(""); const [receipt, setReceipt] = useState("");
  const pending = pendingCreate !== null || pendingCommand !== null || uploadCount > 0; const locked = busy || pendingCreate !== null || pendingCommand !== null;
  const role = client.currentSession?.currentRoleContext; const canReadManaged = !personal && ["HEADQUARTERS_FINANCE", "SYSTEM_ADMIN", "SYSTEM_OWNER"].includes(role?.subject ?? "") && role?.scope === "GLOBAL" && role.regionId === undefined && role.campusId === undefined && role.venueId === undefined;
  const canReview = canReadManaged && role?.subject === "HEADQUARTERS_FINANCE";
  // The released client only permits submission by TEACHING_TEACHER. Other personal roles may safely inspect their own records/drafts.
  const canSubmit = personal && role?.subject === "TEACHING_TEACHER";
  const candidates = feeCandidates.filter((fee) => fee.refundStatus === "ACTIVE");
  useEffect(() => { onUnconfirmedChange(pending); }, [pending, onUnconfirmedChange]);
  const load = async (): Promise<void> => { setFresh(false); const nextRecords = personal ? await client.listOwnRefunds() : await client.listManagedRefunds(); const nextDrafts = personal ? await client.listOwnFinanceDrafts() : []; setRecords(nextRecords.documents); setDrafts(nextDrafts.filter((item) => item.kind === "REFUND")); setLoaded(true); setFresh(true); };
  const resetForm = (): void => { setAttachments([]); setChosen({}); setSelectedFees([]); setReason(""); pendingUploads.current.clear(); setUploadCount(0); };
  const refresh = async (): Promise<void> => { if (pending) return; setDetail(null); setReviewReason(""); try { await load(); } catch (error) { setNotice(`退款记录刷新失败：${financeError(error)}`); if (isFinanceAuthError(error)) throw error; } };
  useEffect(() => { if (!active || busy || started.current || (!personal && !canReadManaged)) return; started.current = true; void run(refresh); }, [active, busy, canReadManaged]);
  const openDraft = async (id: string): Promise<void> => { if (!personal || pending) return; setDraft(null); resetForm(); try { const metadata = await client.getOwnFinanceDraft(id); const recovered = await client.listFinanceDocumentAttachments(id); if (metadata.kind !== "REFUND" || metadata.status !== "DRAFT") { setNotice("这笔记录已不能继续作为退款草稿，请刷新后核对。"); return; } setDraft(metadata); setAttachments(recovered.attachments); } catch (error) { setNotice(`退款草稿未能打开：${financeError(error)}`); if (isFinanceAuthError(error)) throw error; } };
  const createDraft = async (): Promise<void> => { if (!canSubmit || pendingCommand !== null || uploadCount > 0) return; const submission = pendingCreate ?? client.createFinanceDraftSubmission({ kind: "REFUND" }); setPendingCreate(submission); try { const result = await client.createFinanceDraft(submission); setPendingCreate(null); resetForm(); setDraft(result); setDrafts((items) => [result, ...items.filter((item) => item.id !== result.id)]); setReceipt("退款草稿已创建。请选择原周费用、填写原因并上传两份原件。"); } catch (error) { if (!uncertain(error)) setPendingCreate(null); setNotice(uncertain(error) ? "尚不能确认退款草稿是否创建，请安全重试原创建请求。" : financeError(error)); if (isFinanceAuthError(error)) throw error; } };
  const execute = async (command: Command): Promise<void> => { setPendingCommand(command); setNotice(""); let result: RefundCommandResult; try { result = command.kind === "submit" ? await client.submitRefund(command.submission) : await client.reviewRefund(command.submission); const expected = command.kind === "submit" ? "PENDING_APPROVAL" : command.submission.draft.decision === "APPROVE" ? "REFUNDED" : "REJECTED"; if (result.status !== expected) throw new Error("REFUND_RESULT_UNCONFIRMED"); } catch (error) { if (uncertain(error)) { setNotice(command.kind === "submit" ? "尚不能确认退款申请结果，费用、原因与原件已锁定。请安全重试原退款申请。" : `尚不能确认审核结果。本次审核决定：${command.submission.draft.decision === "APPROVE" ? "批准" : "驳回"}；审核原因已锁定。请安全重试原审核操作。`); return; } setPendingCommand(null); if (error instanceof ApiClientError && error.status === 409) { if (command.kind === "submit") { setDraft(null); resetForm(); } else { setDetail(null); setReviewReason(""); } try { await load(); } catch (reload) { if (isFinanceAuthError(reload)) throw reload; } setNotice("单据或周费用状态已变化，旧输入已清空。请重新读取后核对，原请求不会自动重发。"); return; } throw error; } setPendingCommand(null); if (command.kind === "submit") { setDraft(null); resetForm(); setReceipt("退款申请已提交，等待总部财务审核；待审期间不冲回系统分润。"); } else { setReviewReason(""); setReceipt(result.status === "REFUNDED" ? "退款审核已通过：系统分润已冲回，原周费用已标记为已退款；现金退款请线下办理。" : "退款已驳回，未冲回系统分润，原周费用保持有效。"); } setDetail(null); try { await load(); if (command.kind === "review") setDetail(await client.getRefundDetail(result.id)); } catch (error) { setNotice("本次退款结果已确认，但刷新失败。请刷新后核对，勿重复操作。"); if (isFinanceAuthError(error)) throw error; } };
  const submit = async (): Promise<void> => { if (!canSubmit || draft === null || pendingCreate !== null) return; if (pendingCommand?.kind === "submit") { await execute(pendingCommand); return; } if (!fresh || uploadCount > 0) { setNotice("请先刷新并确认原件上传结果。"); return; } const support = chosen.SUPPORTING_DOCUMENT; const screenshot = chosen.APPLICATION_SCREENSHOT; const selected = selectedFees.filter((id) => candidates.some((fee) => fee.weeklyFeeEntryId === id)); if (!reason.trim() || reason.length > 1000 || /[\x00-\x1f\x7f]/.test(reason)) { setNotice("请填写退款原因，最多1000字，勿包含换行或控制字符。"); return; } if (selected.length === 0) { setNotice("请选择至少一笔仍有效的原周费用。"); return; } if (!support || !screenshot) { setNotice("请上传并选用已就绪的退款业务单据与申请截图。"); return; } await execute({ kind: "submit", submission: client.createRefundSubmission({ documentId: draft.id, expectedVersion: draft.version, reason: reason.trim(), weeklyFeeEntryIds: selected, attachmentVersionIds: [support, screenshot] }) }); };
  const review = async (decision: "APPROVE" | "REJECT"): Promise<void> => { if (!canReview || detail?.status !== "PENDING_APPROVAL" || pending) return; const retry = pendingCommand as Command | null; if (retry?.kind === "review") { await execute(retry); return; } const value = reviewReason.trim(); if (!value || value.length > 1000 || /[\x00-\x1f\x7f]/.test(value)) { setNotice("请填写审核原因，最多1000字，勿包含换行或控制字符。"); return; } await execute({ kind: "review", submission: client.createRefundReviewSubmission({ documentId: detail.id, expectedVersion: detail.version, decision, reason: value }) }); };
  const readDetail = async (id: string): Promise<void> => { if (pending) return; setDetail(null); setReviewReason(""); try { setDetail(await client.getRefundDetail(id)); } catch (error) { setNotice(`退款详情未能读取：${financeError(error)}`); if (isFinanceAuthError(error)) throw error; } };
  if (!personal && !canReadManaged) return null;
  return <section className="finance-panel" data-finance-module="refund" data-mode={mode} hidden={!active} aria-label={personal ? "我的退款" : "退款管理记录"}><div className="section-heading"><div><p className="eyebrow">{personal ? "我的账户" : "财务查询"}</p><h2>{personal ? "学生退款申请" : "学生退款管理"}</h2><p>退款申请与审核不提供银行或付款操作。审核通过后系统冲回分润，现金退款由线下办理。</p></div><Button variant="outline" disabled={locked} onClick={() => void run(refresh)}>刷新退款记录</Button></div>{receipt && <p className="finance-success" role="status">{receipt}</p>}{notice && <p className="finance-notice" role="alert">{notice}</p>}
    {pendingCreate && <Card className="finance-warning" data-refund-pending="create"><p>草稿创建结果待确认，原请求已保留。</p><Button disabled={busy} onClick={() => void run(createDraft)}>安全重试原创建请求</Button></Card>}{pendingCommand && <Card className="finance-warning" data-refund-pending={pendingCommand.kind}><p>{pendingCommand.kind === "submit" ? "退款申请结果待确认，费用、原因与原件已锁定。" : `审核结果待确认。本次审核决定：${pendingCommand.submission.draft.decision === "APPROVE" ? "批准" : "驳回"}；审核原因已锁定。`}</p><Button disabled={busy} onClick={() => void run(() => execute(pendingCommand))}>{pendingCommand.kind === "submit" ? "安全重试原退款申请" : "安全重试原审核操作"}</Button></Card>}
    {personal && <Card className="finance-card" data-refund-action="personal-application"><div className="section-heading"><div><h3>退款草稿</h3><p>{canSubmit ? "草稿不改变原周费用或任何分润。" : "当前身份可查看本人退款记录；退款提交须使用授课老师身份。"}</p></div><Button disabled={locked || !canSubmit} onClick={() => void run(createDraft)}>新建退款申请</Button></div>{drafts.map((item) => <div className="finance-list-row" key={item.id}><span>退款草稿 · {item.id}</span><Button variant="outline" disabled={locked || draft?.id === item.id} onClick={() => void run(() => openDraft(item.id))}>{draft?.id === item.id ? "正在填写" : "继续填写退款"}</Button></div>)}
      {draft && <div className="finance-card"><h3>填写学生退款申请</h3><label>退款原因<input value={reason} maxLength={1000} disabled={locked || !canSubmit} onChange={(event) => setReason(event.target.value)} /></label><p className="finance-muted">仅可选仍有效的原周费用；选中的费用编号会随本次申请冻结。</p><div className="finance-list">{candidates.map((fee) => <label className="finance-list-row" key={fee.weeklyFeeEntryId}><span><input type="checkbox" checked={selectedFees.includes(fee.weeklyFeeEntryId)} disabled={locked || !canSubmit} onChange={(event) => setSelectedFees((items) => event.target.checked ? [...items, fee.weeklyFeeEntryId] : items.filter((id) => id !== fee.weeklyFeeEntryId))} />{fee.studentDisplayName} · {fee.courseContextId} · {fee.teachingWeekId} · {formatCentsAsBeans(fee.grossAmountCents)} 豆</span></label>)}</div>{feeCandidates.some((fee) => fee.refundStatus === "REFUNDED") && <p className="finance-muted">已退款周费用不可再次选择。</p>}
        <div className="finance-attachments">{purposes.map(({ purpose, label: attachmentLabel }) => <div className="finance-attachment-slot" key={purpose}><AttachmentPicker client={client} documentId={draft.id} purpose={purpose} label={attachmentLabel} disabled={locked || !canSubmit} run={run} onReady={(versionId) => setChosen((items) => ({ ...items, [purpose]: versionId }))} onPendingChange={(value) => { if (value) pendingUploads.current.add(purpose); else pendingUploads.current.delete(purpose); setUploadCount(pendingUploads.current.size); }} />{attachments.filter((item) => item.purpose === purpose).flatMap((item) => item.versions.filter((version) => version.status === "READY").map((version) => <label key={version.versionId}><input type="radio" name={purpose} checked={chosen[purpose] === version.versionId} disabled={locked} onChange={() => setChosen((items) => ({ ...items, [purpose]: version.versionId }))} />选用 {version.originalFilename} · 第{version.versionNo}版</label>))}</div>)}</div><Button disabled={locked || !canSubmit} onClick={() => void run(submit)}>{pendingCommand?.kind === "submit" ? "安全重试原退款申请" : "确认提交退款申请"}</Button></div>}
    </Card>}
    {loaded && records.length === 0 && <p className="finance-empty">暂无退款申请记录。</p>}{records.map((item) => <div className="finance-list-row" key={item.id}><span>{item.studentDisplayName} · {label(item.status)} · {item.selectedFeeCount} 笔原周费用</span><Button variant="outline" disabled={locked} onClick={() => void run(() => readDetail(item.id))}>查看退款详情</Button></div>)}
    {detail && <Card className="finance-card"><h3>退款详情</h3><p>{label(detail.status)} · {detail.studentDisplayName} · {detail.selectedFeeCount} 笔原周费用</p><p>退款原因：{detail.reason}</p><p>{detail.status === "PENDING_APPROVAL" ? "待审核期间不冲回系统分润。" : detail.status === "REFUNDED" ? "系统分润已冲回，原周费用已标记为已退款；现金退款线下办理。" : "退款已驳回，未冲回系统分润。"}</p>{detail.selectedFees.map((fee) => <p key={fee.weeklyFeeEntryId}>{fee.teachingWeekId} · {formatCentsAsBeans(fee.submittedGrossAmountCents)} 豆 · {fee.refundStatus === "REFUNDED" ? "已退款" : "有效"}</p>)}{detail.attachments.map((item) => <AttachmentDownload key={item.versionId} client={client} versionId={item.versionId} filename={item.originalFilename} disabled={busy} run={run} />)}{canReview && detail.status === "PENDING_APPROVAL" && <div data-refund-action="review"><h4>人工审核</h4><textarea value={reviewReason} maxLength={1000} disabled={locked} onChange={(event) => setReviewReason(event.target.value)} placeholder="填写审核依据或驳回原因" /><Button disabled={locked || !reviewReason.trim()} onClick={() => void run(() => review("APPROVE"))}>批准退款申请</Button><Button variant="destructive" disabled={locked || !reviewReason.trim()} onClick={() => void run(() => review("REJECT"))}>驳回退款申请</Button></div>}</Card>}
  </section>;
}
