import { test, expect } from '@playwright/test';

test('福利计划真实保存及响应丢失重试，保存不生成执行记录', async ({ page }) => {
  test.skip(process.env.ALLIANCE_SYNTHETIC_E2E !== '1', 'Requires isolated synthetic demo');
  await page.clock.setFixedTime(new Date('2026-09-23T04:00:00Z'));
  let token = '';
  page.on('response', async response => {
    if (response.url().endsWith('/v1/session') && response.ok()) token = (await response.json()).data.sessionId;
  });
  await page.goto('/');
  await page.getByLabel('手机号', { exact: true }).fill('13800000003');
  await page.getByLabel('密码', { exact: true }).fill('Local-demo-only-2026');
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('button', { name: '刷新', exact: true })).toBeEnabled();
  await page.getByLabel('当前身份', { exact: true }).selectOption('HEADQUARTERS_FINANCE');
  await page.getByRole('button', { name: '医社保与公积金', exact: true }).click();
  const panel = page.getByRole('region', { name: '福利计划维护', exact: true });
  await panel.getByLabel('福利类型', { exact: true }).selectOption('HOUSING_FUND');
  await panel.getByLabel('受益人', { exact: true }).selectOption({ label: '演示授课老师' });
  await panel.getByLabel('福利月份', { exact: true }).fill('2026-10');
  await panel.getByLabel('福利类型', { exact: true }).selectOption('HOUSING_FUND');
  await panel.getByLabel('受益人', { exact: true }).selectOption({ label: '演示授课老师' });
  await panel.getByLabel('执行日', { exact: true }).fill('12');
  await panel.getByLabel('金额（欢乐豆）', { exact: true }).fill('90');
  const funds = panel.getByLabel('扣费账户', { exact: true });
  const value = await funds.locator('option').nth(1).getAttribute('value');
  await funds.selectOption(value);
  await panel.getByLabel('理由', { exact: true }).fill('合成公积金计划保存验证');
  const commands = [], results = [];
  await page.route('**/v1/finance/benefit-plans', async route => {
    commands.push(route.request().postDataJSON());
    const response = await route.fetch();
    expect(response.status()).toBe(200);
    results.push((await response.json()).data);
    if (commands.length === 1) await route.abort('failed');
    else await route.fulfill({ response });
  });
  await panel.getByRole('button', { name: '保存计划', exact: true }).click();
  const retry = panel.getByRole('button', { name: '使用原提交重试', exact: true });
  await expect(retry).toBeEnabled();
  await expect(page.getByLabel('当前身份', { exact: true })).toBeDisabled();
  await expect(panel.getByLabel('金额（欢乐豆）', { exact: true })).toBeDisabled();
  await retry.click();
  await expect(panel.getByText(/福利计划已保存/)).toBeVisible();
  expect(commands).toHaveLength(2);
  expect(commands[1]).toEqual(commands[0]);
  expect(results[1].id).toBe(results[0].id);
  const response = await page.request.get('/v1/finance/benefit-roster?month=2026-10-01', { headers: { authorization: `Bearer ${token}` } });
  expect(response.status()).toBe(200);
  const entry = (await response.json()).data.items.find(item => item.benefitKind === 'HOUSING_FUND' && item.beneficiaryPersonId === commands[0].beneficiaryPersonId);
  expect(entry).toBeTruthy();
  expect(entry.currentPlan.amountCents).toBe('9000');
  expect(entry.currentPlan.executionDay).toBe(12);
  expect(entry.todo).toBeNull();
  expect(entry.execution).toBeNull();
  expect(entry.status).toBe('SCHEDULED');
  await page.getByLabel('当前身份', { exact: true }).selectOption('TEACHING_TEACHER');
  await expect(panel).toHaveCount(0);
});
