import {test,expect} from '@playwright/test';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEUlEQVR4AWP8DwQMQMDEAAUAPfgEADYYS7QAAAAASUVORK5CYII=','base64');
test('工资线下确认使用真实双用途附件，丢失响应重试仅扣一次豆',async({page})=>{
 test.skip(process.env.ALLIANCE_SYNTHETIC_E2E!=='1','Requires isolated synthetic demo');
 await page.clock.setFixedTime(new Date('2026-09-23T04:00:00Z'));
 const login=await page.request.post('/v1/session',{data:{phoneNormalized:'13800000001',password:'Local-demo-only-2026'}});expect(login.status()).toBe(200);const teacher=(await login.json()).data;const headers={authorization:`Bearer ${teacher.sessionId}`};
 const before=(await (await page.request.get('/v1/me',{headers})).json()).data;
 let financeSession='';page.on('response',async response=>{if(response.url().endsWith('/v1/session')&&response.ok())financeSession=(await response.json()).data.sessionId;});
 await page.goto('/');await page.getByLabel('手机号',{exact:true}).fill('13800000003');await page.getByLabel('密码',{exact:true}).fill('Local-demo-only-2026');await page.getByRole('button',{name:'登录',exact:true}).click();await expect(page.getByRole('button',{name:'刷新',exact:true})).toBeEnabled();await page.getByLabel('当前身份',{exact:true}).selectOption('HEADQUARTERS_FINANCE');
 const rosterResponse=await page.request.get('/v1/finance/cash-wage-roster?month=2026-09-01',{headers:{authorization:`Bearer ${financeSession}`}});expect(rosterResponse.status()).toBe(200);const existing=(await rosterResponse.json()).data.items.find(item=>item.teacherDisplayName==='演示授课老师');const targetCents=BigInt(existing.confirmedCashCents)+400n;const targetYuan=`${targetCents/100n}.${(targetCents%100n).toString().padStart(2,'0')}`;
 await page.getByRole('button',{name:'工资管理',exact:true}).click();const plan=page.getByRole('region',{name:'工资计划维护',exact:true});await plan.getByRole('combobox',{name:'老师',exact:true}).selectOption({label:'演示授课老师'});await plan.getByLabel('现金计划（元）',{exact:true}).fill(targetYuan);await plan.getByLabel('扣豆计划（欢乐豆）',{exact:true}).fill(targetYuan);await plan.getByLabel('理由',{exact:true}).fill('合成浏览器验证补发4元');await plan.getByRole('button',{name:'保存工资计划',exact:true}).click();await expect(plan.getByText(/工资计划已保存/)).toBeVisible();
 await page.getByRole('button',{name:'工资发放确认',exact:true}).click();const panel=page.getByRole('region',{name:'现金工资确认',exact:true});const teachers=panel.getByLabel('确认工资老师',{exact:true});await expect(teachers).toBeEnabled();const options=await teachers.locator('option').allTextContents();const label=options.find(v=>v.startsWith('演示授课老师'));await teachers.selectOption({label});
 await panel.getByLabel('实际现金（元）',{exact:true}).fill('4');await panel.getByLabel('扣豆（欢乐豆）',{exact:true}).fill('4');await panel.getByLabel('理由',{exact:true}).fill('合成现金已线下发放事实');await panel.getByLabel('我确认现金已在线下发放',{exact:true}).check();await panel.getByRole('button',{name:'创建工资确认凭证',exact:true}).click();
 let lostUpload=false;await page.route('**/v1/finance/attachment-uploads/*/content',async route=>{const response=await route.fetch();expect(response.status()).toBe(200);if(!lostUpload){lostUpload=true;await route.abort('failed');}else await route.fulfill({response});});
 for(const label of ['工资发放凭证','工资确认截图']){
   await panel.getByLabel(label,{exact:true}).setInputFiles({name:`${label}.png`,mimeType:'image/png',buffer:png});await panel.getByRole('button',{name:`上传${label}`,exact:true}).click();if(label==='工资发放凭证'){const uploadRetry=panel.getByRole('button',{name:`安全重试上传${label}`,exact:true});await expect(uploadRetry).toBeEnabled();await expect(panel.getByLabel('工资确认截图',{exact:true})).toBeDisabled();await uploadRetry.click();}await expect(panel.getByText(`${label}.png 已完整上传。`,{exact:true})).toBeVisible();
 }
 const requests=[],results=[];await page.route('**/v1/finance/cash-wages/confirm',async route=>{requests.push(route.request().postDataJSON());const response=await route.fetch();expect(response.status()).toBe(200);results.push((await response.json()).data);if(requests.length===1)await route.abort('failed');else await route.fulfill({response});});
 await panel.getByRole('button',{name:'确认现金已发放并记录扣豆',exact:true}).click();const retry=panel.getByRole('button',{name:'安全重试原确认',exact:true});await expect(retry).toBeEnabled();await expect(teachers).toBeDisabled();await expect(page.getByRole('button',{name:'工资管理',exact:true})).toBeDisabled();await expect(panel).toBeVisible();await retry.click();
 await expect(teachers).toBeEnabled();await expect(teachers).toHaveValue('');await expect(teachers.locator('option').filter({hasText:`演示授课老师 · 计划 ${targetYuan} 元 · 已确认 ${targetYuan} 元 · 剩余 0.00 元`})).toHaveCount(1);
 expect(requests).toHaveLength(2);expect(requests[1]).toEqual(requests[0]);expect(results[1]).toEqual({...results[0],replay:true});expect(results[0].replay).toBe(false);
 const after=(await (await page.request.get('/v1/me',{headers})).json()).data;expect(BigInt(after.balanceCents)-BigInt(before.balanceCents)).toBe(-400n);expect(after.currentYearIncomeByCategory).toEqual(before.currentYearIncomeByCategory);
});
