import { useEffect, useRef, useState, type ReactNode } from "react";
import { Button, Picker, Text, Textarea, View } from "@tarojs/components";
import { ApiClientError, RoleSelectionRequiredError, formatCentsAsBeans, type PlanningMentorRelationshipChangeSubmission, type SessionSnapshot, type TeacherApiClient } from "@teaching-research-alliance/client";

type Props = Readonly<{ client: TeacherApiClient; session: SessionSnapshot; sessionKey: string; busy?: boolean; onInvalidated?: () => void; onSaved?: () => void; onUnconfirmedChange?: (pending: boolean) => void }>;
type Directory = Awaited<ReturnType<TeacherApiClient["listPlanningMentorRelationships"]>>;
type Preview = Awaited<ReturnType<TeacherApiClient["previewPlanningMentorRelationshipChange"]>>;
type Phase = "idle" | "previewing" | "publishing" | "unknown" | "stale";
const allowed = (s: SessionSnapshot): boolean => { const c=s.currentRoleContext; return c?.subject==="PLANNING_MENTOR"&&c.scope==="SELF"&&c.regionId===undefined&&c.campusId===undefined&&c.venueId===undefined; };
const identity = (s:SessionSnapshot,k:string):string=>{const c=s.currentRoleContext;return [k,c?.personId??"",c?.subject??"",c?.scope??"",c?.regionId??"",c?.campusId??"",c?.venueId??""].join("|");};
const auth = (e:unknown):boolean=>e instanceof RoleSelectionRequiredError||e instanceof ApiClientError&&[401,403].includes(e.status)||typeof e==="object"&&e!==null&&[401,403].includes((e as {status?:number}).status??0);
const explain=(e:unknown,f:string):string=>{if(!(e instanceof ApiClientError))return f;if(["RELATIONSHIP_PREVIEW_STALE","RELATIONSHIP_PREVIEW_ALREADY_PUBLISHED"].includes(e.code))return "预览已过期，请重新生成并核对。";if(["PLANNING_MENTOR_RELATIONSHIP_CONFLICT","PLANNING_MENTOR_RELATIONSHIP_NOT_OWNED"].includes(e.code))return "规划师关系已变化，请刷新后重试。";if(["RELATIONSHIP_DATA_UNAVAILABLE","RELATIONSHIP_SERVICE_UNAVAILABLE"].includes(e.code))return "关系数据暂不能核验，请稍后重试。";return f;};
const bjt=(v:string):string=>new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",dateStyle:"medium",timeStyle:"short"}).format(new Date(v));

export function PlanningMentorRelationshipPanel({client,session,sessionKey,busy=false,onInvalidated,onSaved,onUnconfirmedChange}:Props):ReactNode {
  const [directory,setDirectory]=useState<Directory|null>(null);const [action,setAction]=useState<"ADD"|"REMOVE">("ADD");const [planner,setPlanner]=useState("");const [week,setWeek]=useState("");const [reason,setReason]=useState("");const [preview,setPreview]=useState<Preview|null>(null);const [submission,setSubmission]=useState<PlanningMentorRelationshipChangeSubmission|null>(null);const [phase,setPhase]=useState<Phase>("idle");const [notice,setNotice]=useState("");
  const generation=useRef(0),writing=useRef(false),prior=useRef("");const canManage=allowed(session),identityKey=identity(session,sessionKey);
  const reset=():void=>{writing.current=false;setDirectory(null);setAction("ADD");setPlanner("");setWeek("");setReason("");setPreview(null);setSubmission(null);setPhase("idle");};
  const invalidate=():void=>{generation.current+=1;reset();setNotice("登录或身份已失效，请重新登录或选择身份。");onUnconfirmedChange?.(false);onInvalidated?.();};
  const load=(success=""):void=>{const token=++generation.current;writing.current=false;setDirectory(null);setPreview(null);setSubmission(null);setPhase("idle");setNotice(success);if(!canManage)return;void client.listPlanningMentorRelationships().then(next=>{if(generation.current===token){setDirectory(next);if(success)setNotice(success);}}).catch((e:unknown)=>{if(generation.current!==token)return;if(auth(e)||client.hasRoleContext===false)invalidate();else setNotice(explain(e,"无法读取本人规划师关系和当前普通周。"));});};
  useEffect(()=>{const changed=prior.current!==identityKey;prior.current=identityKey;if(changed)reset();load();return()=>{generation.current+=1;writing.current=false;};},[client,identityKey,canManage]);
  useEffect(()=>{onUnconfirmedChange?.(phase==="publishing"||phase==="unknown");return()=>onUnconfirmedChange?.(false);},[phase,onUnconfirmedChange]);
  const clearPreview=():void=>{setPreview(null);setSubmission(null);setPhase("idle");};
  const requestPreview=async():Promise<void>=>{if(busy||writing.current||!canManage||directory===null)return;if(!planner||!week||!reason.trim()){setNotice("请选择操作、规划师和当前普通周，并填写变更原因。");return;}const token=generation.current;setPhase("previewing");setPreview(null);setSubmission(null);setNotice("");try{const result=await client.previewPlanningMentorRelationshipChange({action,plannerPersonId:planner,effectiveTeachingWeekId:week,reason:reason.trim()});if(generation.current!==token)return;setPreview(result);setPhase("idle");setNotice("预览已生成，请核对后明确发布。");}catch(e){if(generation.current!==token)return;setPhase("idle");if(auth(e)||client.hasRoleContext===false){invalidate();return;}setNotice(explain(e,"无法生成预览，请核对规划师和当前普通周。"));}};
  const publish=async():Promise<void>=>{if(busy||writing.current||!canManage||preview===null)return;let command=submission;if(command===null){try{command=client.createPlanningMentorRelationshipChangeSubmission(preview.previewId);}catch(e){setNotice(explain(e,"无法准备发布请求。"));return;}setSubmission(command);}const token=generation.current;writing.current=true;setPhase("publishing");setNotice("");try{const result=await client.publishPlanningMentorRelationshipChange(command);if(generation.current!==token)return;writing.current=false;setSubmission(null);setPreview(null);setPhase("idle");onSaved?.();load(result.replay?"规划导师关系已确认，未重复发布。":"规划导师关系已发布：只影响本普通周及后续适用费用。");}catch(e){if(generation.current!==token)return;writing.current=false;if(auth(e)||client.hasRoleContext===false){invalidate();return;}if(e instanceof ApiClientError&&[404,409].includes(e.status)){setSubmission(null);setPreview(null);setPhase("stale");setNotice("预览已失效，未自动发布。请重新生成并人工核对。");return;}if(e instanceof ApiClientError&&e.status===400){setSubmission(null);setPhase("idle");setNotice(explain(e,"发布被拒绝，请修改后重新预览。"));return;}setPhase("unknown");setNotice("发布结果未确认。请使用原发布请求安全重试，避免重复变更。");}};
  if(!canManage)return <View className="panel planning-mentor-relationship-panel"><Text className="panel-title">我的规划师关系</Text><Text>请切换到学业规划导师本人身份后办理。</Text></View>;
  const locked=busy||["previewing","publishing","unknown"].includes(phase);const planners=action==="ADD"?directory?.availablePlanners??[]:directory?.managedPlanners??[];const plannerIndex=Math.max(planners.findIndex(x=>x.personId===planner)+1,0);const weekIndex=Math.max((directory?.currentWeeks??[]).findIndex(x=>x.id===week)+1,0);
  return <View className="panel planning-mentor-relationship-panel"><Text className="panel-title">我的规划师关系</Text><Text>仅增减自己名下规划师；当前普通周起调整介绍池拆分，更早周及已退款费用不变，寒暑假交管理员处理。</Text>
    {directory===null?<><Text>{notice||"正在读取本人关系与当前普通周…"}</Text>{notice&&<Button disabled={locked} onClick={()=>load()}>重试读取目录</Button>}</>:<>
      <Text>当前管理 {directory.managedPlanners.length} 名规划师</Text>
      <Text className="field-label">关系操作</Text><Picker disabled={locked} mode="selector" range={["新增本人管理关系","移除本人管理关系"]} value={action==="ADD"?0:1} onChange={e=>{setAction(Number(e.detail.value)===0?"ADD":"REMOVE");setPlanner("");clearPreview();}}><View className="picker-field">{action==="ADD"?"新增本人管理关系":"移除本人管理关系"}</View></Picker>
      <Text className="field-label">规划师</Text><Picker disabled={locked} mode="selector" range={["请选择规划师",...planners.map(x=>x.nickname)]} value={plannerIndex} onChange={e=>{const next=planners[Number(e.detail.value)-1];setPlanner(next?.personId??"");clearPreview();}}><View className="picker-field">{plannerIndex===0?"请选择规划师":planners[plannerIndex-1]?.nickname}</View></Picker>
      {planners.length===0&&<Text>{action==="ADD"?"当前没有可新增的规划师。":"当前没有可移除的本人规划师关系。"}</Text>}
      <Text className="field-label">当前普通周</Text><Picker disabled={locked} mode="selector" range={["请选择当前普通周",...directory.currentWeeks.map(x=>`${x.startsOn} 至 ${x.endsOn}`)]} value={weekIndex} onChange={e=>{const next=directory.currentWeeks[Number(e.detail.value)-1];setWeek(next?.id??"");clearPreview();}}><View className="picker-field">{weekIndex===0?"请选择当前普通周":`${directory.currentWeeks[weekIndex-1]?.startsOn} 至 ${directory.currentWeeks[weekIndex-1]?.endsOn}`}</View></Picker>
      <Text className="field-label">变更原因</Text><Textarea disabled={locked} value={reason} onInput={e=>{setReason(e.detail.value);clearPreview();}} />
      <Button disabled={locked||phase==="stale"} onClick={()=>void requestPreview()}>{phase==="previewing"?"正在生成预览…":"生成关系影响预览"}</Button>{phase==="stale"&&<Button disabled={busy} onClick={()=>{setPhase("idle");setNotice("请重新生成预览。");}}>重新生成预览</Button>}
      {preview!==null&&<View className="finance-card"><Text>{preview.action==="ADD"?"新增":"移除"}规划师：{preview.plannerNickname}</Text><Text>北京时间生效：{bjt(preview.effectiveAt)}；{preview.nextBoundaryAt===null?"适用于后续普通周。":`下一边界 ${bjt(preview.nextBoundaryAt)}。`}</Text><Text>核对 {preview.consideredFeeCount} 笔，变化 {preview.changedFeeCount} 笔，零导师份额 {preview.zeroShareFeeCount} 笔，退款排除 {preview.excludedRefundCount} 笔。</Text><Text>规划师差额 {formatCentsAsBeans(preview.plannerDeltaCents)}，导师差额 {formatCentsAsBeans(preview.mentorDeltaCents)} 欢乐豆；介绍池总额不增加。</Text><Button data-planning-mentor-action="publish" disabled={locked} onClick={()=>void publish()}>{phase==="publishing"?"正在发布…":submission!==null?"使用原发布请求重试":"确认发布关系变更"}</Button>{phase==="unknown"&&<Button data-planning-mentor-action="retry-publish" disabled={busy} onClick={()=>void publish()}>使用原发布请求重试</Button>}</View>}
    </>}{notice!==""&&<Text>{notice}</Text>}
  </View>;
}
