import type { RoleContext } from "@teaching-research-alliance/contracts";
import type { PostgresPool } from "./postgres-ledger-repository.js";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const TEACHERS = ["TEACHING_TEACHER", "ACADEMIC_PLANNER", "PLANNING_MENTOR"];
const assertTeacher = (context: RoleContext): void => { if (!TEACHERS.includes(context.subject)) throw new Error("FORBIDDEN_SCOPE"); };
export type VenueView = Readonly<{ id: string; ownerPersonId: string; ownerNickname: string; name: string; status: "ACTIVE" | "INACTIVE"; defaultForOwner: boolean; version: number; accountId?: string; balanceCents?: string; canView: boolean; canWithdraw: boolean; grants?: readonly VenueGrantView[] }>;
export type VenueGrantView = Readonly<{ id: string; granteePersonId: string; granteeNickname: string; canView: boolean; canWithdraw: boolean; validFrom: string; validTo: string | null; version: number }>;

const mapGrant = (row: any): VenueGrantView => { const v = Number(row.version); if (!UUID.test(row.id) || !UUID.test(row.grantee_person_id) || !Number.isSafeInteger(v) || v < 1 || !row.valid_from) throw new Error("VENUE_DATA_UNAVAILABLE"); return { id: row.id, granteePersonId: row.grantee_person_id, granteeNickname: row.grantee_nickname, canView: row.can_view, canWithdraw: row.can_withdraw, validFrom: row.valid_from, validTo: row.valid_to, version: v }; };
const mapVenue = (row: any, grants?: readonly VenueGrantView[]): VenueView => { const v = Number(row.version); if (!UUID.test(row.id) || !UUID.test(row.owner_person_id) || !UUID.test(row.account_id) || !Number.isSafeInteger(v) || v < 1 || !["ACTIVE", "INACTIVE"].includes(row.status) || !/^-?[0-9]+$/.test(row.balance_cents ?? "")) throw new Error("VENUE_DATA_UNAVAILABLE"); const result: VenueView = { id: row.id, ownerPersonId: row.owner_person_id, ownerNickname: row.owner_nickname, name: row.name, status: row.status, defaultForOwner: row.default_for_owner, version: v, canView: row.can_view, canWithdraw: row.can_withdraw, ...(grants === undefined ? {} : { grants }) }; if (row.can_withdraw) return { ...result, accountId: row.account_id, balanceCents: row.balance_cents }; return result; };

export class PostgresVenueReadService {
  public constructor(private readonly pool: PostgresPool) {}
  public async list(context: RoleContext, at: Date): Promise<readonly VenueView[]> { assertTeacher(context); if (!Number.isFinite(at.getTime())) throw new Error("INVALID_INPUT"); const client = await this.pool.connect(); try { const rows = await client.query(`SELECT venue.id::text AS id,venue.owner_person_id::text AS owner_person_id,owner.nickname AS owner_nickname,venue.name,venue.status,venue.default_for_owner,venue.version::text AS version,account.id::text AS account_id,COALESCE(balance.balance_cents,0)::text AS balance_cents,(venue.owner_person_id=$1::uuid) AS can_view,(venue.owner_person_id=$1::uuid) AS can_withdraw FROM venue JOIN person owner ON owner.id=venue.owner_person_id JOIN settlement_account account ON account.owner_type='VENUE' AND account.owner_id=venue.id LEFT JOIN account_balance_projection balance ON balance.account_id=account.id WHERE venue.owner_person_id=$1::uuid OR EXISTS (SELECT 1 FROM venue_permission_grant grant_row WHERE grant_row.venue_id=venue.id AND grant_row.grantee_person_id=$1::uuid AND grant_row.can_view AND grant_row.valid_from <= $2::timestamptz AND (grant_row.valid_to IS NULL OR $2::timestamptz < grant_row.valid_to)) ORDER BY venue.name,venue.id`, [context.personId, at.toISOString()]); return rows.rows.map(row => mapVenue(row)); } finally { await client.release(); } }
  public async listOwned(context: RoleContext, at: Date): Promise<readonly VenueView[]> { assertTeacher(context); if (!Number.isFinite(at.getTime())) throw new Error("INVALID_INPUT"); const client = await this.pool.connect(); try { const rows = await client.query(`SELECT venue.id::text AS id,venue.owner_person_id::text AS owner_person_id,owner.nickname AS owner_nickname,venue.name,venue.status,venue.default_for_owner,venue.version::text AS version,account.id::text AS account_id,COALESCE(balance.balance_cents,0)::text AS balance_cents,true AS can_view,true AS can_withdraw FROM venue JOIN person owner ON owner.id=venue.owner_person_id JOIN settlement_account account ON account.owner_type='VENUE' AND account.owner_id=venue.id LEFT JOIN account_balance_projection balance ON balance.account_id=account.id WHERE venue.owner_person_id=$1::uuid ORDER BY venue.name,venue.id`, [context.personId]); const result: VenueView[] = []; for (const row of rows.rows) { const grants = await client.query(`SELECT grant_row.id::text AS id,grant_row.grantee_person_id::text AS grantee_person_id,grantee.nickname AS grantee_nickname,grant_row.can_view,grant_row.can_withdraw,to_char(grant_row.valid_from AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS valid_from,to_char(grant_row.valid_to AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS valid_to,grant_row.version::text AS version FROM venue_permission_grant grant_row JOIN person grantee ON grantee.id=grant_row.grantee_person_id WHERE grant_row.venue_id=$1::uuid AND grant_row.valid_to IS NULL ORDER BY grantee.nickname,grantee.id`, [row.id]); result.push(mapVenue(row, grants.rows.map(mapGrant))); } return result; } finally { await client.release(); } }
  public async get(context: RoleContext, venueId: string, at: Date): Promise<VenueView> { assertTeacher(context); if (!UUID.test(venueId) || !Number.isFinite(at.getTime())) throw new Error("INVALID_INPUT"); const client = await this.pool.connect(); try { const rows = await client.query(`SELECT venue.id::text AS id,venue.owner_person_id::text AS owner_person_id,owner.nickname AS owner_nickname,venue.name,venue.status,venue.default_for_owner,venue.version::text AS version,account.id::text AS account_id,COALESCE(balance.balance_cents,0)::text AS balance_cents,(venue.owner_person_id=$1::uuid OR EXISTS (SELECT 1 FROM venue_permission_grant grant_row WHERE grant_row.venue_id=venue.id AND grant_row.grantee_person_id=$1::uuid AND grant_row.can_view AND grant_row.valid_from <= $3::timestamptz AND (grant_row.valid_to IS NULL OR $3::timestamptz < grant_row.valid_to))) AS can_view,(venue.owner_person_id=$1::uuid OR EXISTS (SELECT 1 FROM venue_permission_grant grant_row WHERE grant_row.venue_id=venue.id AND grant_row.grantee_person_id=$1::uuid AND grant_row.can_withdraw AND grant_row.valid_from <= $3::timestamptz AND (grant_row.valid_to IS NULL OR $3::timestamptz < grant_row.valid_to))) AS can_withdraw FROM venue JOIN person owner ON owner.id=venue.owner_person_id JOIN settlement_account account ON account.owner_type='VENUE' AND account.owner_id=venue.id LEFT JOIN account_balance_projection balance ON balance.account_id=account.id WHERE venue.id=$2::uuid AND (venue.owner_person_id=$1::uuid OR EXISTS (SELECT 1 FROM venue_permission_grant grant_row WHERE grant_row.venue_id=venue.id AND grant_row.grantee_person_id=$1::uuid AND grant_row.can_view AND grant_row.valid_from <= $3::timestamptz AND (grant_row.valid_to IS NULL OR $3::timestamptz < grant_row.valid_to)))`, [context.personId, venueId, at.toISOString()]); const row = rows.rows[0]; if (!row) throw new Error("VENUE_NOT_FOUND"); return mapVenue(row); } finally { await client.release(); } }
}
