import { createHash, randomUUID } from "node:crypto";
import type { RoleContext } from "@teaching-research-alliance/contracts";
import { allocationDelta, allocateSettlement, postLedgerEvent, type LedgerDelta } from "@teaching-research-alliance/domain";
import { createPostgresLedgerTransaction, type PostgresClient, type PostgresPool } from "./postgres-ledger-repository.js";
import { lockSettlementAllocationExclusive } from "./postgres-settlement-allocation-gate.js";
import { resolveSettlementContext } from "./postgres-settlement-context.js";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Json=Record<string,unknown>;
type Campus={id:string;campus_id:string;region_id:string;valid_from:string;valid_to:string|null;created_by:string;created_at:string};
type PersonAssignment={id:string;person_id:string;campus_id:string;region_id:string;valid_from:string;valid_to:string|null;created_by:string;created_at:string};
type Effect={source:PersonAssignment;from:string;to:string|null;resultId:string;continuationId:string|null};
type Fee={id:string;version:string;teaching_week_id:string;settlement_month:string;gross_amount_cents:string;refund_id:string|null;snapshot_id:string|null;snapshot_json:unknown|null;context_json:unknown|null;policy_version_id:string|null;net_monthly_cents:string|null;receiver_at_campus:boolean;referrer_at_campus:boolean};
type PreviewRow={id:string;base_hash:string;campus_id:string;source_region_id:string;target_region_id:string;source_assignment_id:string;effective_from:string;effective_to:string|null;reason:string};

export type CampusRegionAssignmentPreviewDraft=Readonly<{campusId:string;targetRegionId:string;effectiveFrom:string;effectiveTo?:string|null;reason:string}>;
export type CampusRegionAssignmentCandidateDirectory=Readonly<{campuses:readonly Readonly<{campusId:string;campusName:string;currentRegionId:string|null;currentRegionName:string|null}>[];regions:readonly Readonly<{regionId:string;regionName:string}>[]}>;
export type CampusRegionAssignmentPreview=Readonly<{previewId:string;campusId:string;sourceRegionId:string;targetRegionId:string;effectiveFrom:string;effectiveTo:string|null;affectedPersonCount:number;affectedAssignmentCount:number;consideredFeeCount:number;changedFeeCount:number;excludedRefundCount:number;organizationImpact:Readonly<{sourceRegionId:string;targetRegionId:string;recordedGrossRevenueCents:string;refundedGrossRevenueCents:string;effectiveGrossRevenueCents:string;campusManagementFeeCents:string}>;accountDeltas:readonly Readonly<{accountCode:string;categoryKey:string;amountCents:string}>[]}>;
export type CampusRegionAssignmentChange=Readonly<{changeId:string;previewId:string;campusVersion:number;resultCampusRegionAssignmentId:string;affectedPersonCount:number;affectedAssignmentCount:number;postingStatus:"POSTED"|"NO_BALANCE_CHANGE";consideredFeeCount:number;changedFeeCount:number;excludedRefundCount:number;replay:boolean}>;

const fail=(code:string):never=>{const mapped:Record<string,string>={CAMPUS_REGION_SOURCE_INVALID:"CAMPUS_REGION_ASSIGNMENT_SOURCE_INVALID",CAMPUS_REGION_NO_CHANGE:"CAMPUS_REGION_ASSIGNMENT_NO_CHANGE"};throw new Error(mapped[code]??code);};
const stringify=(v:unknown)=>JSON.stringify(v,(_k,x)=>typeof x==="bigint"?x.toString():x);
const hash=(v:unknown)=>createHash("sha256").update(stringify(v)).digest("hex");
const stableId=(previewId:string,key:string)=>{const hex=createHash("sha256").update(`${previewId}:${key}`).digest("hex");return `${hex.slice(0,8)}-${hex.slice(8,12)}-4${hex.slice(13,16)}-8${hex.slice(17,20)}-${hex.slice(20,32)}`;};
const uuid=(v:string)=>UUID.test(v)?v.toLowerCase():fail("INVALID_INPUT");
const date=(v:string)=>{const d=new Date(v);if(!Number.isFinite(d.getTime()))fail("INVALID_INPUT");return d.toISOString();};
const clean=(v:string,n:number)=>{const x=v.trim();return x&&x.length<=n&&!/[\x00-\x1f\x7f]/.test(x)?x:fail("INVALID_INPUT");};
const time=(v:string)=>Date.parse(v);
const contextOk=(c:RoleContext)=>{if(!(["SYSTEM_OWNER","SYSTEM_ADMIN"] as const).includes(c.subject as "SYSTEM_OWNER")||c.scope!=="GLOBAL"||!UUID.test(c.personId)||c.regionId!==undefined||c.campusId!==undefined||c.venueId!==undefined)fail("FORBIDDEN_SCOPE");};
const actor=async(client:PostgresClient,c:RoleContext,at:string)=>{const rows=(await client.query<{id:string}>("SELECT id::text FROM role_assignment WHERE person_id=$1::uuid AND subject_code=$2 AND scope_type='GLOBAL' AND scope_id IS NULL AND valid_from<=$3::timestamptz AND (valid_to IS NULL OR valid_to>$3::timestamptz) ORDER BY id LIMIT 2 FOR SHARE",[c.personId,c.subject,at])).rows;if(rows.length!==1)fail("FORBIDDEN_SCOPE");return rows[0]!.id;};
const campusFact=(x:Campus)=>({id:x.id,campusId:x.campus_id,regionId:x.region_id,validFrom:x.valid_from,validTo:x.valid_to,createdByPersonId:x.created_by,createdAt:x.created_at});
const personFact=(x:PersonAssignment)=>({id:x.id,personId:x.person_id,campusId:x.campus_id,regionId:x.region_id,validFrom:x.valid_from,validTo:x.valid_to,createdByPersonId:x.created_by,createdAt:x.created_at});
const aggregate=(items:readonly LedgerDelta[])=>[...items.reduce((m,x)=>{const k=`${x.accountKey}\u0000${x.categoryKey}`,old=m.get(k);m.set(k,{...x,amountCents:(old?.amountCents??0n)+x.amountCents});return m;},new Map<string,LedgerDelta>()).values()].filter(x=>x.amountCents!==0n);
const decode=(raw:unknown)=>{if(raw===null||typeof raw!=="object"||Array.isArray(raw))fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE");const x=raw as {lines?:unknown;accountByKey?:unknown};if(!Array.isArray(x.lines)||x.accountByKey===null||typeof x.accountByKey!=="object"||Array.isArray(x.accountByKey))fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE");return {lines:(x.lines as unknown[]).map((v:unknown)=>{const y=v as {key?:unknown;cents?:unknown},key=typeof y.key==="string"?y.key:fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE"),cents=typeof y.cents==="string"&&/^-?\d+$/.test(y.cents)?y.cents:fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE");return {key,cents:BigInt(cents)};}),accountByKey:x.accountByKey as Record<string,string>};};

type Built={source:Campus;from:string;to:string|null;targetRegionId:string;resultId:string;continuationId:string|null;effects:readonly Effect[];fees:readonly Fee[];impact:Json};
const loadSource=async(client:PostgresClient,campusId:string,from:string,to:string|null,lock:boolean)=>{const rows=(await client.query<Campus>(`SELECT id::text,campus_id::text,region_id::text,valid_from::text,valid_to::text,created_by::text,created_at::text FROM campus_region_assignment WHERE campus_id=$1::uuid AND valid_from<=$2::timestamptz AND (valid_to IS NULL OR valid_to>$2::timestamptz) AND ($3::timestamptz IS NULL OR valid_to IS NULL OR valid_to>=$3::timestamptz) ORDER BY valid_from DESC,id LIMIT 2 ${lock?"FOR UPDATE":"FOR SHARE"}`,[campusId,from,to])).rows;if(rows.length!==1)fail("CAMPUS_REGION_SOURCE_INVALID");return rows[0]!;};
const build=async(client:PostgresClient,draft:CampusRegionAssignmentPreviewDraft,now:string,lock:boolean,previewId:string):Promise<Built>=>{
  const campusId=uuid(draft.campusId),target=uuid(draft.targetRegionId),from=date(draft.effectiveFrom),requestTo=draft.effectiveTo===undefined||draft.effectiveTo===null?null:date(draft.effectiveTo);
  if((!lock&&time(from)<time(now)-1000)||(requestTo!==null&&time(requestTo)<=time(from)))fail("CAMPUS_REGION_EFFECTIVE_RANGE_INVALID");clean(draft.reason,1000);
  const campus=(await client.query<{id:string}>(`SELECT id::text FROM organization_unit WHERE id=$1::uuid AND unit_type='CAMPUS' ${lock?"FOR SHARE":""}`,[campusId])).rows;if(campus.length!==1)fail("CAMPUS_REGION_CAMPUS_NOT_FOUND");
  const targetUnit=(await client.query<{id:string}>(`SELECT id::text FROM organization_unit WHERE id=$1::uuid AND unit_type='REGION' ${lock?"FOR SHARE":""}`,[target])).rows;if(targetUnit.length!==1)fail("CAMPUS_REGION_TARGET_NOT_FOUND");
  const source=await loadSource(client,campusId,from,requestTo,lock),to=requestTo??source.valid_to;if(source.region_id===target)fail("CAMPUS_REGION_NO_CHANGE");
  const people=(await client.query<PersonAssignment>(`SELECT id::text,person_id::text,campus_id::text,region_id::text,valid_from::text,valid_to::text,created_by::text,created_at::text FROM person_campus_assignment WHERE campus_id=$1::uuid AND valid_from<COALESCE($3::timestamptz,'infinity') AND (valid_to IS NULL OR valid_to>$2::timestamptz) ORDER BY person_id,valid_from,id ${lock?"FOR UPDATE":"FOR SHARE"}`,[campusId,from,to])).rows;
  const effects=people.map(sourceRow=>{const start=time(sourceRow.valid_from)>time(from)?sourceRow.valid_from:from;const end=sourceRow.valid_to===null?to:to===null?sourceRow.valid_to:time(sourceRow.valid_to)<time(to)?sourceRow.valid_to:to;if(end!==null&&time(end)<=time(start))fail("CAMPUS_REGION_PERSON_ASSIGNMENT_INVALID");return {source:sourceRow,from:start,to:end,resultId:stableId(previewId,`person-result:${sourceRow.id}`),continuationId:end!==null&&(sourceRow.valid_to===null||time(end)<time(sourceRow.valid_to))?stableId(previewId,`person-continuation:${sourceRow.id}`):null};});
  const fees=(await client.query<Fee>(`SELECT fee.id::text,fee.version::text,fee.teaching_week_id::text,fee.settlement_month::text,fee.gross_amount_cents::text,refund.finance_document_id::text refund_id,snapshot.id::text snapshot_id,snapshot.snapshot_json,snapshot.context_json,snapshot.policy_version_id::text,snapshot.net_monthly_cents::text,EXISTS(SELECT 1 FROM person_campus_assignment a WHERE a.campus_id=$1::uuid AND a.person_id=referral.receiver_person_id AND a.valid_from<=(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') AND (a.valid_to IS NULL OR a.valid_to>(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai'))) receiver_at_campus,EXISTS(SELECT 1 FROM person_campus_assignment a WHERE a.campus_id=$1::uuid AND a.person_id=referral.referrer_person_id AND a.valid_from<=(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') AND (a.valid_to IS NULL OR a.valid_to>(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai'))) referrer_at_campus FROM weekly_fee_entry fee JOIN referral_case referral ON referral.id=fee.referral_case_id JOIN teaching_week week ON week.id=fee.teaching_week_id LEFT JOIN weekly_fee_refund_effect refund ON refund.weekly_fee_entry_id=fee.id LEFT JOIN LATERAL(SELECT s.* FROM weekly_fee_allocation_snapshot s WHERE s.weekly_fee_entry_id=fee.id ORDER BY s.sequence_no DESC LIMIT 1) snapshot ON true WHERE (week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') >=$2::timestamptz AND ($3::timestamptz IS NULL OR (week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai')<$3::timestamptz) AND EXISTS(SELECT 1 FROM person_campus_assignment a WHERE a.campus_id=$1::uuid AND (a.person_id=referral.receiver_person_id OR a.person_id=referral.referrer_person_id) AND a.valid_from<=(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') AND (a.valid_to IS NULL OR a.valid_to>(week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai'))) ORDER BY fee.id ${lock?"FOR UPDATE OF fee":"FOR SHARE OF fee"}`,[campusId,from,to])).rows;
  const impact={schemaVersion:"campus-region-assignment-preview.v1",campusId,sourceAssignment:campusFact(source),targetRegionId:target,effectiveFrom:from,effectiveTo:to,people:effects.map(e=>({sourceAssignment:personFact(e.source),effectiveFrom:e.from,effectiveTo:e.to})),fees:fees.map(f=>({feeId:f.id,version:f.version,teachingWeekId:f.teaching_week_id,settlementMonth:f.settlement_month,refunded:f.refund_id!==null,snapshotId:f.snapshot_id,receiverAtCampus:f.receiver_at_campus,referrerAtCampus:f.referrer_at_campus})),reason:clean(draft.reason,1000)};
  return {source,from,to,targetRegionId:target,resultId:stableId(previewId,`campus-result:${source.id}`),continuationId:to!==null&&(source.valid_to===null||time(to)<time(source.valid_to))?stableId(previewId,`campus-continuation:${source.id}`):null,effects,fees,impact};
};

const materialize=async(client:PostgresClient,b:Built,changeId:string|null,actorId:string,now:string)=>{
  await client.query("UPDATE campus_region_assignment SET valid_to=$2::timestamptz,superseded_by_campus_region_change_id=$3::uuid WHERE id=$1::uuid",[b.source.id,b.from,changeId]);
  await client.query("INSERT INTO campus_region_assignment(id,campus_id,region_id,valid_from,valid_to,created_by,created_at,campus_region_change_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8::uuid)",[b.resultId,b.source.campus_id,b.targetRegionId,b.from,b.to,actorId,now,changeId]);
  if(b.continuationId)await client.query("INSERT INTO campus_region_assignment(id,campus_id,region_id,valid_from,valid_to,created_by,created_at,campus_region_change_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8::uuid)",[b.continuationId,b.source.campus_id,b.source.region_id,b.to,b.source.valid_to,actorId,now,changeId]);
  for(const e of b.effects){await client.query("UPDATE person_campus_assignment SET valid_to=$2::timestamptz,superseded_by_campus_region_change_id=$3::uuid WHERE id=$1::uuid",[e.source.id,e.from,changeId]);await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at,campus_region_change_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::uuid)",[e.resultId,e.source.person_id,e.source.campus_id,b.targetRegionId,e.from,e.to,actorId,now,changeId]);if(e.continuationId)await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at,campus_region_change_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::uuid)",[e.continuationId,e.source.person_id,e.source.campus_id,e.source.region_id,e.to,e.source.valid_to,actorId,now,changeId]);}
};
type Sim={changed:number;excluded:number;deltas:readonly {accountCode:string;categoryKey:string;amountCents:string}[];frozen:readonly Json[]};
const simulate=async(client:PostgresClient,b:Built,actorId:string,now:string):Promise<Sim>=>{await client.query("SAVEPOINT campus_region_preview");try{await materialize(client,b,null,actorId,now);const all:LedgerDelta[]=[],frozen:Json[]=[];let changed=0,excluded=0;for(const f of b.fees){const previousHash=f.snapshot_json&&f.context_json?hash({snapshot:f.snapshot_json,context:f.context_json}):null;if(f.refund_id!==null){excluded++;frozen.push({feeId:f.id,version:f.version,refundId:f.refund_id,snapshotHash:previousHash,disposition:"REFUNDED"});continue;}if(!f.snapshot_id||!f.snapshot_json||!f.context_json||!f.policy_version_id||f.net_monthly_cents===null)fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE");const prior=decode(f.snapshot_json),next=await resolveSettlementContext(client,f.id),delta=allocationDelta(prior.lines,allocateSettlement(next.input),prior.accountByKey,next.accountByKey);if(delta.length)changed++;all.push(...delta);frozen.push({feeId:f.id,version:f.version,refundId:null,snapshotHash:previousHash,disposition:delta.length?"CHANGE":"CONTEXT_ONLY",nextContextHash:hash(next.contextJson)});}const deltas=aggregate(all).map(x=>({accountCode:x.accountKey,categoryKey:x.categoryKey,amountCents:x.amountCents.toString()}));await client.query("ROLLBACK TO SAVEPOINT campus_region_preview");return {changed,excluded,deltas,frozen};}catch(e){await client.query("ROLLBACK TO SAVEPOINT campus_region_preview");throw e;}};
const org=(sourceRegionId:string,targetRegionId:string,fees:readonly Fee[])=>{let gross=0n,refund=0n,management=0n;for(const x of fees){if(x.receiver_at_campus){gross+=BigInt(x.gross_amount_cents);if(x.refund_id!==null)refund+=BigInt(x.gross_amount_cents);}if(x.referrer_at_campus&&x.refund_id===null&&x.snapshot_json!==null){const line=decode(x.snapshot_json).lines.find(v=>v.key==="campusConsultation");management+=line?.cents??0n;}}return {sourceRegionId,targetRegionId,recordedGrossRevenueCents:gross.toString(),refundedGrossRevenueCents:refund.toString(),effectiveGrossRevenueCents:(gross-refund).toString(),campusManagementFeeCents:management.toString()};};

export class PostgresCampusRegionAssignmentService {
  public constructor(private readonly pool:PostgresPool){}
  public async directory(context:RoleContext,at:Date):Promise<CampusRegionAssignmentCandidateDirectory>{contextOk(context);const now=date(at.toISOString()),client=await this.pool.connect();try{await actor(client,context,now);const campuses=(await client.query<{campus_id:string;campus_name:string;region_id:string|null;region_name:string|null}>("SELECT c.id::text campus_id,c.name campus_name,a.region_id::text,region.name region_name FROM organization_unit c LEFT JOIN LATERAL(SELECT * FROM campus_region_assignment x WHERE x.campus_id=c.id AND x.valid_from<=$1::timestamptz AND (x.valid_to IS NULL OR x.valid_to>$1::timestamptz) ORDER BY x.valid_from DESC LIMIT 1) a ON true LEFT JOIN organization_unit region ON region.id=a.region_id WHERE c.unit_type='CAMPUS' ORDER BY c.name,c.id",[now])).rows;const regions=(await client.query<{region_id:string;region_name:string}>("SELECT id::text region_id,name region_name FROM organization_unit WHERE unit_type='REGION' ORDER BY name,id")).rows;return {campuses:campuses.map(x=>({campusId:x.campus_id,campusName:x.campus_name,currentRegionId:x.region_id,currentRegionName:x.region_name})),regions:regions.map(x=>({regionId:x.region_id,regionName:x.region_name}))};}finally{await client.release();}}
  public async preview(context:RoleContext,draft:CampusRegionAssignmentPreviewDraft,at:Date):Promise<CampusRegionAssignmentPreview>{contextOk(context);const now=date(at.toISOString()),client=await this.pool.connect();try{await client.query("BEGIN");const roleId=await actor(client,context,now),previewId=randomUUID(),b=await build(client,draft,now,false,previewId),sim=await simulate(client,b,context.personId,now),impact={...b.impact,financial:{consideredFeeCount:b.fees.length,changedFeeCount:sim.changed,excludedRefundCount:sim.excluded,accountDeltas:sim.deltas,fees:sim.frozen,organizationImpact:org(b.source.region_id,b.targetRegionId,b.fees)}},baseHash=hash(impact);await client.query("INSERT INTO campus_region_assignment_change_preview(id,campus_id,source_region_id,target_region_id,source_assignment_id,effective_from,effective_to,reason,base_hash,impact_json,actor_role_assignment_id,created_by_person_id,actor_subject_code,actor_scope_type,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11,$12,$13,'GLOBAL',$14)",[previewId,b.source.campus_id,b.source.region_id,b.targetRegionId,b.source.id,b.from,b.to,clean(draft.reason,1000),baseHash,stringify(impact),roleId,context.personId,context.subject,now]);await client.query("COMMIT");const affectedPeople=new Set(b.effects.map(e=>e.source.person_id)).size;return {previewId,campusId:b.source.campus_id,sourceRegionId:b.source.region_id,targetRegionId:b.targetRegionId,effectiveFrom:b.from,effectiveTo:b.to,affectedPersonCount:affectedPeople,affectedAssignmentCount:b.effects.length,consideredFeeCount:b.fees.length,changedFeeCount:sim.changed,excludedRefundCount:sim.excluded,organizationImpact:org(b.source.region_id,b.targetRegionId,b.fees),accountDeltas:sim.deltas};}catch(e){await client.query("ROLLBACK");throw e;}finally{await client.release();}}
  public async publish(context:RoleContext,previewIdRaw:string,keyRaw:string,at:Date):Promise<CampusRegionAssignmentChange>{
    contextOk(context); const previewId=uuid(previewIdRaw),key=clean(keyRaw,200),now=date(at.toISOString()),client=await this.pool.connect();
    try { await client.query("BEGIN"); await lockSettlementAllocationExclusive(client); await actor(client,context,now);
      const replay=(await client.query<{id:string;preview_id:string;assignment_version:string;result_assignment_id:string;posting_status:"POSTED"|"NO_BALANCE_CHANGE";considered_person_count:number;affected_assignment_count:number;considered_fee_count:number;changed_fee_count:number;excluded_refund_count:number}>("SELECT id::text,preview_id::text,assignment_version::text,result_assignment_id::text,posting_status,considered_person_count,affected_assignment_count,considered_fee_count,changed_fee_count,excluded_refund_count FROM campus_region_assignment_change WHERE published_by_person_id=$1::uuid AND idempotency_key=$2 FOR SHARE",[context.personId,key])).rows[0];
      if(replay){ if(replay.preview_id!==previewId)fail("IDEMPOTENCY_REPLAY"); await client.query("COMMIT"); return {changeId:replay.id,previewId:replay.preview_id,campusVersion:Number(replay.assignment_version),resultCampusRegionAssignmentId:replay.result_assignment_id,affectedPersonCount:replay.considered_person_count,affectedAssignmentCount:replay.affected_assignment_count,postingStatus:replay.posting_status,consideredFeeCount:replay.considered_fee_count,changedFeeCount:replay.changed_fee_count,excludedRefundCount:replay.excluded_refund_count,replay:true}; }
    const p=(await client.query<PreviewRow>("SELECT id::text,base_hash,campus_id::text,source_region_id::text,target_region_id::text,source_assignment_id::text,effective_from::text,effective_to::text,reason FROM campus_region_assignment_change_preview WHERE id=$1::uuid FOR UPDATE",[previewId])).rows[0]??fail("CAMPUS_REGION_PREVIEW_NOT_FOUND");if((await client.query("SELECT 1 FROM campus_region_assignment_change WHERE preview_id=$1::uuid FOR SHARE",[previewId])).rows.length)fail("CAMPUS_REGION_PREVIEW_STALE");const b=await build(client,{campusId:p.campus_id,targetRegionId:p.target_region_id,effectiveFrom:p.effective_from,effectiveTo:p.effective_to,reason:p.reason},now,true,previewId);if(b.source.id!==p.source_assignment_id)fail("CAMPUS_REGION_PREVIEW_STALE");const sim=await simulate(client,b,context.personId,now),impact={...b.impact,financial:{consideredFeeCount:b.fees.length,changedFeeCount:sim.changed,excludedRefundCount:sim.excluded,accountDeltas:sim.deltas,fees:sim.frozen,organizationImpact:org(b.source.region_id,b.targetRegionId,b.fees)}};if(hash(impact)!==p.base_hash)fail("CAMPUS_REGION_PREVIEW_STALE");await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))",[`campus-region-assignment-version:${p.campus_id}`]);const changeId=randomUUID(),version=Number((await client.query<{v:string}>("SELECT COALESCE(max(assignment_version),0)+1::bigint v FROM campus_region_assignment_change WHERE campus_id=$1::uuid",[p.campus_id])).rows[0]?.v??"1");await materialize(client,b,changeId,context.personId,now);
    const work:{fee:Fee;resultId:string;previous:{lines:{key:string;cents:bigint}[];accountByKey:Record<string,string>};next:Awaited<ReturnType<typeof resolveSettlementContext>>;delta:readonly LedgerDelta[]}[]=[];let excluded=0;for(const f of b.fees){if(f.refund_id!==null){excluded++;continue;}if(!f.snapshot_id||!f.snapshot_json||!f.context_json||!f.policy_version_id||f.net_monthly_cents===null)fail("CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE");const previous=decode(f.snapshot_json),next=await resolveSettlementContext(client,f.id),delta=allocationDelta(previous.lines,allocateSettlement(next.input),previous.accountByKey,next.accountByKey);work.push({fee:f,resultId:randomUUID(),previous,next,delta});}const deltas=aggregate(work.flatMap(x=>x.delta));let runId:string|null=null,eventId:string|null=null;if(work.length){runId=randomUUID();if(deltas.length){const posted=await postLedgerEvent({transaction:w=>w(createPostgresLedgerTransaction(client))},{eventKey:`weekly-settlement:campus-region-change:${changeId}`,eventType:"WEEKLY_FEE_SETTLEMENT",payloadHash:hash({changeId,fees:work.map(x=>x.fee.id)}),deltas},randomUUID);eventId=posted.event.eventId;}const anchor=work[0]!;await client.query("INSERT INTO settlement_calculation_run(id,request_key,fee_entry_id,fee_version,actor_person_id,status,ledger_event_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[runId,`campus-region-change:${changeId}`,anchor.fee.id,anchor.fee.version,context.personId,eventId?"POSTED":"NO_BALANCE_CHANGE",eventId,now]);for(const x of work)await client.query("INSERT INTO weekly_fee_allocation_snapshot(id,run_id,weekly_fee_entry_id,source_weekly_fee_version,policy_version_id,net_monthly_cents,snapshot_json,context_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9)",[x.resultId,runId,x.fee.id,x.fee.version,x.fee.policy_version_id,x.fee.net_monthly_cents,stringify({lines:allocateSettlement(x.next.input).map(l=>({key:l.key,cents:l.cents.toString()})),accountByKey:x.next.accountByKey}),stringify(x.next.contextJson),now]);}
    const before={campusRegionAssignment:campusFact(b.source)},after={campusRegionAssignment:{id:b.resultId,campusId:b.source.campus_id,regionId:b.targetRegionId,validFrom:b.from,validTo:b.to}};
    await client.query("INSERT INTO campus_region_assignment_change(id,preview_id,campus_id,source_region_id,target_region_id,source_assignment_id,result_assignment_id,continuation_assignment_id,assignment_version,effective_from,effective_to,reason,idempotency_key,request_hash,base_hash,posting_status,settlement_calculation_run_id,ledger_event_id,considered_person_count,affected_assignment_count,considered_fee_count,changed_fee_count,excluded_refund_count,before_json,after_json,published_by_person_id,actor_subject_code,actor_scope_type,published_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24::jsonb,$25::jsonb,$26,$27,'GLOBAL',$28,$28)",[changeId,previewId,b.source.campus_id,b.source.region_id,b.targetRegionId,b.source.id,b.resultId,b.continuationId,version,b.from,b.to,p.reason,key,hash({previewId,key}),p.base_hash,eventId?"POSTED":"NO_BALANCE_CHANGE",runId,eventId,new Set(b.effects.map(e=>e.source.person_id)).size,b.effects.length,b.fees.length,work.filter(x=>x.delta.length).length,excluded,stringify(before),stringify(after),context.personId,context.subject,now]);
    for(const e of b.effects)await client.query("INSERT INTO campus_region_assignment_person_effect(change_id,person_id,source_assignment_id,result_assignment_id,continuation_assignment_id,effective_from,effective_to,before_json,after_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9::jsonb,$10)",[changeId,e.source.person_id,e.source.id,e.resultId,e.continuationId,e.from,e.to,stringify(personFact(e.source)),stringify({id:e.resultId,personId:e.source.person_id,campusId:e.source.campus_id,regionId:b.targetRegionId,validFrom:e.from,validTo:e.to}),now]);
    if(runId)for(const x of work)await client.query("INSERT INTO campus_region_assignment_settlement_effect(change_id,weekly_fee_entry_id,source_weekly_fee_version,teaching_week_id,settlement_month,previous_snapshot_id,result_snapshot_id,settlement_calculation_run_id,delta_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)",[changeId,x.fee.id,x.fee.version,x.fee.teaching_week_id,x.fee.settlement_month,x.fee.snapshot_id,x.resultId,runId,stringify({entries:x.delta.map(d=>({...d,amountCents:d.amountCents.toString()}))}),now]);
    await client.query("INSERT INTO audit_event(actor_person_id,action_code,subject_type,subject_id,before_json,after_json,reason,created_at) VALUES($1,'CAMPUS_REGION_ASSIGNMENT_CHANGED','CAMPUS_REGION_ASSIGNMENT_CHANGE',$2,$3::jsonb,$4::jsonb,$5,$6)",[context.personId,changeId,stringify(before),stringify(after),p.reason,now]); await client.query("COMMIT");
    const affectedPeople=new Set(b.effects.map(e=>e.source.person_id)).size;
    return {changeId,previewId,campusVersion:version,resultCampusRegionAssignmentId:b.resultId,affectedPersonCount:affectedPeople,affectedAssignmentCount:b.effects.length,postingStatus:eventId?"POSTED":"NO_BALANCE_CHANGE",consideredFeeCount:b.fees.length,changedFeeCount:work.filter(x=>x.delta.length).length,excludedRefundCount:excluded,replay:false};
  }catch(e){await client.query("ROLLBACK");throw e;}finally{await client.release();}}
}
