import { createHash, randomUUID } from "node:crypto";
import type { RoleContext } from "@teaching-research-alliance/contracts";
import { allocationDelta, allocateSettlement, postLedgerEvent, type LedgerDelta } from "@teaching-research-alliance/domain";
import { createPostgresLedgerTransaction, type PostgresClient, type PostgresPool } from "./postgres-ledger-repository.js";
import { lockSettlementAllocationExclusive } from "./postgres-settlement-allocation-gate.js";
import { resolveSettlementContext } from "./postgres-settlement-context.js";

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
type Json = Record<string, unknown>;
type Assignment = { id: string; person_id: string; campus_id: string; region_id: string; valid_from: string; valid_to: string | null; created_by: string; created_at: string };
type Relationship = { id: string; teacher_id: string; related_person_id: string; valid_from: string; valid_to: string | null; effective_scope: string | null; created_by: string; created_at: string };
type Principal = { person_id: string; nickname: string; role_assignment_id: string; valid_from: string; valid_to: string | null };
type Action = "TRANSFER" | "PRINCIPAL_REPAIR";
type PreviewRow = { id: string; action: Action; base_hash: string; impact_json: unknown; person_id: string; target_campus_id: string; target_region_id: string; target_principal_person_id: string; target_principal_role_assignment_id: string; source_assignment_id: string; result_assignment_id: string | null; continuation_assignment_id: string | null; source_campus_principal_relationship_id: string | null; result_campus_principal_relationship_id: string; continuation_campus_principal_relationship_id: string | null; effective_from: string; effective_to: string | null; reason: string };
type Fee = { id: string; version: string; teaching_week_id: string; settlement_month: string; gross_amount_cents: string; refund_id: string | null; referrer_person_id: string; referrer_identity: string; snapshot_id: string | null; snapshot_json: unknown | null; context_json: unknown | null; policy_version_id: string | null; net_monthly_cents: string | null };

export type PersonCampusAssignmentPreviewDraft = Readonly<{ personId: string; targetCampusId: string; effectiveFrom: string; effectiveTo?: string | null; reason: string }>;
export type PersonCampusAssignmentCandidateDirectory = Readonly<{
  people: readonly Readonly<{ personId: string; nickname: string; currentCampusId: string | null; currentCampusName: string | null; currentRegionId: string | null; currentRegionName: string | null }>[];
  campuses: readonly Readonly<{ campusId: string; campusName: string }>[];
  regions: readonly Readonly<{ regionId: string; regionName: string }>[];
}>;
export type PersonCampusAssignmentPreview = Readonly<{
  previewId: string; personId: string; targetCampusId: string; targetRegionId: string; targetPrincipalPersonId: string; targetPrincipalNickname: string;
  sourceCampusId: string; sourceRegionId: string; sourcePrincipalPersonId: string | null; effectiveFrom: string; effectiveTo: string | null; consideredFeeCount: number; changedFeeCount: number; excludedRefundCount: number;
  organizationImpact: Readonly<{ sourceCampusId: string; sourceRegionId: string; targetCampusId: string; targetRegionId: string; recordedGrossRevenueCents: string; refundedGrossRevenueCents: string; effectiveGrossRevenueCents: string; campusManagementFeeCents: string }>;
  accountDeltas: readonly Readonly<{ accountCode: string; categoryKey: string; amountCents: string }>[];
}>;
export type PersonCampusAssignmentChangeResult = Readonly<{ changeId: string; previewId: string; assignmentVersion: number; resultAssignmentId: string | null; resultCampusPrincipalRelationshipId: string; postingStatus: "POSTED" | "NO_BALANCE_CHANGE"; consideredFeeCount: number; changedFeeCount: number; excludedRefundCount: number; replay: boolean }>;

const fail = (code: string): never => { throw new Error(code); };
const stringify = (value: unknown): string => JSON.stringify(value, (_key, item) => typeof item === "bigint" ? item.toString() : item);
const hash = (value: unknown): string => createHash("sha256").update(stringify(value)).digest("hex");
const uuid = (value: string): string => UUID.test(value) ? value.toLowerCase() : fail("INVALID_INPUT");
const validDate = (value: string): string => { const at = new Date(value); if (!Number.isFinite(at.getTime())) fail("INVALID_INPUT"); return at.toISOString(); };
const clean = (value: string, limit: number): string => { const out = value.trim(); return out && out.length <= limit && !/[\x00-\x1f\x7f]/.test(out) ? out : fail("INVALID_INPUT"); };
const instant = (value: string): number => Date.parse(value);
const fact = (row: Assignment) => ({ id: row.id, personId: row.person_id, campusId: row.campus_id, regionId: row.region_id, validFrom: row.valid_from, validTo: row.valid_to, createdByPersonId: row.created_by, createdAt: row.created_at });
const relationshipFact = (row: Relationship) => ({ id: row.id, teacherPersonId: row.teacher_id, relatedPersonId: row.related_person_id, relationshipType: "CAMPUS_PRINCIPAL", validFrom: row.valid_from, validTo: row.valid_to, effectiveScope: row.effective_scope, createdByPersonId: row.created_by, createdAt: row.created_at });
const assertContext = (context: RoleContext): void => {
  if (!(["SYSTEM_OWNER", "SYSTEM_ADMIN"] as const).includes(context.subject as "SYSTEM_OWNER") || context.scope !== "GLOBAL" || !UUID.test(context.personId) || context.regionId !== undefined || context.campusId !== undefined || context.venueId !== undefined) fail("FORBIDDEN_SCOPE");
};
const actor = async (client: PostgresClient, context: RoleContext, at: string): Promise<string> => {
  const rows = (await client.query<{ id: string }>(`SELECT id::text FROM role_assignment WHERE person_id=$1::uuid AND subject_code=$2 AND scope_type='GLOBAL' AND scope_id IS NULL AND valid_from<=$3::timestamptz AND (valid_to IS NULL OR valid_to>$3::timestamptz) ORDER BY id LIMIT 2 FOR SHARE`, [context.personId, context.subject, at])).rows;
  if (rows.length !== 1) fail("FORBIDDEN_SCOPE"); return rows[0]!.id;
};
const assignmentAt = async (client: PostgresClient, personId: string, from: string, to: string | null, lock: boolean): Promise<Assignment> => {
  const rows = (await client.query<Assignment>(`SELECT id::text,person_id::text,campus_id::text,region_id::text,valid_from::text,valid_to::text,created_by::text,created_at::text FROM person_campus_assignment WHERE person_id=$1::uuid AND valid_from<=$2::timestamptz AND (valid_to IS NULL OR valid_to>$2::timestamptz) AND ($3::timestamptz IS NULL OR valid_to IS NULL OR valid_to>=$3::timestamptz) ORDER BY valid_from DESC,id LIMIT 2 ${lock ? "FOR UPDATE" : "FOR SHARE"}`, [personId, from, to])).rows;
  if (rows.length !== 1) fail("PERSON_CAMPUS_ASSIGNMENT_SOURCE_INVALID"); return rows[0]!;
};
const principalAt = async (client: PostgresClient, campusId: string, from: string, to: string | null, lock: boolean): Promise<Principal> => {
  const rows = (await client.query<Principal>(`SELECT p.id::text AS person_id,p.nickname,r.id::text AS role_assignment_id,r.valid_from::text,r.valid_to::text FROM role_assignment r JOIN person p ON p.id=r.person_id WHERE r.subject_code='CAMPUS_PRINCIPAL' AND r.scope_type='CAMPUS' AND r.scope_id=$1::uuid AND p.status='ACTIVE' AND r.valid_from<=$2::timestamptz AND (r.valid_to IS NULL OR r.valid_to>$2::timestamptz) AND (($3::timestamptz IS NULL AND r.valid_to IS NULL) OR ($3::timestamptz IS NOT NULL AND (r.valid_to IS NULL OR r.valid_to>=$3::timestamptz))) ORDER BY r.valid_from DESC,r.id LIMIT 2 ${lock ? "FOR SHARE" : ""}`, [campusId, from, to])).rows;
  if (rows.length !== 1) fail("PERSON_CAMPUS_TARGET_PRINCIPAL_INVALID"); return rows[0]!;
};
const targetRegion = async (client: PostgresClient, campusId: string, from: string, to: string | null, lock: boolean): Promise<string> => {
  const rows = (await client.query<{ region_id: string }>(`SELECT region_id::text FROM campus_region_assignment WHERE campus_id=$1::uuid AND valid_from<=$2::timestamptz AND (valid_to IS NULL OR valid_to>=$3::timestamptz) ORDER BY valid_from DESC,id LIMIT 2 ${lock ? "FOR SHARE" : ""}`, [campusId, from, to])).rows;
  if (rows.length !== 1) fail("PERSON_CAMPUS_TARGET_REGION_NOT_UNIQUE"); return rows[0]!.region_id;
};
const campusRelationshipAt = async (client: PostgresClient, personId: string, from: string, to: string | null, lock: boolean): Promise<Relationship | null> => {
  const rows = (await client.query<Relationship>(`SELECT id::text,teacher_id::text,related_person_id::text,valid_from::text,valid_to::text,effective_scope,created_by::text,created_at::text FROM person_relationship WHERE teacher_id=$1::uuid AND relationship_type='CAMPUS_PRINCIPAL' AND valid_from<=$2::timestamptz AND (valid_to IS NULL OR valid_to>$2::timestamptz) AND ($3::timestamptz IS NULL OR valid_to IS NULL OR valid_to>=$3::timestamptz) ORDER BY valid_from DESC,id LIMIT 2 ${lock ? "FOR UPDATE" : "FOR SHARE"}`, [personId, from, to])).rows;
  if (rows.length > 1) fail("PERSON_CAMPUS_PRINCIPAL_RELATIONSHIP_AMBIGUOUS"); return rows[0] ?? null;
};

type Built = { action: Action; source: Assignment; sourcePrincipal: Relationship | null; continuationPrincipal: Principal | null; targetPrincipal: Principal; targetRegionId: string; effectiveFrom: string; effectiveTo: string | null; resultAssignmentId: string | null; continuationAssignmentId: string | null; resultRelationshipId: string; continuationRelationshipId: string | null; impact: Json; baseHash: string; fees: readonly Fee[]; };
const build = async (client: PostgresClient, draft: PersonCampusAssignmentPreviewDraft, at: string, lock: boolean): Promise<Built> => {
  const personId = uuid(draft.personId), campusId = uuid(draft.targetCampusId), from = validDate(draft.effectiveFrom), requestedTo = draft.effectiveTo === null || draft.effectiveTo === undefined ? null : validDate(draft.effectiveTo);
  if ((!lock && instant(from) < instant(at) - 1_000) || (requestedTo !== null && instant(requestedTo) <= instant(from))) fail("PERSON_CAMPUS_EFFECTIVE_RANGE_INVALID");
  clean(draft.reason, 1000);
  const person = (await client.query<{ id: string }>(`SELECT person.id::text FROM person JOIN teacher_profile profile ON profile.person_id=person.id WHERE person.id=$1::uuid AND person.status='ACTIVE' AND profile.employment_status='ACTIVE' ${lock ? "FOR SHARE OF person,profile" : ""}`, [personId])).rows;
  if (person.length !== 1) fail("PERSON_CAMPUS_PERSON_NOT_ELIGIBLE");
  const campus = (await client.query<{ id: string }>(`SELECT id::text FROM organization_unit WHERE id=$1::uuid AND unit_type='CAMPUS' ${lock ? "FOR SHARE" : ""}`, [campusId])).rows;
  if (campus.length !== 1) fail("PERSON_CAMPUS_TARGET_NOT_FOUND");
  const source = await assignmentAt(client, personId, from, requestedTo, lock);
  const to = requestedTo ?? source.valid_to;
  const region = await targetRegion(client, campusId, from, to, lock), principal = await principalAt(client, campusId, from, to, lock), sourcePrincipal = await campusRelationshipAt(client, personId, from, null, lock);
  const hasContinuation = to !== null && (source.valid_to === null || instant(to) < instant(source.valid_to));
  const continuationPrincipal = hasContinuation ? await principalAt(client, source.campus_id, to!, source.valid_to, lock) : null;
  const action: Action = source.campus_id === campusId && source.region_id === region ? "PRINCIPAL_REPAIR" : "TRANSFER";
  if (action === "PRINCIPAL_REPAIR" && sourcePrincipal?.related_person_id === principal.person_id) fail("PERSON_CAMPUS_ASSIGNMENT_NO_CHANGE");
  const fees = (await client.query<Fee>(`SELECT fee.id::text,fee.version::text,fee.teaching_week_id::text,fee.settlement_month::text,fee.gross_amount_cents::text,refund.finance_document_id::text AS refund_id,referral.referrer_person_id::text,referral.referrer_identity,snapshot.id::text AS snapshot_id,snapshot.snapshot_json,snapshot.context_json,snapshot.policy_version_id::text,snapshot.net_monthly_cents::text FROM weekly_fee_entry fee JOIN referral_case referral ON referral.id=fee.referral_case_id JOIN teaching_week week ON week.id=fee.teaching_week_id LEFT JOIN weekly_fee_refund_effect refund ON refund.weekly_fee_entry_id=fee.id LEFT JOIN LATERAL (SELECT candidate.* FROM weekly_fee_allocation_snapshot candidate WHERE candidate.weekly_fee_entry_id=fee.id ORDER BY candidate.sequence_no DESC LIMIT 1) snapshot ON true WHERE (referral.receiver_person_id=$1::uuid OR referral.referrer_person_id=$1::uuid) AND (week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') >= $2::timestamptz AND ($3::timestamptz IS NULL OR (week.starts_on::timestamp AT TIME ZONE 'Asia/Shanghai') < $3::timestamptz) ORDER BY fee.id ${lock ? "FOR UPDATE OF fee" : "FOR SHARE OF fee"}`, [personId, from, to])).rows;
  const impact: Json = { schemaVersion: "person-campus-assignment-preview.v1", action, personId, sourceAssignment: fact(source), sourceCampusPrincipalRelationship: sourcePrincipal ? relationshipFact(sourcePrincipal) : null, targetCampusId: campusId, targetRegionId: region, targetPrincipal: { personId: principal.person_id, nickname: principal.nickname, roleAssignmentId: principal.role_assignment_id, validFrom: principal.valid_from, validTo: principal.valid_to }, effectiveFrom: from, effectiveTo: to, fees: fees.map(fee => ({ feeId: fee.id, version: fee.version, teachingWeekId: fee.teaching_week_id, settlementMonth: fee.settlement_month, refunded: false, snapshotId: fee.snapshot_id })), reason: clean(draft.reason, 1000) };
  return { action, source, sourcePrincipal, continuationPrincipal, targetPrincipal: principal, targetRegionId: region, effectiveFrom: from, effectiveTo: to, resultAssignmentId: action === "TRANSFER" ? randomUUID() : null, continuationAssignmentId: action === "TRANSFER" && hasContinuation ? randomUUID() : null, resultRelationshipId: randomUUID(), continuationRelationshipId: hasContinuation ? randomUUID() : null, impact, baseHash: hash(impact), fees };
};

const decode = (raw: unknown): { lines: { key: string; cents: bigint }[]; accountByKey: Record<string, string> } => {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE");
  const value = raw as { lines?: unknown; accountByKey?: unknown };
  if (!Array.isArray(value.lines) || value.accountByKey === null || typeof value.accountByKey !== "object" || Array.isArray(value.accountByKey)) fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE");
  return { lines: (value.lines as unknown[]).map((line: unknown) => { const row = line as { key?: unknown; cents?: unknown }; const key = typeof row.key === "string" ? row.key : fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE"); const cents = typeof row.cents === "string" && /^-?\d+$/.test(row.cents) ? row.cents : fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE"); return { key, cents: BigInt(cents) }; }), accountByKey: value.accountByKey as Record<string,string> };
};
const aggregate = (deltas: readonly LedgerDelta[]): LedgerDelta[] => [...deltas.reduce((out, entry) => { const key = `${entry.accountKey}\u0000${entry.categoryKey}`; out.set(key, { ...entry, amountCents: (out.get(key)?.amountCents ?? 0n) + entry.amountCents }); return out; }, new Map<string, LedgerDelta>()).values()].filter(entry => entry.amountCents !== 0n);
const organizationImpact = (personId: string, source: Assignment, targetCampusId: string, targetRegionId: string, fees: readonly Fee[]) => {
  let recorded = 0n, refunded = 0n, management = 0n;
  for (const fee of fees) {
    const gross = BigInt(fee.gross_amount_cents); recorded += gross;
    if (fee.refund_id !== null) { refunded += gross; continue; }
    if (fee.referrer_person_id === personId && fee.referrer_identity === "ACADEMIC_PLANNER" && fee.snapshot_json !== null) {
      const line = decode(fee.snapshot_json).lines.find((item) => item.key === "campusConsultation");
      management += line?.cents ?? 0n;
    }
  }
  return { sourceCampusId: source.campus_id, sourceRegionId: source.region_id, targetCampusId, targetRegionId, recordedGrossRevenueCents: recorded.toString(), refundedGrossRevenueCents: refunded.toString(), effectiveGrossRevenueCents: (recorded-refunded).toString(), campusManagementFeeCents: management.toString() };
};
type SimulatedImpact = { changedFeeCount: number; excludedRefundCount: number; accountDeltas: readonly { accountCode: string; categoryKey: string; amountCents: string }[]; frozenFees: readonly Json[] };
const simulateSettlementImpact = async (client: PostgresClient, built: Built, personId: string, targetCampusId: string, from: string, to: string | null, actorId: string, at: string): Promise<SimulatedImpact> => {
  await client.query("SAVEPOINT person_campus_assignment_preview");
  try {
    // This is the exact temporal materialization used by publish, rolled back
    // after resolving settlement. It prevents a display-only estimate from
    // drifting away from the formal settlement resolver.
    if (built.action === "TRANSFER") {
      await client.query("UPDATE person_campus_assignment SET valid_to=$2::timestamptz WHERE id=$1::uuid", [built.source.id, from]);
      await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [built.resultAssignmentId, personId, targetCampusId, built.targetRegionId, from, to, actorId, at]);
      if (built.continuationAssignmentId !== null) await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)", [built.continuationAssignmentId, built.source.person_id, built.source.campus_id, built.source.region_id, to, built.source.valid_to, actorId, at]);
    }
    if (built.sourcePrincipal) await client.query("UPDATE person_relationship SET valid_to=$2::timestamptz WHERE id=$1::uuid", [built.sourcePrincipal.id, from]);
    await client.query("INSERT INTO person_relationship(id,teacher_id,relationship_type,related_person_id,valid_from,valid_to,effective_scope,created_by,created_at) VALUES($1,$2,'CAMPUS_PRINCIPAL',$3,$4,$5,'CAMPUS',$6,$7)", [built.resultRelationshipId, personId, built.targetPrincipal.person_id, from, to, actorId, at]);
    if (built.continuationRelationshipId !== null) await client.query("INSERT INTO person_relationship(id,teacher_id,relationship_type,related_person_id,valid_from,valid_to,effective_scope,created_by,created_at) VALUES($1,$2,'CAMPUS_PRINCIPAL',$3,$4,$5,'CAMPUS',$6,$7)", [built.continuationRelationshipId, personId, built.continuationPrincipal?.person_id ?? fail("PERSON_CAMPUS_TARGET_PRINCIPAL_INVALID"), to, built.source.valid_to, actorId, at]);
    const deltas: LedgerDelta[]=[]; const frozenFees: Json[]=[]; let changed=0, excluded=0;
    for (const fee of built.fees) {
      const snapshotHash = fee.snapshot_json === null || fee.context_json === null ? null : hash({snapshot:fee.snapshot_json,context:fee.context_json});
      if (fee.refund_id !== null) { excluded++; frozenFees.push({feeId:fee.id,version:fee.version,refundId:fee.refund_id,snapshotHash,disposition:"REFUNDED"}); continue; }
      if (!fee.snapshot_json) fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE");
      const previous=decode(fee.snapshot_json), resolved=await resolveSettlementContext(client,fee.id), next={lines:allocateSettlement(resolved.input),accountByKey:resolved.accountByKey};
      const delta=allocationDelta(previous.lines,next.lines,previous.accountByKey,next.accountByKey); if(delta.length) changed++; deltas.push(...delta);
      frozenFees.push({feeId:fee.id,version:fee.version,refundId:null,snapshotHash,disposition:delta.length?"CHANGE":"CONTEXT_ONLY",nextContextHash:hash(resolved.contextJson)});
    }
    const accountDeltas=aggregate(deltas).map((entry)=>({accountCode:entry.accountKey,categoryKey:entry.categoryKey,amountCents:entry.amountCents.toString()}));
    await client.query("ROLLBACK TO SAVEPOINT person_campus_assignment_preview");
    return {changedFeeCount:changed,excludedRefundCount:excluded,accountDeltas,frozenFees};
  } catch (error) { await client.query("ROLLBACK TO SAVEPOINT person_campus_assignment_preview"); throw error; }
};

export class PostgresPersonCampusAssignmentService {
  public constructor(private readonly pool: PostgresPool) {}
  public async listDirectory(context: RoleContext, at: Date): Promise<PersonCampusAssignmentCandidateDirectory> {
    assertContext(context); const iso = validDate(at.toISOString()); const client = await this.pool.connect();
    try { await actor(client, context, iso); const people = (await client.query<{person_id:string;nickname:string;campus_id:string|null;campus_name:string|null;region_id:string|null;region_name:string|null}>(`SELECT p.id::text person_id,p.nickname,a.campus_id::text,campus.name campus_name,a.region_id::text,region.name region_name FROM person p JOIN teacher_profile profile ON profile.person_id=p.id LEFT JOIN LATERAL (SELECT * FROM person_campus_assignment x WHERE x.person_id=p.id AND x.valid_from<=$1::timestamptz AND (x.valid_to IS NULL OR x.valid_to>$1::timestamptz) ORDER BY x.valid_from DESC LIMIT 1) a ON true LEFT JOIN organization_unit campus ON campus.id=a.campus_id LEFT JOIN organization_unit region ON region.id=a.region_id WHERE p.status='ACTIVE' AND profile.employment_status='ACTIVE' ORDER BY p.nickname,p.id`, [iso])).rows;
      const campuses = (await client.query<{campus_id:string;campus_name:string}>("SELECT id::text campus_id,name campus_name FROM organization_unit WHERE unit_type='CAMPUS' ORDER BY name,id")).rows;
      const regions = (await client.query<{region_id:string;region_name:string}>("SELECT id::text region_id,name region_name FROM organization_unit WHERE unit_type='REGION' ORDER BY name,id")).rows;
      return { people: people.map(x=>({personId:x.person_id,nickname:x.nickname,currentCampusId:x.campus_id,currentCampusName:x.campus_name,currentRegionId:x.region_id,currentRegionName:x.region_name})), campuses: campuses.map(x=>({campusId:x.campus_id,campusName:x.campus_name})), regions: regions.map(x=>({regionId:x.region_id,regionName:x.region_name})) }; } finally { await client.release(); }
  }
  public async preview(context: RoleContext, draft: PersonCampusAssignmentPreviewDraft, at: Date): Promise<PersonCampusAssignmentPreview> {
    assertContext(context); const now = validDate(at.toISOString()); const client = await this.pool.connect();
    try { await client.query("BEGIN"); const roleId = await actor(client, context, now), built = await build(client,draft,now,false), previewId=randomUUID();
      const simulated=await simulateSettlementImpact(client,built,draft.personId,draft.targetCampusId,built.effectiveFrom,built.effectiveTo,context.personId,now);
      const frozenImpact={...built.impact,financial:{consideredFeeCount:built.fees.length,changedFeeCount:simulated.changedFeeCount,excludedRefundCount:simulated.excludedRefundCount,accountDeltas:simulated.accountDeltas,fees:simulated.frozenFees,organizationImpact:organizationImpact(draft.personId,built.source,draft.targetCampusId,built.targetRegionId,built.fees)}}; const baseHash=hash(frozenImpact);
      await client.query(`INSERT INTO person_campus_assignment_change_preview(id,action,person_id,source_assignment_id,result_assignment_id,continuation_assignment_id,source_campus_principal_relationship_id,result_campus_principal_relationship_id,continuation_campus_principal_relationship_id,target_campus_id,target_region_id,target_principal_person_id,target_principal_role_assignment_id,effective_from,effective_to,reason,base_hash,impact_json,actor_role_assignment_id,created_by_person_id,actor_subject_code,actor_scope_type,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19,$20,$21,'GLOBAL',$22)`, [previewId,built.action,draft.personId,built.source.id,built.resultAssignmentId,built.continuationAssignmentId,built.sourcePrincipal?.id??null,built.resultRelationshipId,built.continuationRelationshipId,draft.targetCampusId,built.targetRegionId,built.targetPrincipal.person_id,built.targetPrincipal.role_assignment_id,built.effectiveFrom,built.effectiveTo,clean(draft.reason,1000),baseHash,stringify(frozenImpact),roleId,context.personId,context.subject,now]); await client.query("COMMIT");
      return {previewId,personId:draft.personId,targetCampusId:draft.targetCampusId,targetRegionId:built.targetRegionId,targetPrincipalPersonId:built.targetPrincipal.person_id,targetPrincipalNickname:built.targetPrincipal.nickname,sourceCampusId:built.source.campus_id,sourceRegionId:built.source.region_id,sourcePrincipalPersonId:built.sourcePrincipal?.related_person_id??null,effectiveFrom:built.effectiveFrom,effectiveTo:built.effectiveTo,consideredFeeCount:built.fees.length,changedFeeCount:simulated.changedFeeCount,excludedRefundCount:simulated.excludedRefundCount,organizationImpact:organizationImpact(draft.personId,built.source,draft.targetCampusId,built.targetRegionId,built.fees),accountDeltas:simulated.accountDeltas};
    } catch(error) { await client.query("ROLLBACK"); throw error; } finally { await client.release(); }
  }
  public async publish(context: RoleContext, previewIdRaw: string, idempotencyKeyRaw: string, at: Date): Promise<PersonCampusAssignmentChangeResult> {
    assertContext(context); const previewId=uuid(previewIdRaw), idempotencyKey=clean(idempotencyKeyRaw,200), now=validDate(at.toISOString()), client=await this.pool.connect();
    try { await client.query("BEGIN"); await lockSettlementAllocationExclusive(client); const roleId=await actor(client,context,now);
      const replay=(await client.query<{id:string;preview_id:string;assignment_version:string;result_assignment_id:string|null;result_campus_principal_relationship_id:string;posting_status:"POSTED"|"NO_BALANCE_CHANGE";considered_fee_count:number;changed_fee_count:number;excluded_refund_count:number}>(`SELECT id::text,preview_id::text,assignment_version::text,result_assignment_id::text,result_campus_principal_relationship_id::text,posting_status,considered_fee_count,changed_fee_count,excluded_refund_count FROM person_campus_assignment_change WHERE published_by_person_id=$1::uuid AND idempotency_key=$2 FOR SHARE`,[context.personId,idempotencyKey])).rows[0];
      if(replay){ if (replay.preview_id !== previewId) fail("IDEMPOTENCY_REPLAY"); const request=(await client.query<{base_hash:string}>("SELECT base_hash FROM person_campus_assignment_change_preview WHERE id=$1::uuid",[previewId])).rows[0]; if(!request||request.base_hash!== (await client.query<{base_hash:string}>("SELECT base_hash FROM person_campus_assignment_change WHERE id=$1::uuid",[replay.id])).rows[0]?.base_hash) fail("IDEMPOTENCY_REPLAY"); await client.query("COMMIT"); return {changeId:replay.id,previewId:replay.preview_id,assignmentVersion:Number(replay.assignment_version),resultAssignmentId:replay.result_assignment_id,resultCampusPrincipalRelationshipId:replay.result_campus_principal_relationship_id,postingStatus:replay.posting_status,consideredFeeCount:replay.considered_fee_count,changedFeeCount:replay.changed_fee_count,excludedRefundCount:replay.excluded_refund_count,replay:true}; }
      const preview=(await client.query<PreviewRow>(`SELECT id::text,action,base_hash,impact_json,person_id::text,target_campus_id::text,target_region_id::text,target_principal_person_id::text,target_principal_role_assignment_id::text,source_assignment_id::text,result_assignment_id::text,continuation_assignment_id::text,source_campus_principal_relationship_id::text,result_campus_principal_relationship_id::text,continuation_campus_principal_relationship_id::text,effective_from::text,effective_to::text,reason FROM person_campus_assignment_change_preview WHERE id=$1::uuid FOR UPDATE`,[previewId])).rows[0] ?? fail("PERSON_CAMPUS_PREVIEW_NOT_FOUND");
      if ((await client.query<{ id: string }>("SELECT id::text FROM person_campus_assignment_change WHERE preview_id=$1::uuid FOR SHARE", [previewId])).rows.length) fail("PERSON_CAMPUS_PREVIEW_STALE");
      const built=await build(client,{personId:preview.person_id,targetCampusId:preview.target_campus_id,effectiveFrom:preview.effective_from,effectiveTo:preview.effective_to,reason:preview.reason},now,true); if(built.source.id!==preview.source_assignment_id || built.targetRegionId!==preview.target_region_id || built.targetPrincipal.person_id!==preview.target_principal_person_id) fail("PERSON_CAMPUS_PREVIEW_STALE");
      if (built.action !== preview.action) fail("PERSON_CAMPUS_PREVIEW_STALE");
      built.resultAssignmentId=preview.result_assignment_id; built.continuationAssignmentId=preview.continuation_assignment_id; built.resultRelationshipId=preview.result_campus_principal_relationship_id; built.continuationRelationshipId=preview.continuation_campus_principal_relationship_id;
      const simulated=await simulateSettlementImpact(client,built,preview.person_id,preview.target_campus_id,preview.effective_from,preview.effective_to,context.personId,now);
      const frozenImpact={...built.impact,financial:{consideredFeeCount:built.fees.length,changedFeeCount:simulated.changedFeeCount,excludedRefundCount:simulated.excludedRefundCount,accountDeltas:simulated.accountDeltas,fees:simulated.frozenFees,organizationImpact:organizationImpact(preview.person_id,built.source,preview.target_campus_id,built.targetRegionId,built.fees)}}; if(hash(frozenImpact)!==preview.base_hash) fail("PERSON_CAMPUS_PREVIEW_STALE");
      await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1,0))", [`person-campus-assignment-version:${preview.person_id}`]);
      const changeId=randomUUID(), version=Number((await client.query<{v:string}>("SELECT COALESCE(max(assignment_version),0)+1::bigint AS v FROM person_campus_assignment_change WHERE person_id=$1::uuid",[preview.person_id])).rows[0]?.v??"1");
      if (built.action === "TRANSFER") { await client.query("UPDATE person_campus_assignment SET valid_to=$2::timestamptz,superseded_by_person_campus_change_id=$3::uuid WHERE id=$1::uuid",[built.source.id,preview.effective_from,changeId]); await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[built.resultAssignmentId,preview.person_id,preview.target_campus_id,built.targetRegionId,preview.effective_from,preview.effective_to,context.personId,now]); if(built.continuationAssignmentId!==null) await client.query("INSERT INTO person_campus_assignment(id,person_id,campus_id,region_id,valid_from,valid_to,created_by,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[built.continuationAssignmentId,built.source.person_id,built.source.campus_id,built.source.region_id,preview.effective_to,built.source.valid_to,context.personId,now]); }
      if(built.sourcePrincipal) await client.query("UPDATE person_relationship SET valid_to=$2::timestamptz WHERE id=$1::uuid",[built.sourcePrincipal.id,preview.effective_from]);
      await client.query("INSERT INTO person_relationship(id,teacher_id,relationship_type,related_person_id,valid_from,valid_to,effective_scope,created_by,created_at,person_campus_change_id) VALUES($1,$2,'CAMPUS_PRINCIPAL',$3,$4,$5,'CAMPUS',$6,$7,$8)",[built.resultRelationshipId,preview.person_id,built.targetPrincipal.person_id,preview.effective_from,preview.effective_to,context.personId,now,changeId]);
      if(built.continuationRelationshipId!==null) await client.query("INSERT INTO person_relationship(id,teacher_id,relationship_type,related_person_id,valid_from,valid_to,effective_scope,created_by,created_at,person_campus_change_id) VALUES($1,$2,'CAMPUS_PRINCIPAL',$3,$4,$5,'CAMPUS',$6,$7,$8)",[built.continuationRelationshipId,preview.person_id,built.continuationPrincipal?.person_id??fail("PERSON_CAMPUS_TARGET_PRINCIPAL_INVALID"),preview.effective_to,built.source.valid_to,context.personId,now,changeId]);
      const effects: {fee:Fee;resultId:string;next: {lines:readonly {key:string;cents:bigint}[];accountByKey:Readonly<Record<string,string>>};context:Json;previous:{lines:{key:string;cents:bigint}[];accountByKey:Record<string,string>};delta:readonly LedgerDelta[]}[]=[]; let excluded=0;
      for(const fee of built.fees){ const refunded=(await client.query("SELECT 1 FROM weekly_fee_refund_effect WHERE weekly_fee_entry_id=$1::uuid",[fee.id])).rows.length>0; if(refunded){excluded++;continue;} if(!fee.snapshot_id||!fee.snapshot_json||!fee.context_json||!fee.policy_version_id||fee.net_monthly_cents===null) fail("PERSON_CAMPUS_SETTLEMENT_DATA_UNAVAILABLE"); const resolved=await resolveSettlementContext(client,fee.id); const next={lines:allocateSettlement(resolved.input),accountByKey:resolved.accountByKey}; const previous=decode(fee.snapshot_json); const delta=allocationDelta(previous.lines,next.lines,previous.accountByKey,next.accountByKey); effects.push({fee,resultId:randomUUID(),next,context:resolved.contextJson as Json,previous,delta}); }
      const deltas=aggregate(effects.flatMap(x=>x.delta)); let runId:string|null=null,eventId:string|null=null;
      // The organisation context is a business fact even when allocation cents
      // happen to be unchanged. Append one snapshot/run for every eligible fee.
      if(effects.length){runId=randomUUID(); if(deltas.length){const posted=await postLedgerEvent({transaction:work=>work(createPostgresLedgerTransaction(client))},{eventKey:`weekly-settlement:person-campus-change:${changeId}`,eventType:"WEEKLY_FEE_SETTLEMENT",payloadHash:hash({changeId,effects:effects.map(x=>x.fee.id)}),deltas},randomUUID); eventId=posted.event.eventId;} const anchor=effects[0]!;await client.query("INSERT INTO settlement_calculation_run(id,request_key,fee_entry_id,fee_version,actor_person_id,status,ledger_event_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[runId,`person-campus-change:${changeId}`,anchor.fee.id,anchor.fee.version,context.personId,eventId?"POSTED":"NO_BALANCE_CHANGE",eventId,now]); for(const effect of effects){await client.query("INSERT INTO weekly_fee_allocation_snapshot(id,run_id,weekly_fee_entry_id,source_weekly_fee_version,policy_version_id,net_monthly_cents,snapshot_json,context_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb,$9)",[effect.resultId,runId,effect.fee.id,effect.fee.version,effect.fee.policy_version_id,effect.fee.net_monthly_cents,stringify({lines:effect.next.lines.map(l=>({key:l.key,cents:l.cents.toString()})),accountByKey:effect.next.accountByKey}),stringify(effect.context),now]);}}
      const before={assignment:fact(built.source),campusPrincipalRelationship:built.sourcePrincipal?relationshipFact(built.sourcePrincipal):null},after={assignment:built.action === "TRANSFER" ? {id:built.resultAssignmentId,personId:preview.person_id,campusId:preview.target_campus_id,regionId:built.targetRegionId,validFrom:preview.effective_from,validTo:preview.effective_to} : fact(built.source),campusPrincipalRelationship:{id:built.resultRelationshipId,relatedPersonId:built.targetPrincipal.person_id}};
      await client.query(`INSERT INTO person_campus_assignment_change(id,preview_id,action,person_id,assignment_version,source_assignment_id,result_assignment_id,continuation_assignment_id,source_campus_principal_relationship_id,result_campus_principal_relationship_id,continuation_campus_principal_relationship_id,target_campus_id,target_region_id,target_principal_person_id,target_principal_role_assignment_id,effective_from,effective_to,reason,idempotency_key,request_hash,base_hash,posting_status,settlement_calculation_run_id,ledger_event_id,considered_fee_count,changed_fee_count,excluded_refund_count,before_json,after_json,published_by_person_id,actor_subject_code,actor_scope_type,published_at,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28::jsonb,$29::jsonb,$30,$31,'GLOBAL',$32,$32)`,[changeId,previewId,built.action,preview.person_id,version,built.source.id,built.resultAssignmentId,built.continuationAssignmentId,built.sourcePrincipal?.id??null,built.resultRelationshipId,built.continuationRelationshipId,preview.target_campus_id,built.targetRegionId,built.targetPrincipal.person_id,built.targetPrincipal.role_assignment_id,preview.effective_from,preview.effective_to,preview.reason,idempotencyKey,hash({previewId,idempotencyKey}),preview.base_hash,eventId?"POSTED":"NO_BALANCE_CHANGE",runId,eventId,built.fees.length,effects.filter(x=>x.delta.length).length,excluded,stringify(before),stringify(after),context.personId,context.subject,now]);
      if(runId) for(const effect of effects) await client.query("INSERT INTO person_campus_assignment_change_effect(change_id,weekly_fee_entry_id,source_weekly_fee_version,teaching_week_id,settlement_month,previous_snapshot_id,result_snapshot_id,settlement_calculation_run_id,delta_json,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10)",[changeId,effect.fee.id,effect.fee.version,effect.fee.teaching_week_id,effect.fee.settlement_month,effect.fee.snapshot_id,effect.resultId,runId,stringify({entries:effect.delta.map(x=>({...x,amountCents:x.amountCents.toString()}))}),now]);
      await client.query("INSERT INTO audit_event(actor_person_id,action_code,subject_type,subject_id,before_json,after_json,reason,created_at) VALUES($1,'PERSON_CAMPUS_ASSIGNMENT_CHANGED','PERSON_CAMPUS_ASSIGNMENT_CHANGE',$2,$3::jsonb,$4::jsonb,$5,$6)",[context.personId,changeId,stringify(before),stringify(after),preview.reason,now]); await client.query("COMMIT"); return {changeId,previewId,assignmentVersion:version,resultAssignmentId:built.resultAssignmentId,resultCampusPrincipalRelationshipId:built.resultRelationshipId,postingStatus:eventId?"POSTED":"NO_BALANCE_CHANGE",consideredFeeCount:built.fees.length,changedFeeCount:effects.filter(x=>x.delta.length).length,excludedRefundCount:excluded,replay:false};
    } catch(error){await client.query("ROLLBACK");throw error;} finally {await client.release();}
  }
}
