import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";
let Panel; let temp;
const flush=()=>act(async()=>{await new Promise(r=>setTimeout(r,0))}); const props=n=>n[Object.keys(n).find(k=>k.startsWith("__reactProps$"))];
const session=(subject="SYSTEM_ADMIN")=>({sessionId:"s",accountId:"a",personId:"admin",roleContexts:[],currentRoleContext:{subject,scope:"GLOBAL",personId:"admin"}});
const directory={planners:[{personId:"planner",nickname:"规划师甲",currentMentorPersonId:null,currentMentorNickname:null,currentRelationshipId:null},{personId:"planner2",nickname:"规划师乙",currentMentorPersonId:"old",currentMentorNickname:"原导师",currentRelationshipId:"rel"}],mentors:[{personId:"mentor",nickname:"新导师"},{personId:"old",nickname:"原导师"}],currentWeeks:[{id:"week",startsOn:"2026-09-21",endsOn:"2026-09-27",settlementMonth:"2026-09-01"},{id:"week2",startsOn:"2026-09-28",endsOn:"2026-10-04",settlementMonth:"2026-10-01"}]};
const preview={previewId:"preview",action:"ADD",plannerPersonId:"planner",plannerNickname:"规划师甲",sourceMentorPersonId:null,sourceMentorNickname:null,newMentorPersonId:"mentor",newMentorNickname:"新导师",effectiveTeachingWeekId:"week",effectiveThroughTeachingWeekId:null,effectiveAt:"2026-09-21T00:00:00.000Z",nextBoundaryAt:null,consideredFeeCount:2,changedFeeCount:1,zeroShareFeeCount:1,excludedRefundCount:0,plannerDeltaCents:"100",sourceMentorDeltaCents:"0",destinationMentorDeltaCents:"100"};
test.before(async()=>{temp=await mkdtemp(resolve(import.meta.dirname,".admin-planning-web-"));const out=resolve(temp,"panel.mjs");await build({entryPoints:[resolve(import.meta.dirname,"../src/admin-planning-mentor-relationship-panel.tsx")],bundle:true,platform:"node",format:"esm",outfile:out,external:["react","react-dom","@teaching-research-alliance/client"]});Panel=(await import(out)).AdminPlanningMentorRelationshipPanel});
test.after(async()=>{await rm(temp,{recursive:true,force:true})});
async function mount(overrides={}){const dom=new JSDOM("<div id='host'></div>",{url:"http://localhost"});Object.assign(globalThis,{window:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});const host=document.querySelector("#host"),root=createRoot(host),calls=[];const client={hasRoleContext:true,listAdminPlanningMentorRelationshipCandidates:async()=>directory,previewAdminPlanningMentorRelationshipChange:async d=>{calls.push(d);return {...preview,action:d.action,plannerPersonId:d.plannerPersonId,newMentorPersonId:d.newMentorPersonId}},createAdminPlanningMentorRelationshipChangeSubmission:id=>({draft:{previewId:id},idempotencyKey:"key"}),publishAdminPlanningMentorRelationshipChange:async()=>({replay:false}),...overrides};await act(async()=>root.render(React.createElement(Panel,{client,session:session(),sessionKey:"one",onInvalidated:()=>calls.push("invalid")})));await flush();const input=async(label,value)=>{const n=host.querySelector(`[aria-label="${label}"]`);await act(async()=>props(n).onChange({target:{value}}))};return{host,calls,input,close:async()=>{await act(async()=>root.unmount());dom.window.close()}}}
async function fill(ui, action, planner){await ui.input("纠正动作",action);await ui.input("规划师",planner);if(action!=="REMOVE")await ui.input("规划导师",action==="REPLACE"?"mentor":"mentor");await ui.input("生效普通周","week");await ui.input("变更原因","普通周关系纠正")}
for (const [action, planner] of [["ADD","planner"],["REPLACE","planner2"],["REMOVE","planner2"]]) test(`管理员${action}动作可预览`,async()=>{const ui=await mount();try{assert.match(ui.host.textContent,/特殊期前结束/);await fill(ui,action,planner);await act(async()=>[...ui.host.querySelectorAll("button")].find(n=>n.textContent.includes("生成规划导师纠正预览")).click());await flush();assert.match(ui.host.textContent,/规划导师/);assert.equal(ui.calls[0].action,action);assert.equal(ui.calls[0].newMentorPersonId,action==="REMOVE"?null:"mentor")}finally{await ui.close()}});
test("结束普通周包含开始周并在开始周后移时清空",async()=>{const ui=await mount();try{await ui.input("生效普通周","week");const through=ui.host.querySelector("select[aria-label='结束普通周']");assert.match(through.textContent,/2026-09-21/);await act(async()=>props(through).onChange({target:{value:"week"}}));await ui.input("生效普通周","week2");assert.equal(through.value,"")}finally{await ui.close()}});
test("未知发布复用原提交，身份错误清理旧状态",async()=>{let attempts=0;const ui=await mount({publishAdminPlanningMentorRelationshipChange:async command=>{assert.equal(command.idempotencyKey,"key");if(++attempts===1)throw new Error("offline");return {replay:true}}});try{await fill(ui,"ADD","planner");await act(async()=>[...ui.host.querySelectorAll("button")].find(n=>n.textContent.includes("生成规划导师纠正预览")).click());await flush();await act(async()=>[...ui.host.querySelectorAll("button")].find(n=>n.textContent.includes("确认发布规划导师纠正")).click());await flush();assert.match(ui.host.textContent,/结果未确认/);await act(async()=>ui.host.querySelector("[data-admin-planning-mentor-action='retry-publish']").click());await flush();assert.equal(attempts,2);assert.match(ui.host.textContent,/已确认/)}finally{await ui.close()}const denied=await mount({listAdminPlanningMentorRelationshipCandidates:async()=>{throw new ApiClientError(403,"FORBIDDEN_SCOPE")}});try{assert.match(denied.host.textContent,/身份已失效/)}finally{await denied.close()}});
