import assert from "node:assert/strict";
import test from "node:test";
import { build } from "esbuild";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";

let Panel;
let temp;
test.before(async () => {
  temp = await mkdtemp(resolve(import.meta.dirname, ".benefit-plan-panel-"));
  const out = resolve(temp, "panel.mjs");
  await build({ entryPoints: [resolve(import.meta.dirname, "../src/benefit-plan-panel.tsx")], bundle: true, platform: "node", format: "esm", outfile: out, external: ["react", "react-dom", "@teaching-research-alliance/client"] });
  Panel = (await import(out)).BenefitPlanPanel;
});
test.after(async () => { if (temp) await rm(temp, { recursive: true, force: true }); });

const id = "00000000-0000-4000-8000-000000000001";
const person = "00000000-0000-4000-8000-000000000002";
const session = (subject, scope = "GLOBAL", regionId) => ({ sessionId: `s-${subject}`, currentRoleContext: { subject, scope, personId: id, ...(regionId === undefined ? {} : { regionId }) }, roleContexts: [] });
const roster = (name = "老师一", version = 1) => ({ benefitMonth: "2026-09-01", items: [{ benefitKind: "SOCIAL_INSURANCE", beneficiaryPersonId: person, beneficiaryDisplayName: name, benefitMonth: "2026-09-01", planVersions: [{ id: "00000000-0000-4000-8000-000000000003", version, executionDay: 5, amountCents: "1000", sourceFund: { id: "00000000-0000-4000-8000-000000000004", code: "FIN", displayName: "总部账户" }, active: true, reason: "旧计划", changedAt: "2026-09-01T00:00:00Z", changedByPersonId: id }], currentPlan: { id: "00000000-0000-4000-8000-000000000003", version, executionDay: 5, amountCents: "1000", sourceFund: { id: "00000000-0000-4000-8000-000000000004", code: "FIN", displayName: "总部账户" }, active: true, reason: "旧计划", changedAt: "2026-09-01T00:00:00Z", changedByPersonId: id }, todo: null, execution: null, status: "SCHEDULED" }] });
const flush = () => new Promise(resolve => setTimeout(resolve, 0));
const propsOf = (node) => { const key = Object.keys(node).find(name => name.startsWith("__reactProps")); return key ? node[key] : {}; };
const change = async (host, label, value) => { const node = [...host.querySelectorAll("input,select,textarea")].find(item => item.getAttribute("aria-label") === label); assert.ok(node, label); await act(async () => propsOf(node).onChange?.({ target: { value, checked: value } })); };
async function mount(subject = "SYSTEM_ADMIN", overrides = {}, scope = "GLOBAL", regionId) {
  const dom = new JSDOM("<div id='app'></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
  const host = document.querySelector("#app"); const root = createRoot(host); const calls = []; const saved = []; const invalidated = []; const pending = [];
  const client = { hasRoleContext: true, listManagedCashWageTeachers: async () => ({ items: [{ id: person, nickname: "老师一" }] }), listBenefitSourceFunds: async () => ({ items: [{ fundId: "00000000-0000-4000-8000-000000000004", code: "FIN", displayName: "总部账户" }] }), listManagedBenefitRoster: async () => roster(), createBenefitPlanSubmission: draft => ({ draft, idempotencyKey: `key-${calls.length + 1}` }), setBenefitPlan: async submission => { calls.push(submission); }, ...overrides };
  let currentSession = session(subject, scope, regionId); let key = "one";
  const render = async () => { await act(async () => root.render(React.createElement(Panel, { client, session: currentSession, sessionKey: key, onSaved: () => saved.push(true), onInvalidated: () => invalidated.push(true), onUnconfirmedChange: value => pending.push(value) }))); await flush(); };
  await render(); return { dom, root, host, client, calls, saved, invalidated, pending, render, setSession: (next, nextKey = "two", nextScope = "GLOBAL", nextRegionId) => { currentSession = session(next, nextScope, nextRegionId); key = nextKey; }, close: async () => { await act(async () => root.unmount()); dom.window.close(); } };
}
const fill = async (v) => { await change(v.host, "受益人", person); await change(v.host, "福利月份", "2026-09"); await change(v.host, "执行日", "5"); await change(v.host, "金额（欢乐豆）", "12.34"); await change(v.host, "扣费账户", "00000000-0000-4000-8000-000000000004"); await change(v.host, "理由", "本月福利计划"); };
const saveButton = (v, text = "保存计划") => [...v.host.querySelectorAll("button")].find(button => button.textContent === text);

test("GLOBAL HQ/admin/owner can read and save a plan", async () => { for (const subject of ["HEADQUARTERS_FINANCE", "SYSTEM_ADMIN", "SYSTEM_OWNER"]) { const v = await mount(subject); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.calls[0].draft.amountCents, "1234"); assert.equal(v.calls[0].draft.benefitMonth, "2026-09-01"); assert.equal(v.saved.length, 1); assert.match(v.host.textContent, /保存计划，不扣豆/); } finally { await v.close(); } } });
test("scoped and unrelated roles do not read or write", async () => { for (const [subject, scope, region] of [["TEACHING_TEACHER", "GLOBAL"], ["REGIONAL_FINANCE", "REGION", id], ["SYSTEM_ADMIN", "CAMPUS", id]]) { let reads = 0; const v = await mount(subject, { listManagedCashWageTeachers: async () => { reads++; return { items: [] }; } }, scope, region); try { assert.equal(reads, 0); assert.match(v.host.textContent, /没有维护总部/); } finally { await v.close(); } } });
test("unknown result preserves the original command for explicit retry", async () => { let writes = 0; const v = await mount("SYSTEM_ADMIN", { setBenefitPlan: async submission => { v.calls.push(submission); writes++; if (writes === 1) throw new Error("timeout"); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.match(v.host.textContent, /结果未确认/); await act(async () => [...v.host.querySelectorAll("button")].find(button => button.textContent === "使用原提交重试").click()); await flush(); assert.equal(v.calls.length, 2); assert.equal(v.calls[0].idempotencyKey, v.calls[1].idempotencyKey); } finally { await v.close(); } });
test("400 releases the draft and creates a new key", async () => { let writes = 0; const v = await mount("SYSTEM_ADMIN", { setBenefitPlan: async submission => { v.calls.push(submission); writes++; if (writes === 1) throw new ApiClientError(400, "INVALID_INPUT"); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); await change(v.host, "理由", "修正后的理由"); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.calls.length, 2); assert.notEqual(v.calls[0].idempotencyKey, v.calls[1].idempotencyKey); } finally { await v.close(); } });
test("409 refreshes latest roster and requires manual review", async () => { let reads = 0; const v = await mount("SYSTEM_OWNER", { listManagedBenefitRoster: async () => { reads++; return roster(reads > 1 ? "最新老师" : "老师一", reads > 1 ? 2 : 1); }, setBenefitPlan: async () => { throw new ApiClientError(409, "BENEFIT_PLAN_CONFLICT"); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(reads, 2); assert.match(v.host.textContent, /最新老师|人工核对/); assert.equal(saveButton(v)?.disabled, true); } finally { await v.close(); } });
test("late directory response cannot cross an identity generation", async () => { let resolveOld; let resolveNew; let read = 0; const old = new Promise(resolve => { resolveOld = resolve; }); const fresh = new Promise(resolve => { resolveNew = resolve; }); const v = await mount("SYSTEM_ADMIN", { listManagedCashWageTeachers: () => read++ === 0 ? old : fresh }); try { v.setSession("SYSTEM_OWNER"); await v.render(); resolveOld({ items: [{ id: person, nickname: "旧身份" }] }); await act(async () => { await flush(); }); assert.equal(v.host.textContent.includes("旧身份"), false); resolveNew({ items: [{ id: person, nickname: "新身份" }] }); await act(async () => { await flush(); }); assert.equal(v.host.textContent.includes("新身份"), true); } finally { await v.close(); } });
test("401/403 invalidate and clear", async () => { for (const status of [401, 403]) { const v = await mount("SYSTEM_ADMIN", { listBenefitSourceFunds: async () => { throw new ApiClientError(status, "AUTH"); } }); try { await flush(); assert.equal(v.invalidated.length, 1); assert.match(v.host.textContent, /身份已失效/); } finally { await v.close(); } } });
test("same-plan double click performs one write", async () => { let resolveWrite; const write = new Promise(resolve => { resolveWrite = resolve; }); const v = await mount("SYSTEM_ADMIN", { setBenefitPlan: async submission => { v.calls.push(submission); return write; } }); try { await fill(v); await act(async () => { const button = saveButton(v); button.click(); button.click(); }); await flush(); assert.equal(v.calls.length, 1); resolveWrite({}); await act(async () => { await flush(); }); } finally { await v.close(); } });
test("409 refresh failure keeps parent lock and offers retry", async () => { let refresh = 0; const v = await mount("SYSTEM_ADMIN", { setBenefitPlan: async () => { throw new ApiClientError(409, "CONFLICT"); }, listManagedBenefitRoster: async () => { refresh++; if (refresh > 1) throw new Error("refresh failed"); return roster(); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.pending.at(-1), true); assert.ok([...v.host.querySelectorAll("button")].some(button => button.textContent === "重试读取最新计划")); assert.equal([...v.host.querySelectorAll("button")].find(button => button.textContent === "已核对最新版本"), undefined); } finally { await v.close(); } });
test("same session key full context and late people/fund responses stay isolated", async () => { let peopleResolve; let fundResolve; let calls = 0; const peopleOld = new Promise(resolve => { peopleResolve = resolve; }); const fundOld = new Promise(resolve => { fundResolve = resolve; }); const v = await mount("SYSTEM_ADMIN", { listManagedCashWageTeachers: () => calls++ === 0 ? peopleOld : Promise.resolve({ items: [{ id: person, nickname: "新身份老师" }] }), listBenefitSourceFunds: () => calls++ === 1 ? fundOld : Promise.resolve({ items: [{ fundId: "new-fund", code: "NEW", displayName: "新账户" }] }) }); try { v.setSession("SYSTEM_OWNER", "one", "GLOBAL", undefined); await v.render(); peopleResolve({ items: [{ id: person, nickname: "旧身份老师" }] }); fundResolve({ items: [{ fundId: "old-fund", code: "OLD", displayName: "旧账户" }] }); await act(async () => { await flush(); }); assert.equal(v.host.textContent.includes("旧身份老师"), false); assert.equal(v.host.textContent.includes("旧账户"), false); assert.equal(v.host.textContent.includes("新身份老师"), true); assert.equal(v.host.textContent.includes("新账户"), true); } finally { await v.close(); } });
test("empty people or funds show retry and disable saving", async () => { for (const field of ["people", "funds"]) { let reads = 0; const v = await mount("SYSTEM_ADMIN", field === "people" ? { listManagedCashWageTeachers: async () => { reads++; return { items: [] }; } } : { listBenefitSourceFunds: async () => { reads++; return { items: [] }; } }); try { assert.ok([...v.host.querySelectorAll("button")].some(button => button.textContent === "重试读取目录")); assert.equal(saveButton(v)?.disabled, true); } finally { await v.close(); } } });
test("write 401/403 invalidate and clear", async () => { for (const status of [401, 403]) { const v = await mount("SYSTEM_ADMIN", { setBenefitPlan: async () => { throw new ApiClientError(status, "AUTH"); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.invalidated.length, 1); assert.match(v.host.textContent, /身份已失效/); } finally { await v.close(); } } });
test("409 does not present the old roster before refresh evidence is ready", async () => { let resolveRefresh; let reads = 0; const pending = new Promise(resolve => { resolveRefresh = resolve; }); const v = await mount("SYSTEM_ADMIN", { listManagedBenefitRoster: async () => { reads++; return reads === 1 ? roster("旧计划老师", 1) : pending; }, setBenefitPlan: async () => { throw new ApiClientError(409, "CONFLICT"); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.host.textContent.includes("旧计划老师"), false); assert.match(v.host.textContent, /正在读取最新福利计划/); resolveRefresh(roster("最新计划老师", 2)); await act(async () => { await flush(); }); assert.match(v.host.textContent, /最新计划老师/); } finally { await v.close(); } });
test("successful save keeps saved fact when roster refresh fails", async () => { let reads = 0; const v = await mount("SYSTEM_ADMIN", { listManagedBenefitRoster: async () => { reads++; if (reads > 1) throw new Error("refresh failed"); return roster(); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.saved.length, 1); assert.match(v.host.textContent, /计划已保存，但最新名单刷新失败/); } finally { await v.close(); } });
test("successful save refresh retry updates roster without resubmitting", async () => { let reads = 0; const v = await mount("SYSTEM_ADMIN", { listManagedBenefitRoster: async () => { reads++; if (reads === 2) throw new Error("refresh failed"); return roster(reads > 2 ? "刷新后的名单" : "原名单", reads > 2 ? 3 : 1); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); assert.equal(v.calls.length, 1); assert.equal(v.saved.length, 1); const retry = [...v.host.querySelectorAll("button")].find(button => button.textContent === "重试读取最新计划/名单"); assert.ok(retry); await act(async () => { retry.click(); retry.click(); }); await flush(); assert.equal(v.calls.length, 1); assert.equal(v.saved.length, 1); assert.match(v.host.textContent, /刷新后的名单/); } finally { await v.close(); } });
test("successful save refresh retry 401/403 invalidates without resubmitting", async () => { for (const status of [401, 403]) { let reads = 0; const v = await mount("SYSTEM_ADMIN", { listManagedBenefitRoster: async () => { reads++; if (reads === 2) throw new Error("refresh failed"); if (reads > 2) throw new ApiClientError(status, "AUTH"); return roster(); } }); try { await fill(v); await act(async () => saveButton(v).click()); await flush(); const retry = [...v.host.querySelectorAll("button")].find(button => button.textContent === "重试读取最新计划/名单"); assert.ok(retry); await act(async () => retry.click()); await flush(); assert.equal(v.calls.length, 1); assert.equal(v.saved.length, 1); assert.equal(v.invalidated.length, 1); assert.match(v.host.textContent, /身份已失效/); } finally { await v.close(); } } });
test("post-save roster refresh synchronously blocks stale and rendered form resubmits", async () => { let reads = 0; let resolveWrite; let resolveRefresh; const write = new Promise(resolve => { resolveWrite = resolve; }); const refresh = new Promise(resolve => { resolveRefresh = resolve; }); let v; v = await mount("SYSTEM_ADMIN", { setBenefitPlan: submission => { v.calls.push(submission); return write; }, listManagedBenefitRoster: async () => ++reads === 1 ? roster("初始名单", 1) : refresh }); try { await fill(v); const staleSubmit = propsOf(v.host.querySelector("form")).onSubmit; await act(async () => saveButton(v).click()); assert.equal(v.calls.length, 1); await act(async () => { resolveWrite({}); await Promise.resolve(); staleSubmit({ preventDefault() {} }); await Promise.resolve(); }); assert.equal(v.saved.length, 1); assert.equal(v.calls.length, 1); assert.equal(saveButton(v).disabled, true); await act(async () => { saveButton(v).click(); saveButton(v).click(); }); assert.equal(v.calls.length, 1); resolveRefresh(roster("保存后名单", 2)); await act(async () => { await flush(); }); assert.equal(saveButton(v).disabled, false); assert.match(v.host.textContent, /保存后名单/); } finally { await v.close(); } });
