import assert from "node:assert/strict";
import test from "node:test";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";
import { BonusProjectPanel } from "../dist/bonus-project-panel.js";

const id = "00000000-0000-4000-8000-000000000001";
const session = (subject, scope = "GLOBAL", regionId) => ({ sessionId: `s-${subject}`, currentRoleContext: { subject, scope, personId: id, ...(regionId === undefined ? {} : { regionId }) }, roleContexts: [] });
const catalog = (name = "项目一", version = 1) => ({ projects: Array.from({ length: 10 }, (_, i) => ({ projectNo: i + 1, nameVersionId: `00000000-0000-4000-8000-${String(i + 2).padStart(12, "0")}`, nameVersion: version, displayName: i === 0 ? name : `项目${i + 1}`, changedByPersonId: null, changeSource: "MIGRATION_DEFAULT", changedAt: "2026-09-23T00:00:00.000Z" })) });
const flush = () => new Promise(resolve => setTimeout(resolve, 0));
async function mount(subject, overrides = {}, scope = "GLOBAL", regionId) {
  const dom = new JSDOM('<div id="app"></div>', { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true });
  const host = document.querySelector("#app"); const root = createRoot(host); const calls = []; const invalidated = []; const saved = []; const pending = [];
  const client = { listBonusProjects: async () => catalog(), createBonusProjectRenameSubmission: draft => ({ draft, idempotencyKey: `key-${calls.length + 1}` }), renameBonusProject: async submission => { calls.push(submission); }, ...overrides };
  let currentSession = session(subject, scope, regionId); let key = "one";
  const render = async () => { await act(async () => root.render(React.createElement(BonusProjectPanel, { client, session: currentSession, sessionKey: key, onInvalidated: () => invalidated.push(true), onSaved: () => saved.push(true), onUnconfirmedChange: value => pending.push(value) }))); await flush(); };
  await render(); return { dom, root, host, client, calls, invalidated, saved, pending, render, setSession: (next, nextKey = "two", nextScope = "GLOBAL", nextRegionId) => { currentSession = session(next, nextScope, nextRegionId); key = nextKey; }, close: async () => { await act(async () => root.unmount()); dom.window.close(); } };
}
const input = async (host, label, value) => { const el = [...host.querySelectorAll("input,textarea")].find(node => node.getAttribute("aria-label") === label); assert.ok(el); const key = Object.keys(el).find(name => name.startsWith("__reactProps")); const props = key ? el[key] : null; await act(async () => { props?.onChange?.({ target: { value } }); }); };

test("GLOBAL admin can rename with expectedVersion", async () => { const v = await mount("SYSTEM_ADMIN"); try { await input(v.host, "项目1新名称", "新名称"); await input(v.host, "项目1变更理由", "修正展示"); await act(async () => v.host.querySelector("button").click()); await flush(); assert.equal(v.calls.length, 1); assert.equal(v.calls[0].draft.expectedVersion, 1); assert.equal(v.calls[0].draft.displayName, "新名称"); assert.equal(v.pending.at(-1), false); } finally { await v.close(); } });
test("HQ is read-only", async () => { const v = await mount("HEADQUARTERS_FINANCE"); try { assert.match(v.host.textContent, /项目一/); assert.equal(v.host.querySelectorAll("button").length, 0); assert.equal(v.host.querySelectorAll("textarea").length, 0); } finally { await v.close(); } });
test("409 reloads latest catalog, requires review, then creates a new versioned command", async () => { let reads = 0; let writes = 0; const v = await mount("SYSTEM_OWNER", { listBonusProjects: async () => { reads += 1; return catalog(reads === 1 ? "项目一" : "最新名称", reads === 1 ? 1 : 2); }, renameBonusProject: async submission => { v.calls.push(submission); writes += 1; if (writes === 1) throw new ApiClientError(409, "BONUS_PROJECT_VERSION_CONFLICT"); } }); try { await input(v.host, "项目1新名称", "尝试"); await input(v.host, "项目1变更理由", "理由"); await act(async () => [...v.host.querySelectorAll("button")].find(b => b.textContent === "保存名称").click()); await flush(); assert.equal(reads, 2); assert.match(v.host.textContent, /版本 2/); assert.equal(v.host.querySelector("article button").disabled, true); await act(async () => [...v.host.querySelectorAll("button")].find(b => b.textContent === "已核对最新版本").click()); await act(async () => [...v.host.querySelectorAll("button")].find(b => b.textContent === "保存名称").click()); await flush(); assert.equal(v.calls.length, 2); assert.equal(v.calls[1].draft.expectedVersion, 2); assert.notEqual(v.calls[1].idempotencyKey, v.calls[0].idempotencyKey); } finally { await v.close(); } });
test("unknown keeps the original command and allows explicit retry", async () => { let count = 0; const v = await mount("SYSTEM_ADMIN", { renameBonusProject: async submission => { v?.calls.push(submission); count += 1; if (count === 1) throw new Error("timeout"); } }); try { await input(v.host, "项目1新名称", "新名称"); await input(v.host, "项目1变更理由", "理由"); await act(async () => [...v.host.querySelectorAll("button")].find(b => b.textContent === "保存名称").click()); await flush(); assert.equal(v.pending.includes(true), true); assert.match(v.host.textContent, /结果未确认/); const retry = [...v.host.querySelectorAll("button")].find(b => b.textContent === "使用原提交重试"); assert.ok(retry); await act(async () => retry.click()); await flush(); assert.equal(v.calls.at(-1).idempotencyKey, v.calls[0].idempotencyKey); } finally { await v.close(); } });
test("late catalog response cannot cross identity", async () => { let resolveOld; let resolveNew; const old = new Promise(resolve => { resolveOld = resolve; }); const fresh = new Promise(resolve => { resolveNew = resolve; }); let request = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: () => request++ === 0 ? old : fresh }); try { v.setSession("SYSTEM_OWNER"); await v.render(); await act(async () => { resolveOld({ projects: [{ ...catalog().projects[0], displayName: "旧身份" }] }); await flush(); }); assert.equal(v.host.textContent.includes("旧身份"), false); await act(async () => { resolveNew(catalog("新身份")); await flush(); }); assert.equal(v.host.textContent.includes("新身份"), true); } finally { await v.close(); } });
test("401 and 403 invalidate and clear", async () => { for (const status of [401, 403]) { const v = await mount("SYSTEM_ADMIN", { listBonusProjects: async () => { throw new ApiClientError(status, "AUTH"); } }); try { await flush(); assert.equal(v.invalidated.length, 1); assert.match(v.host.textContent, /身份已失效/); } finally { await v.close(); } } });
test("400 unlocks the project and creates a fresh command", async () => { let writes = 0; const v = await mount("SYSTEM_ADMIN", { renameBonusProject: async submission => { v.calls.push(submission); writes += 1; if (writes === 1) throw new ApiClientError(400, "INVALID_INPUT"); } }); try { await input(v.host, "项目1新名称", "第一次"); await input(v.host, "项目1变更理由", "理由"); await act(async () => v.host.querySelector("button").click()); await flush(); await input(v.host, "项目1新名称", "第二次"); await act(async () => v.host.querySelector("button").click()); await flush(); assert.equal(v.calls.length, 2); assert.notEqual(v.calls[0].idempotencyKey, v.calls[1].idempotencyKey); } finally { await v.close(); } });
test("late rename success after identity change has no save or reload", async () => { let resolveWrite; const write = new Promise(resolve => { resolveWrite = resolve; }); let reads = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: async () => { reads += 1; return catalog(); }, renameBonusProject: () => write }); try { await input(v.host, "项目1新名称", "在途"); await input(v.host, "项目1变更理由", "理由"); await act(async () => v.host.querySelector("button").click()); await flush(); const before = reads; v.setSession("SYSTEM_OWNER"); await v.render(); resolveWrite({}); await act(async () => { await flush(); }); assert.equal(v.saved.length, 0); assert.equal(reads, before + 1); } finally { await v.close(); } });
test("single write lock prevents another project from editing or submitting until owner retry succeeds", async () => { let writes = 0; const v = await mount("SYSTEM_ADMIN", { renameBonusProject: async submission => { v.calls.push(submission); writes += 1; if (writes === 1) throw new Error("timeout"); } }); try { await input(v.host, "项目1新名称", "项目一改名"); await input(v.host, "项目1变更理由", "理由"); await act(async () => [...v.host.querySelectorAll("button")].find(b => b.textContent === "保存名称").click()); await flush(); const otherName = v.host.querySelector('[aria-label="项目2新名称"]'); assert.equal(otherName.disabled, true); const otherButton = [...v.host.querySelectorAll("article")][1].querySelector("button"); assert.equal(otherButton.disabled, true); await input(v.host, "项目2新名称", "不应生效"); assert.equal(v.calls.length, 1); const retry = [...v.host.querySelectorAll("button")].find(b => b.textContent === "使用原提交重试"); await act(async () => retry.click()); await flush(); assert.equal(v.calls.length, 2); assert.equal(v.calls[1].idempotencyKey, v.calls[0].idempotencyKey); assert.equal(v.host.querySelector('[aria-label="项目2新名称"]').disabled, false); } finally { await v.close(); } });
test("same project double click starts at most one rename", async () => { let resolve; const pending = new Promise(r => { resolve = r; }); const v = await mount("SYSTEM_ADMIN", { renameBonusProject: async submission => { v.calls.push(submission); return pending; } }); try { await input(v.host, "项目1新名称", "双击"); await input(v.host, "项目1变更理由", "理由"); await act(async () => { const button = [...v.host.querySelectorAll("button")].find(b => b.textContent === "保存名称"); button.click(); button.click(); }); await flush(); assert.equal(v.calls.length, 1); resolve({}); await act(async () => { await flush(); }); } finally { await v.close(); } });
test("scoped admin is read-only and does not read the catalog", async () => { let reads = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: async () => { reads += 1; return catalog(); } }, "REGION", "00000000-0000-4000-8000-000000000099"); try { assert.equal(reads, 0); assert.match(v.host.textContent, /没有查看总部/); assert.equal(v.host.querySelectorAll("input,textarea,button").length, 0); } finally { await v.close(); } });
test("same sessionKey role change invalidates a late admin catalog for HQ", async () => { let resolveOld; const old = new Promise(resolve => { resolveOld = resolve; }); let reads = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: () => reads++ === 0 ? old : Promise.resolve(catalog("HQ目录")) }); try { v.setSession("HEADQUARTERS_FINANCE", "one"); await v.render(); resolveOld(catalog("旧ADMIN目录")); await act(async () => { await flush(); }); assert.equal(v.host.textContent.includes("旧ADMIN目录"), false); assert.match(v.host.textContent, /HQ目录/); assert.equal(v.host.querySelectorAll("input,textarea,button").length, 0); } finally { await v.close(); } });
test("same sessionKey role change isolates a late admin rename from HQ", async () => { let resolveWrite; const write = new Promise(resolve => { resolveWrite = resolve; }); let reads = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: async () => { reads += 1; return catalog(); }, renameBonusProject: () => write }); try { await input(v.host, "项目1新名称", "旧ADMIN改名"); await input(v.host, "项目1变更理由", "理由"); await act(async () => v.host.querySelector("button").click()); await flush(); v.setSession("HEADQUARTERS_FINANCE", "one"); await v.render(); const before = reads; resolveWrite({}); await act(async () => { await flush(); }); assert.equal(v.saved.length, 0); assert.equal(reads, before); assert.equal(v.host.querySelectorAll("input,textarea,button").length, 0); } finally { await v.close(); } });
test("same-context replacement session object does not cancel an in-flight rename", async () => { let resolveWrite; const write = new Promise(resolve => { resolveWrite = resolve; }); let reads = 0; const v = await mount("SYSTEM_ADMIN", { listBonusProjects: async () => { reads += 1; return catalog(); }, renameBonusProject: () => write }); try { await input(v.host, "项目1新名称", "同身份改名"); await input(v.host, "项目1变更理由", "理由"); await act(async () => v.host.querySelector("button").click()); await flush(); v.setSession("SYSTEM_ADMIN", "one"); await v.render(); resolveWrite({}); await act(async () => { await flush(); }); assert.equal(v.saved.length, 1); assert.equal(reads, 2); } finally { await v.close(); } });
