import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";

let Panel; let temp;
const flush = () => act(async () => { await new Promise(resolvePromise => setTimeout(resolvePromise, 0)); });
const props = node => node[Object.keys(node).find(key => key.startsWith("__reactProps$"))];
const session = (subject = "SYSTEM_ADMIN", patch = {}) => ({ sessionId: "s", accountId: "a", personId: "admin", roleContexts: [], currentRoleContext: { subject, scope: "GLOBAL", personId: "admin", ...patch } });
const directory = { campuses: [{ campusId: "campus-a", campusName: "A校区", currentRegionId: "region-a", currentRegionName: "甲区" }], regions: [{ regionId: "region-a", regionName: "甲区" }, { regionId: "region-b", regionName: "乙区" }] };
const preview = { previewId: "preview", campusId: "campus-a", sourceRegionId: "region-a", targetRegionId: "region-b", effectiveFrom: "2026-09-24T01:00:00.000Z", effectiveTo: null, affectedPersonCount: 2, affectedAssignmentCount: 3, consideredFeeCount: 4, changedFeeCount: 2, excludedRefundCount: 1, organizationImpact: { sourceRegionId: "region-a", targetRegionId: "region-b", recordedGrossRevenueCents: "20000", refundedGrossRevenueCents: "5000", effectiveGrossRevenueCents: "15000", campusManagementFeeCents: "3000" }, accountDeltas: [{ accountCode: "REGION_A", categoryKey: "settlement", amountCents: "-100" }, { accountCode: "REGION_B", categoryKey: "settlement", amountCents: "100" }] };
test.before(async () => { temp = await mkdtemp(resolve(import.meta.dirname, ".campus-region-web-")); const out = resolve(temp, "panel.mjs"); await build({ entryPoints: [resolve(import.meta.dirname, "../src/campus-region-assignment-panel.tsx")], bundle: true, platform: "node", format: "esm", outfile: out, external: ["react", "react-dom", "@teaching-research-alliance/client"] }); Panel = (await import(out)).CampusRegionAssignmentPanel; });
test.after(async () => { await rm(temp, { recursive: true, force: true }); });
async function mount(overrides = {}) { const dom = new JSDOM("<div id='host'></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, IS_REACT_ACT_ENVIRONMENT: true }); const host = document.querySelector("#host"), root = createRoot(host), calls = []; const client = { hasRoleContext: true, listCampusRegionAssignmentCandidates: async () => directory, previewCampusRegionAssignmentChange: async draft => { calls.push(draft); return preview; }, createCampusRegionAssignmentChangeSubmission: previewId => ({ draft: { previewId }, idempotencyKey: "stable" }), publishCampusRegionAssignmentChange: async () => ({ replay: false }), ...overrides }; await act(async () => root.render(React.createElement(Panel, { client, session: session(), sessionKey: "one", onInvalidated: () => calls.push("invalid") }))); await flush(); const input = async (label, value) => { const node = host.querySelector(`[aria-label="${label}"]`); await act(async () => props(node).onChange({ target: { value } })); }; const click = async text => { await act(async () => [...host.querySelectorAll("button")].find(node => node.textContent.includes(text)).click()); await flush(); }; return { host, calls, input, click, close: async () => { await act(async () => root.unmount()); dom.window.close(); } }; }
async function fill(ui) { await ui.input("校区", "campus-a"); await ui.input("目标分区", "region-b"); await ui.input("生效时间", "2026-09-24T09:00"); await ui.input("变更原因", "分区重组"); }
test("管理员以北京时间生成预览，显示人员、费用、组织归属和保持不变的关系", async () => { const ui = await mount(); try { await fill(ui); await ui.click("生成分区调整预览"); assert.equal(ui.calls[0].effectiveFrom, "2026-09-24T01:00:00.000Z"); assert.match(ui.host.textContent, /受影响人员：2 人；人员归属记录：3 条/); assert.match(ui.host.textContent, /考虑 4 笔，需重算 2 笔，退款排除 1 笔/); assert.match(ui.host.textContent, /有效营收 150\.00/); assert.match(ui.host.textContent, /校区不变；校长、组长、教学导师、规划导师和场地不变/); } finally { await ui.close(); } });
test("未来生效时段由服务端判定原分区，结束时间必须晚于生效时间", async () => { const ui = await mount(); try { await ui.input("校区", "campus-a"); await ui.input("目标分区", "region-a"); await ui.input("生效时间", "2026-09-24T09:00"); await ui.input("变更原因", "分区重组"); await ui.click("生成分区调整预览"); assert.equal(ui.calls[0].targetRegionId, "region-a"); await ui.input("目标分区", "region-b"); await ui.input("结束时间", "2026-09-24T08:00"); await ui.click("生成分区调整预览"); assert.match(ui.host.textContent, /结束时间必须晚于生效时间/); assert.equal(ui.calls.length, 1); } finally { await ui.close(); } });
test("预览范围和结算资料错误提供可操作提示", async () => { const ui = await mount({ previewCampusRegionAssignmentChange: async () => { throw new ApiClientError(409, "CAMPUS_REGION_SETTLEMENT_DATA_UNAVAILABLE"); } }); try { await fill(ui); await ui.click("生成分区调整预览"); assert.match(ui.host.textContent, /缺少可追溯的结算快照/); } finally { await ui.close(); } });
test("未知发布结果保留原提交并允许安全重试", async () => { let attempts = 0; const ui = await mount({ publishCampusRegionAssignmentChange: async command => { attempts += 1; if (attempts === 1) throw new Error("network"); assert.equal(command.idempotencyKey, "stable"); return { replay: true }; } }); try { await fill(ui); await ui.click("生成分区调整预览"); await ui.click("确认发布分区调整"); assert.match(ui.host.textContent, /发布结果未确认/); await act(async () => ui.host.querySelector('[data-campus-region-action="retry-publish"]').click()); await flush(); assert.equal(attempts, 2); assert.match(ui.host.textContent, /未重复发布/); } finally { await ui.close(); } });
