import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "../../../packages/client/dist/index.js";

const dirs = []; const later = () => { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; };
const referral = (status = "ACCEPTED", id = "referral-a") => ({ referralId: id, studentDisplayName: "学生甲", courseContextId: "数学", receiverPersonId: "receiver", receiverNickname: "接收老师", referrerPersonId: "referrer", referrerNickname: "推荐老师", referralStatus: status, version: 3, submittedAt: "2026-09-24T00:00:00Z" });
const flush = () => act(async () => { await new Promise(done => setTimeout(done, 0)); });
async function Panel() { const dir = await mkdtemp(resolve(import.meta.dirname, ".managed-referral-")); dirs.push(dir); const out = resolve(dir, "panel.mjs"); await build({ entryPoints: [resolve(import.meta.dirname, "../src/managed-referral-completion-panel.tsx")], bundle: true, format: "esm", platform: "node", outfile: out, external: ["react", "@teaching-research-alliance/client"] }); return (await import(out)).ManagedReferralCompletionPanel; }
async function mount(client, active = true) { const dom = new JSDOM("<div id='root'></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, IS_REACT_ACT_ENVIRONMENT: true }); const host = document.querySelector("#root"), root = createRoot(host), invalidated = []; const C = await Panel(); const render = async nextActive => { await act(async () => root.render(React.createElement(C, { client, sessionKey: "s", busy: false, active: nextActive, onUnconfirmedChange: () => {}, onInvalidated: () => invalidated.push(true) }))); await flush(); }; await render(active); const click = async text => { const b = [...host.querySelectorAll("button")].find(x => x.textContent === text); assert.ok(b, text); await act(async () => b.click()); await flush(); }; return { host, render, click, invalidated, close: async () => { await act(async () => root.unmount()); dom.window.close(); } }; }
test.after(async () => { for (const dir of dirs) await rm(dir, { recursive: true, force: true }); });

test("隐藏的管理员面板不读取目录，打开后只显示可完结记录", async () => { let reads = 0; const client = { listManagedReferrals: async () => { reads += 1; return [referral(), referral("COMPLETED", "referral-b")]; }, createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "complete" }), changeReferralLifecycle: async () => ({}) }; const ui = await mount(client, false); try { assert.equal(reads, 0); await ui.render(true); assert.equal(reads, 1); assert.match(ui.host.textContent, /完结撒花/); assert.equal([...ui.host.querySelectorAll("button")].filter(x => x.textContent === "完结课程").length, 1); } finally { await ui.close(); } });
test("管理员完结成功与未知结果重试复用同一 submission", async () => { const calls = []; const client = { listManagedReferrals: async () => [referral()], createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "stable" }), changeReferralLifecycle: async command => { calls.push(command); if (calls.length === 1) throw new Error("network"); return {}; } }; const ui = await mount(client); try { await ui.click("完结课程"); assert.match(ui.host.textContent, /结果尚未确认/); await ui.click("安全重试原完结操作"); assert.equal(calls.length, 2); assert.equal(calls[0], calls[1]); assert.equal(calls[0].draft.command, "COMPLETE"); } finally { await ui.close(); } });
test("管理员401清空目录且迟到读取不能回填", async () => { const wait = later(); const client = { listManagedReferrals: () => wait.promise, createReferralLifecycleSubmission: draft => ({ draft, idempotencyKey: "x" }), changeReferralLifecycle: async () => ({}) }; const ui = await mount(client); try { await ui.render(false); await act(async () => wait.resolve([referral()])); await flush(); assert.doesNotMatch(ui.host.textContent, /学生甲/); client.listManagedReferrals = async () => { throw new ApiClientError(403, "FORBIDDEN_SCOPE"); }; await ui.render(true); assert.equal(ui.invalidated.length, 1); } finally { await ui.close(); } });
