import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { build } from "esbuild";
import { JSDOM } from "jsdom";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { ApiClientError } from "@teaching-research-alliance/client";

let Panel; let temp;
const flush = () => act(async () => { await new Promise((done) => setTimeout(done, 0)); });
const deferred = () => { let resolve; const promise = new Promise((accept) => { resolve = accept; }); return { promise, resolve }; };
const props = (node) => node[Object.keys(node).find((key) => key.startsWith("__reactProps$"))];
const session = (subject = "SYSTEM_ADMIN") => ({ sessionId: "s", accountId: "a", personId: "actor", roleContexts: [], currentRoleContext: { subject, scope: "GLOBAL", personId: "actor" } });
const item = (id, anomalyCodes = [], repairability = "READ_ONLY") => ({ auditItemId: `relationship:${id}`, relationshipId: id, relationshipFingerprint: `fingerprint:${id}`, relationshipType: "GROUP_LEADER", member: { personId: "member", nickname: "成员甲", personStatus: "ACTIVE" }, relatedPerson: { personId: "leader", nickname: "组长乙", personStatus: "ACTIVE" }, validFrom: "2026-09-01T00:00:00.000Z", validTo: null, effectiveScope: "普通周", status: "CURRENT", matchingRoleAssignmentIds: [], sourceChange: null, referenceCounts: { weeklyFees: 2, allocationSnapshots: 1, referrals: 0 }, anomalyCodes, repairability, repairBlockedReason: null, createdBy: { personId: "owner", nickname: "开发者" }, createdAt: "2026-09-01T00:00:00.000Z" });
const page = (items, nextCursor = null) => ({ snapshotAt: "2026-09-24T00:00:00.000Z", dataVersion: "v7", items, nextCursor });

test.before(async () => { temp = await mkdtemp(resolve(import.meta.dirname, ".relationship-audit-web-")); const output = resolve(temp, "panel.mjs"); await build({ entryPoints: [resolve(import.meta.dirname, "../src/person-relationship-audit-panel.tsx")], bundle: true, platform: "node", format: "esm", outfile: output, external: ["react", "react-dom", "@teaching-research-alliance/client"] }); ({ PersonRelationshipAuditPanel: Panel } = await import(output)); });
test.after(async () => { await rm(temp, { recursive: true, force: true }); });
async function mount(client, current = session(), key = "one") { const dom = new JSDOM("<div id='host'></div>", { url: "http://localhost" }); Object.assign(globalThis, { window: dom.window, document: dom.window.document, HTMLElement: dom.window.HTMLElement, IS_REACT_ACT_ENVIRONMENT: true }); const host = dom.window.document.querySelector("#host"); const root = createRoot(host); await act(async () => root.render(React.createElement(Panel, { client, session: current, sessionKey: key, onInvalidated: client.onInvalidated }))); await flush(); return { host, render: async (next, nextKey = key) => { await act(async () => root.render(React.createElement(Panel, { client, session: next, sessionKey: nextKey, onInvalidated: client.onInvalidated }))); await flush(); }, close: async () => { await act(async () => root.unmount()); dom.window.close(); } }; }
const base = (overrides = {}) => ({ hasRoleContext: true, listPersonRelationshipAudit: async () => page([item("r1")]), ...overrides });

test("筛选发送类型、异常状态、人员编号并显示快照/最小关系字段", async () => { const calls = []; const client = base({ listPersonRelationshipAudit: async (filter) => { calls.push(filter); return page([item("r1", ["RELATIONSHIP_OVERLAP"], "GROUP_LEADER_REGULAR_WEEK_PREVIEW")]); } }); const ui = await mount(client); try { await act(async () => props(ui.host.querySelector("select[aria-label='关系类型']")).onChange({ target: { value: "GROUP_LEADER" } })); await act(async () => props(ui.host.querySelector("select[aria-label='关系状态']")).onChange({ target: { value: "ANOMALOUS" } })); await act(async () => props(ui.host.querySelector("select[aria-label='异常码']")).onChange({ target: { value: "RELATIONSHIP_OVERLAP" } })); await act(async () => props(ui.host.querySelector("select[aria-label='可纠正性']")).onChange({ target: { value: "GROUP_LEADER_REGULAR_WEEK_PREVIEW" } })); await act(async () => props(ui.host.querySelector("input[aria-label='人员编号']")).onChange({ target: { value: "p-123" } })); await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "应用筛选").click()); await flush(); assert.deepEqual(calls.at(-1), { relationshipType: "GROUP_LEADER", status: "ANOMALOUS", anomalyCode: "RELATIONSHIP_OVERLAP", repairability: "GROUP_LEADER_REGULAR_WEEK_PREVIEW", personId: "p-123", limit: 50 }); assert.match(ui.host.textContent, /快照时间：2026-09-24/); assert.match(ui.host.textContent, /关系时间重叠/); assert.match(ui.host.textContent, /可在普通周组长变更办理/); assert.doesNotMatch(ui.host.textContent, /13800000000|银行卡号|工资金额|账户余额/); } finally { await ui.close(); } });
test("分页追加并显示空态", async () => { const calls = []; const client = base({ listPersonRelationshipAudit: async (filter) => { calls.push(filter); return calls.length === 1 ? page([item("r1")], "next") : page([item("r2")]); } }); const ui = await mount(client); try { assert.match(ui.host.textContent, /成员甲/); await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "加载下一页").click()); await flush(); assert.match(ui.host.textContent, /r2|组长乙/); assert.equal(calls.at(-1).cursor, "next"); const empty = await mount(base({ listPersonRelationshipAudit: async () => page([]) }), session(), "empty"); try { assert.match(empty.host.textContent, /当前筛选没有关系记录/); } finally { await empty.close(); } } finally { await ui.close(); } });
test("修改草稿筛选但未应用时分页沿用已应用筛选", async () => { const calls = []; const client = base({ listPersonRelationshipAudit: async (filter) => { calls.push(filter); return calls.length <= 2 ? page([item("r1")], "next") : page([item("r2")]); } }); const ui = await mount(client, session(), "stable-filter"); try { const typeSelect = ui.host.querySelector("select[aria-label='关系类型']"); await act(async () => props(typeSelect).onChange({ target: { value: "GROUP_LEADER" } })); await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "应用筛选").click()); await flush(); await act(async () => props(typeSelect).onChange({ target: { value: "TEACHING_MENTOR" } })); await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "加载下一页").click()); await flush(); assert.equal(calls.at(-1).relationshipType, "GROUP_LEADER"); assert.equal(calls.at(-1).cursor, "next"); } finally { await ui.close(); } });
test("分页版本冲突保留已读结果并要求刷新", async () => { let reads = 0; const client = base({ listPersonRelationshipAudit: async () => { if (++reads === 1) return page([item("r1")], "next"); throw new ApiClientError(409, "VERSION_CONFLICT"); } }); const ui = await mount(client, session(), "version-conflict"); try { await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "加载下一页").click()); await flush(); assert.match(ui.host.textContent, /审计数据已有变化，请刷新审计后继续/); assert.match(ui.host.textContent, /成员甲/); assert.equal([...ui.host.querySelectorAll("button")].some((node) => node.textContent === "加载下一页"), false); } finally { await ui.close(); } });
test("非零分润缺失关系显示为问题项而不伪造关联人和创建人", async () => { const missing = { ...item("missing"), auditItemId: "missing:GROUP_LEADER:member", relationshipId: null, relatedPerson: null, createdBy: null, createdAt: null, anomalyCodes: ["NONZERO_RECIPIENT_MISSING"], repairability: "REQUIRES_RELATIONSHIP_CORRECTION" }; const ui = await mount(base({ listPersonRelationshipAudit: async () => page([missing]) }), session(), "missing"); try { assert.match(ui.host.textContent, /关联人：缺失/); assert.match(ui.host.textContent, /非零分润缺少接收关系/); assert.match(ui.host.textContent, /创建人：系统审计/); } finally { await ui.close(); } });
test("规划导师普通周问题可筛选并显示管理员纠正入口", async () => { const calls = []; const planning = { ...item("planning", [], "PLANNING_MENTOR_REGULAR_WEEK_PREVIEW"), relationshipType: "PLANNING_MENTOR" }; const ui = await mount(base({ listPersonRelationshipAudit: async (filter) => { calls.push(filter); return page([planning]); } }), session(), "planning-repair"); try { await act(async () => props(ui.host.querySelector("select[aria-label='可纠正性']")).onChange({ target: { value: "PLANNING_MENTOR_REGULAR_WEEK_PREVIEW" } })); await act(async () => [...ui.host.querySelectorAll("button")].find((node) => node.textContent === "应用筛选").click()); await flush(); assert.equal(calls.at(-1).repairability, "PLANNING_MENTOR_REGULAR_WEEK_PREVIEW"); assert.match(ui.host.textContent, /可在普通周规划导师纠正办理/); } finally { await ui.close(); } });
test("401/403 清理身份，迟到旧目录不覆盖新身份", async () => { const invalidated = []; const late = deferred(); let reads = 0; const client = base({ onInvalidated: () => invalidated.push(true), listPersonRelationshipAudit: () => ++reads === 1 ? late.promise : Promise.resolve(page([item("fresh")])) }); const ui = await mount(client, session(), "old"); try { await ui.render(session("SYSTEM_ADMIN"), "new"); late.resolve(page([item("stale")])) ; await flush(); assert.doesNotMatch(ui.host.textContent, /stale/); assert.match(ui.host.textContent, /成员甲/); } finally { await ui.close(); } const denied = await mount(base({ onInvalidated: () => invalidated.push(true), listPersonRelationshipAudit: async () => { throw new ApiClientError(403, "FORBIDDEN_SCOPE"); } }), session(), "denied"); try { await flush(); assert.equal(invalidated.length, 1); } finally { await denied.close(); } });
